### ISSUE TITLE
Quote handler is totally wrong and it's miracle that it's working

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1058]

**Comment by huckeduster** [comment]
Does this issue include the problem, that "Insert pair quote" SmartKeys setting seems to be ignored for Perl files (tested in PyCharm Community 2017.3)? It always inserts the quote pair no matter the mentioned option is selected or not.

**Comment by hurricup** [comment]
This issue is obsolete, and smartkeys setting fixed in #1696  (available in master)
