### ISSUE TITLE
EOL annotations may be confusing

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1072]
For example:
```
my @arr = (
  'some json text', #@inject JSON
  'this is not json, but will be injected because annotation is just before this string',
);
```

**Comment by hurricup** [comment]
Removed

**Comment by StrikeForceZero** [comment]
I'm disappointed these were removed. My team was using these heavily for SQL statements...

**Comment by hurricup** [comment]
Sorry, but they are still misleading and causes other technical issues :(

**Comment by StrikeForceZero** [comment]
Is there a way to keep them in at (users own risk) until another option is available? 

What technical issues was it causing?

I feel removing them in a 2.X release without a depreciation notice is kinda sudden..

But without them I'm going to be forced into trying to maintain a fork with it available ):

```perl
$dbh->prepare( "SELECT foo FROM bar WHERE fizz = 'buzz'" ); #@inject MYSQL
```

was working great for us.

**Comment by hurricup** [comment]
1. They were initially experimental (like some features in perl) and could be removed anytime.
2. First problem is conceptual - described in this issue. Consider your well working example:
```
$dbh->prepare( "SELECT foo FROM bar WHERE fizz = 'buzz'" ); #@inject MYSQL
say 'Hello world';
```
Hello world will be injected with MYSQL. But it shoudn't be.
3. Also fast seeking of EOL annotation not working fine every time because PSI tree and document are not synced in every moment and sometimes caused exceptions, like [this one](http://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-235).

You are free to fork or just use previous version of the plugin. But I'm considering this type of annotations  as a really bad idea.

**Comment by StrikeForceZero** [comment]
1. Can you please link me where you declared it experimental? You opened the original issue #860 
Your initial mention was
```
New annotation: #@inject, allows you to inject other languages in strings. 
Annotation may be before the string, before the statement containing the string or in the end of line string ends. 
(NB: eol annotation may be misleading and should be considered experimental, see #1072. Need a feedback.)
```
2.) I see your point there. But couldn't only injecting strings left of the comment be a viable alternative?

Considering and declaring are different statements. semantic versioning hints that a minor upgrade such as 2.2 wouldn't break anything in 2.0-2.1. I really appreciate all of your work on this plugin and wish I could actually contribute to it (my java is a little rusty, and I haven't looked into intellij plugins before) but this is really bad practice in open source software. A depreciation warning for 2.x and removal in 3.0 if no alternatives were found would have been the way to go.

**Comment by hurricup** [comment]
`(NB: eol annotation may be misleading and should be considered experimental, see #1072. Need a feedback.)`
This states this feature as experimental. 

I'm deeply sorry that this change caused problem for you and your collegues. But for now I don't see the way to solve this problem properly. When and if i'll find the way - I'll gladly return this feature back.

```
#@inject MYSQL no left side here, should we ignore this one?
my($sql1,$sql2) = (
   'SELECT...',
   'SELECT...', #@inject MYSQL proper searching (without exception) will be resourseful
);
```
It's possible to make this work, but proper way is overcomplicated and resourseful.

Current scheme with before-string and before-statement annotations is pretty solid and enough in my opinion. The only problem here is that you've used this feature extensively last month and again, i'm sorry about it. You still can use last version that supports it to migrate or to continue using it if it's really so important to you.

**Comment by StrikeForceZero** [comment]
I have it forked for now and working, so no harm done - https://github.com/StrikeForceZero/Perl5-IDEA

I'll try and set some time aside to take a look at the code and see what thoughts come to mind.

Could we add a checkbox in plugin configuration dialog: "EOL annotations enable/disable (experimental)" instead of stripping it out completely?

**Comment by hurricup** [comment]
Ye, this probably the way. I could implement this proper way and make it optional and discouraged. Need to think.

**Comment by hurricup** [comment]
Btw, have you considered to pass your code through something like:
```
while(<>)
{
     if( s/#@inject MYSQL$// )
     {
            say '#@inject MYSQL';
     }
     say;
}
```
This will change your eol annotations to proper ones.

**Comment by StrikeForceZero** [comment]
Wait.... Do the annotations work above the strings in v2.200? And I've just been complaining about you removing them on the EOL? I thought they were removed all together...

**Comment by hurricup** [comment]
No. Only EOL been removed. You still may annotate before string or before statement, as i mentioned above.

**Comment by StrikeForceZero** [comment]
I'll have to try this again.. I swear that method wasn't working either.
If it is working then I apologize, I misinterpreted this entire issue since we all used EOL, whoops. Updating our code to put the annotation above the string would be fine although the EOL is nice to have. I'll report back.

**Comment by StrikeForceZero** [comment]
so I was indeed misinterpreting what feature was removed. I again apologize for coming off abrasive on the topic. 

"above the string" annotations still work. 

I'm ok with EOL annotations being removed. although without looking over the code I came up with a potential regex that matches all possible injections.

https://regex101.com/r/jJ1uD2/1

**Comment by hurricup** [comment]
Not sure I've got your idea about regex
