### ISSUE TITLE
Cannot create a file template with extension pm

### ISSUE THREAD

**Issue by l2trace** [Camelcade/Perl5-IDEA#1145]
I don't know if this part of #796  or not but whenever I  create a template that has the extension .pm it will not be listed in the available templates. If I change the extension to pl or anything it lists.

**Comment by hurricup** [comment]
Please, also specify you IDE name and version and OS/Java installed.

**Comment by l2trace** [comment]
Intellij Ultimate 
OSX (el capitan)
java 1.8.0_45   ( system ) 

The output of "About Intellij' 

IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by l2trace** [comment]
Just FYI:  If I uninstall the module the file template works as expected

**Comment by hurricup** [comment]
You know, I can't reproduce the problem.
![Works fine for me](http://joxi.net/eAOqBZbt48qDRm.png)

**Comment by l2trace** [comment]
Thanks for your reply.  Then there is something that I am missing.  Here is
a screencast https://www.youtube.com/watch?v=oOrN3qoFgp8&feature=youtu.be
that I made. Is there something I am missing ?
