### ISSUE TITLE
Specific Perl::Critc options can be passed via UI. Please update wiki.

### ISSUE THREAD

**Issue by kberov** [Camelcade/Perl5-IDEA#1206]
# Specific Perl::Critc options can be passed via UI
In the [wiki/Implemented-features](https://github.com/Camelcade/Perl5-IDEA/wiki/Implemented-features) I read:
"There is no any UI to configure Perl::Critic settings for now. Only enable/disable checkbox in Perl5 settings."
Now there is a text field labeled "Perl::Critic command line arguments".
I was able to pass a whole custom profile by just adding:
"--profile /path/to/my/.perlcriticrc"
Please update wiki.
Great work!
Thanks!

**Comment by hurricup** [comment]
Updated, thank you!
