### ISSUE TITLE
Perl Remote Debugger Steps seem to be incomplete to get it working.

### ISSUE THREAD

**Issue by swkanwar** [Camelcade/Perl5-IDEA#1231]
Hi,

I followed the steps under Debugger, to set the Remote Debugging. However the readMe.MD at http://search.cpan.org/~hurricup/Devel-Camelcadedb/ says that it is not working.
Can you please let me know how i can setup the remote debugging?

**Comment by hurricup** [comment]
Have you read https://github.com/Camelcade/Perl5-IDEA/wiki/Perl-Debugger ?
What step worked not as intended?

**Comment by swkanwar** [comment]
I am not able to install Devel::Camelcadedb

**Comment by hurricup** [comment]
This repo is about plugin. Debugger is there: https://github.com/Camelcade/Perl5-IDEA-Debugger/issues
And don't forget to read issue template.
