### ISSUE TITLE
Structure view varies between PerlDoc and sub list

### ISSUE THREAD

**Issue by gbegen** [Camelcade/Perl5-IDEA#1243]
I can't figure out a pattern to this, but sometimes the structure view will show the structure based on the PerlDoc within the file, and sometimes it just shows the list of subroutines in the module. It will sometimes switch while editing the file.

IDE: Android Studio 2.1.1
Build #AI-143.2821654, built on April 28, 2016

Perl5 Plugin: 2.005

JRE: 1.8.0_91-b14 x86_64

OS: OS X El Capitan
10.11.5

**Comment by hurricup** [comment]
My guess - it depends on your cursor position. Consider any perl package as two files (pod and perl) plaited together, instead perl file with pod injections. So when your cursor is in perl part - you see a perl   file structure and pod othewise.

If it's not like this, I need an example to reproduce.

**Comment by gbegen** [comment]
It is indeed based on cursor position, but it is a bit confusing because it depends on where the cursor is at the time the editor window is activated (or when the structure view is shown). I can get it to change by changing the active editor window and coming back or by closing the structure view and reopening it. Would it be possible to put a button into the structure window to control which mode it is in?

**Comment by hurricup** [comment]
Created a task for this https://github.com/Camelcade/Perl5-IDEA/issues/1256
