### ISSUE TITLE
Remote debugger doesn't allow configuration of remote port

### ISSUE THREAD

**Issue by gbegen** [Camelcade/Perl5-IDEA#1244]
The instructions at https://github.com/Camelcade/Perl5-IDEA/wiki/Perl-Debugger indicate that the port for the remote can be configured within the IDE, but this option is not available. I have to debug over port 12345.

IDE: Android Studio 2.1.1
Build #AI-143.2821654, built on April 28, 2016

Perl5 Plugin: 2.005

JRE: 1.8.0_91-b14 x86_64

OS: OS X El Capitan
10.11.5

**Comment by hurricup** [comment]
Are you saying that you don't have this option in debug configuration settings? 

![this one](http://joxi.net/GrqMZQWFNWbONr.png)

Basically, you should be able to set port in this option and set PERL5_DEBUG_PORT env variable to the same value on the perl side.

**Comment by gbegen** [comment]
This is what I have -
![screen shot 2016-06-21 at 11 52 56 am](https://cloud.githubusercontent.com/assets/516787/16242323/cce45a2e-37a6-11e6-8cfc-c539e545de57.png)

This was after updating to 2.100 that was published last weekend.

**Comment by VISTALL** [comment]
Can you give logs ? (Help -> Show log in Reveal) and attach idea.log file

**Comment by hurricup** [comment]
Could you please try to resize this window? May be some scrolling bug in IDEA for Mac?

**Comment by gbegen** [comment]
Not due to size of window:

![screen shot 2016-06-22 at 2 36 06 pm](https://cloud.githubusercontent.com/assets/516787/16284662/21474938-3887-11e6-8f6e-0fb48f8ea271.png)

idea.log file:

[idea.log.txt](https://github.com/Camelcade/Perl5-IDEA/files/328809/idea.log.txt)

**Comment by hurricup** [comment]
http://evstigneev.com/IDEA-Perl5-2.102.zip
