### ISSUE TITLE
Remote debugger too slow

### ISSUE THREAD

**Issue by gbegen** [Camelcade/Perl5-IDEA#1245]
There may be nothing to be done about this, but remote debugging a large project with many Moose classes takes way too long to start debugging for it to be useful. While I am waiting I can hit the pause button in the IDE and it will break during the compilation, so I know it is working on something, but it takes approximately 10 times longer for the project to be debuggable with the IDE than it does for local debugging via the standard Perl debugger on the command line over SSH to the remote machine.

IDE: Android Studio 2.1.1
Build #AI-143.2821654, built on April 28, 2016

Perl5 Plugin: 2.005

JRE: 1.8.0_91-b14 x86_64

OS: OS X El Capitan
10.11.5

**Comment by hurricup** [comment]
Moved to https://github.com/Camelcade/Perl5-IDEA-Debugger/issues/18

**Comment by hurricup** [comment]
You may try: http://evstigneev.com/IDEA-Perl5-2.101.zip
WIth Devel::Camelcadedb v.1.6.1.4 from CPAN
Should work much faster

**Comment by gbegen** [comment]
Much better. Thank you.
