### ISSUE TITLE
goto declaration for packaged variable

### ISSUE THREAD

**Issue by olvolkov** [Camelcade/Perl5-IDEA#1249]
Module can't parse and serch declaration for next structure:
**$package::variable = "";**
also array, hash..

**Comment by hurricup** [comment]
Guess you should read this: https://github.com/Camelcade/Perl5-IDEA/wiki/Perl-syntax-nuances

**Comment by hurricup** [comment]
We can't consider assignment as a declaration. Technically it is, i know, but there can be multiple of them and this is total mess. I've tried in the beginning.

**Comment by olvolkov** [comment]
it's a pity. I have a lot of project code with this declaration :(

**Comment by hurricup** [comment]
Than you need to add one declaration per global variable.
