### ISSUE TITLE
Cygwin support:  packages and perltidy/perlcritic scripts not recognized

### ISSUE THREAD

**Issue by bbarker** [Camelcade/Perl5-IDEA#1261]
* IDE 2016.1.3, #IU-145.1617
  * Perl5 plugin version: 2.100
  * JRE version 1.8.0_77-b03
  * Windows 10 + Cygwin64

Let me be the first to say I welcome the coming of the new Windows Bash shell ... but until it is stable I'm stuck with Cygwin :) So I thought I'd report this. But at least the .bat portion of the issue will likely still be relevant then.

I first installed the plugin before I installed many Perl 5 packages, but I wouldn't think that should make a difference; it didn't recognize the following two directories which seem to include most of my packages installed via CPAN (of course in IntellIJ I use the real Windows expansion of these, e.g., `C:\cygwin64\usr\lib\...`:

```
/usr/lib/perl5/site_perl/5.22/
/usr/lib/perl5/site_perl/5.22/x86_64-cygwin-threads
```

It did however seem to recognize the interpreter (Perl v5.22.2 (cygwin-thread-multi)) in C:\cygwin64\bin, though I'm not sure if this has any practical use except for debugging.

Another issue is that in Cygwin, the perltidy and perlcritic scripts are not by default .bat (installed them via CPAN), but the Camelcade plugin seems to expect that they are .bat files and will not let me use any other file type, so I symlinked them to .bat files. Unfortunately this did not seem to work (I checked that the .bat files were executable in cygwin):

```
Try to specify path to perltidy manually in Perl5 settings. Cannot run program "C:\cygwin64\usr\local\bin\perltidy.bat" (in directory "C:\cygwin64\home\brand_000\arXiv"): CreateProcess error=5, Access is denied
```

**Comment by bbarker** [comment]
I will also give Strawberry Perl a try ... :)

**Comment by hurricup** [comment]
You are right about .bat files. Currently plugin expects bat files on the win machines. I've never used cygwin myself, using strawberry and it's ok.  You could try to create a bat file which should just start your perltidy/perlcritic (don't forget to proxy arguments passed to the bat file), but not sure if it helps. How do you start them from windows cmd ? just perlcritic/perltidy? 

Considering libs. When you add an SDK, plugin runs perl one-liner, like `use v5.10;say for @INC;` and adds all printed paths as lib paths. As far as i know, these paths are hardcoded into the perl and should not change after additional modules installation, but may be I missing somthing. In this case, you can try to remove SDK and add it again, so plugin got current `@INC` list. Also, you could check if one-liner returns all necessary paths.
