### ISSUE TITLE
Parse error in .tt

### ISSUE THREAD

**Issue by earandap** [Camelcade/Perl5-IDEA#1262]
```javascript
<script type="text/javascript">
    var a = 5;
    [% b = 4 %]
    if([% b %] <= a) {
        console.log("Hello world");
    }
</script>
```

**Comment by hurricup** [comment]
JavaScript does not parses TT part correctly. Will check it. Thanks.

**Comment by hurricup** [comment]
Solution is not obvious, for now you could use intermediate variable.

**Comment by earandap** [comment]
The file is a template .tt where I am generating some JavaScript code. The variable b is provided by a controller with dynamic value, I included the declaration for showing you  consistent code.

I can use a intermediate variable, but in this project there are a lot of places where is used this snippet of code, and the code is legacy.

 But don't worry, in the new code i will use a work around.

**Comment by earandap** [comment]
Another example.
```javascript
<script type="text/javascript">

    [% IF comments # some comment here %]
     //javacript comment
    [% END %]

    function calculate(a){
    [% IF negative %]
        if( a < 0){
            alert('Negative');
            return false;
        }
    [% END %]
        return a+10;
    }

</script>
```

**Comment by hurricup** [comment]
Wow, this is nice bug :) Thanks

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-2.104.zip

**Comment by earandap** [comment]
Nice!!! Issue solved.
