### ISSUE TITLE
Declaring  HASH, Parse Error in TT

### ISSUE THREAD

**Issue by earandap** [Camelcade/Perl5-IDEA#1267]
[%
   #Example declaring hash
    hash = {
        'A'  => 1,
        'B'  => 2,
        'C'  => 3
    };
%]

The TT documentation is not clear about this kind of declaration, but indeed this is working in my code.

**Comment by hurricup** [comment]
Try http://evstigneev.com/IDEA-Perl5-2.105.zip
Could you please re-run code analysis with this one and send me other errors examples?

**Comment by earandap** [comment]
It is working now.
