### ISSUE TITLE
Support all methods of Template::Iterator in .tt

### ISSUE THREAD

**Issue by earandap** [Camelcade/Perl5-IDEA#1268]
http://template-toolkit.org/docs/modules/Template/Iterator.html

Parse Error for: 

```
<table>
[% FOREACH name IN ['Arthur', 'Ford', 'Trillian'] -%]
  <tr class="[% (loop.last ? "last" : "") %] ">
    <td>[% name %]</td>
  </tr>
[% END %]
</table>

```

**Comment by hurricup** [comment]
Not sure I get it
![This works fine](http://joxi.net/J2beb0kF4DZQ5m.png)

**Comment by earandap** [comment]
![tmol - -projects-ln-tmol - -tmweb-tpl-testing tt - webstorm 2016 1 3_002](https://cloud.githubusercontent.com/assets/10537721/16319331/426060e0-3969-11e6-9080-68ebada62c5e.png)

**Comment by earandap** [comment]
![menu_005](https://cloud.githubusercontent.com/assets/10537721/16320349/a004f860-396d-11e6-8eff-678c654564c5.png)

**Comment by hurricup** [comment]
I guess that you've set anycase tags flag in configuration. But in our project you are not using it.
TT does not allows to use keywords in identifiers

**Comment by hurricup** [comment]
Guess i need to add some adequate error reporting here.
