### ISSUE TITLE
Add support for custom extensions for TT2 support

### ISSUE THREAD

**Issue by highflying** [Camelcade/Perl5-IDEA#1269]
Our code bases uses *.template extension for TT2 files, please allow for custom extensions.

**Comment by hurricup** [comment]
Please, see `Settings -> Languages and Frameworks -> Perl -> Template Toolkit`
It is in there.
Also, please update to the most recent dev build, few important fixes there: http://evstigneev.com/IDEA-Perl5-2.105.zip

**Comment by hurricup** [comment]
Oh, and if this extension is not yet assigned to anything, you should just assign it to template toolkit file in `Settings -> Editor -> File types`
