### ISSUE TITLE
Req: View parameter info support?

### ISSUE THREAD

**Issue by lol768** [Camelcade/Perl5-IDEA#1270]
When writing code in languages like PHP or Java I can hit Ctrl+P (Parameter Info) and the IDE will give me a list of the current expected parameters for the method I'm calling:

![](https://lol768.com/i/63so5GC2H9n8sQ)

They appear in a grey popup:

![](https://lol768.com/i/CfUTf25NQSDRLg)

-----

When working with Perl and this plugin, it appears to be able to guess the arguments to a subroutine in the autocomplete menu as I begin typing its name:

![](https://lol768.com/i/1sIFXIxgzq55Hg)

However, pressing Ctrl+P when my caret is inside the brackets doesn't work - nothing happens:

![](https://lol768.com/i/A12K2-vpnFcI4Q)

Would this functionality be possible to add?

**Comment by lol768** [comment]
Hmm, looks like I can Ctrl+Hover on `new` to get something similar to pop up:

![](https://lol768.com/i/v4QtQ0MdovrS3w)

Is there a more convenient (keyboard way) of showing this?

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-2.108.zip

**Comment by lol768** [comment]
Hi @hurricup,

Can confirm it works perfectly,many thanks for implementing this :)

![](https://lol768.com/i/0sh7B0of2z8jnw)

Cheers.
