### ISSUE TITLE
Console log filter makes IDE freeze

### ISSUE THREAD

**Issue by denofevil** [Camelcade/Perl5-IDEA#1281]
I'm creating this report from [issue](https://youtrack.jetbrains.com/issue/RUBY-18244) that was reported in RubyMine bug tracker.

You can find corresponding thread dumps [here](https://youtrack.jetbrains.com/_persistent/threadDumps-20160702-121606-RM-145.1813.zip?file=74-325602&c=true)

* IDE: RubyMine 145.1813.1  
* JRE version: JetBrains  1.8.0_76-release-build198`
* OS: Mac OS X 10.11.5

**Comment by hurricup** [comment]
Thank you for proxying the report.
