### ISSUE TITLE
Deparse doesn't pick up all subs in an object

### ISSUE THREAD

**Issue by dezzak** [Camelcade/Perl5-IDEA#1283]
PhpStorm 2016.1.2
Build #PS-145.1616, built on May 24, 2016
JRE: 1.8.0_76-release-b198 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Perl5 plugin version: 2.111
Debian 8

I have a couple of packages where some subs aren't added to `_Deparsed_XSubs.pm`. Not sure if it is by design or not.

In the `DBI` package for database connections, `DBI::db` and `DBI::st` should both have `errstr()` subs. It looks from my brief look that these are defined on line 316-ish of DBI.pm. My Perl-fu doesn't extend to the magic that ties it all together, so I could just be Doing It Wrong.

My other example is `DateTime::Format::MySQL` which has a `parse_datetime()` method that isn't picked up. I think this is because it does some magic with `DateTime::Format::Builder`.

I'm not even sure if it's possible to use the documentation to build these method stubs either as I don't think there's a standard for annotating them.

This is more of a whishlist. I suppose in the meantime, I can manually add them to `_Deparsed_XSubs.pm`.

**Comment by hurricup** [comment]
`_Deparsed_XSubs` is only for XSubs. Perl extensions written in C and not available anyhow in perl code. If you can find sub definition it should be just handled a regular way. 

Described problems appears when code is kinda tricky. In case of DBI, database and statement handlers has their own specific classes (you may see them in the debuggger or pure perl implementation `DBI::PurePerl`). For example, database handler class name is `DBD::_::db`. I never knew it before started to work on plugin. And plugin has no any possibility to know it. 

There is an issue #1251 which plans to add external annotations, so you will be able to annotate `DBI->connect` with `#@returns DBD::_::db` without messing with sources. For now the only solution i see is to explicitly specify variable types, like `my DBD::_::db $dbh = DBI->connect...`. 

And you are right about `DateTime::Format::MySQL`. As you may see in sources it uses builder to make subs. And such things can be only handled via code in plugin. But perl has many such extensions, and i've got only two hands, so working on most popular ones. 

Howewer, i'm thinking about handling such situations globally at least for auto-completion using the same approach as been used for XSubs, but solution is not quite ready.

**Comment by dezzak** [comment]
@hurricup, thank you, for your prompt reply, as always. Your plugin is appreciated, and I fully understand that these are edge cases and not at the top of the priority list. I look forwards to playing with your solution at some point, and keep up the good work :-)
