### ISSUE TITLE
Warning when using FindBin, unable to find variable declaration, unable to find package file

### ISSUE THREAD

**Issue by eskaaren** [Camelcade/Perl5-IDEA#1284]
IDE: IntelliJ #IU-145.1617
Perl5 plugin: 2.111
JRE: 1.8.0_76-b198
Mac OSX 10.11.5

When writing my own packages in a lib directory I often use something like this:

```perl
use FindBin qw($Bin);
use lib "$Bin/lib";
use My::Package;
```

Issues:
1. The Bin part warns with "Unable to find variable declaration".
2. The My::Package part warns with "Unable to find package file".

By adding the lib dir to the classpath in project structure->SDKs->perl v5... the warning in issue 2 disappears. (It would be nicer to have this resolved automatically by the plugin?)

But issue 1 still gives a warning.

**Comment by hurricup** [comment]
1. There is no expclicit declaration of `$Bin` inside the `FindBin` module, so warning is right.
2. Expressions calculation may be implemented but not in near future. Perl's flexibility makes it hard.

It's important to understand that this plugin is not for simple scripts/playing with perl. It's been done to make it easier to develop large scale projects with transparent solid structure without a lot of perl magick.
