### ISSUE TITLE
Can't dismiss "Perl5 interpreter is not configured" warning

### ISSUE THREAD

**Issue by mcrawford-dayspring** [Camelcade/Perl5-IDEA#1295]
When I open up a Perl file in PHPStorm, I get a big yellow warning at the top saying "Perl5 interpreter is not configured" and there is no way to dismiss this warning.

I don't even have a Perl interpreter installed, so I can never configure it. I'm just reading legacy code and want the syntax highlighting. I just need a way to dismiss the warning.

PHPStorm #PS-162.1121.38
Plugin Version 2.117
JRE 1.8.0_91
Windows 10

**Comment by hurricup** [comment]
It was not supposed to be used this way. Will add an option to disable warning.

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-2.119.zip
