### ISSUE TITLE
Re-format with Perl::Tidy hangs, idea hangs as well.

### ISSUE THREAD

**Issue by YuraKotov** [Camelcade/Perl5-IDEA#1297]
Attempting to reformat big file (Perl/Tidy.pm) hangs.
Reformat is fine on the small files. 

IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_77-b03 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

Perl plugin version - 2.117

OS: Windows 7 Enterprise, SP1

Please see idea.log & tread dumps in attachment.
Legend of these files:
> Start idea
> perform Re-format with Perl::Tidy on tidy.pl file, in the attachment also.

**Comment by YuraKotov** [comment]
[threadDump-20160715-173917.txt](https://github.com/Camelcade/Perl5-IDEA/files/366205/threadDump-20160715-173917.txt)
[threadDump-20160715-173922.txt](https://github.com/Camelcade/Perl5-IDEA/files/366206/threadDump-20160715-173922.txt)
[threadDump-20160715-173927.txt](https://github.com/Camelcade/Perl5-IDEA/files/366204/threadDump-20160715-173927.txt)
[threadDump-20160715-173932.txt](https://github.com/Camelcade/Perl5-IDEA/files/366203/threadDump-20160715-173932.txt)
[threadDump-20160715-173937.txt](https://github.com/Camelcade/Perl5-IDEA/files/366202/threadDump-20160715-173937.txt)
[threadDump-20160715-173942.txt](https://github.com/Camelcade/Perl5-IDEA/files/366207/threadDump-20160715-173942.txt)
[threadDump-20160715-173947.txt](https://github.com/Camelcade/Perl5-IDEA/files/366209/threadDump-20160715-173947.txt)
[threadDump-20160715-173952.txt](https://github.com/Camelcade/Perl5-IDEA/files/366208/threadDump-20160715-173952.txt)
[tidy.txt](https://github.com/Camelcade/Perl5-IDEA/files/366210/tidy.txt)
[idea.txt](https://github.com/Camelcade/Perl5-IDEA/files/366211/idea.txt)

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-2.118.zip

**Comment by YuraKotov** [comment]
Doesn't work. No hang, but after reformatting the file became scratch.
Dumps happened. Do you need it?

**Comment by YuraKotov** [comment]
[threadDump-20160715-231408.txt](https://github.com/Camelcade/Perl5-IDEA/files/366771/threadDump-20160715-231408.txt)
[threadDump-20160715-231413.txt](https://github.com/Camelcade/Perl5-IDEA/files/366772/threadDump-20160715-231413.txt)
[threadDump-20160715-231418.txt](https://github.com/Camelcade/Perl5-IDEA/files/366773/threadDump-20160715-231418.txt)
[threadDump-20160715-231423.txt](https://github.com/Camelcade/Perl5-IDEA/files/366774/threadDump-20160715-231423.txt)

**Comment by YuraKotov** [comment]
Even small files that was fine with 2.117 became scratch now.

**Comment by YuraKotov** [comment]
Should I open a new issue for exception below in idea.log?
It is always in place.

2016-07-15 23:14:05,074 [  61835]   WARN - n.process.BaseOSProcessHandler - Must specify non-empty 'commandLine' parameter 
java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:56)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:58)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:58)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:51)
	at com.perl5.lang.perl.idea.actions.PerlFormatWithPerlTidyAction.actionPerformed(PerlFormatWithPerlTidyAction.java:122)

**Comment by hurricup** [comment]
Threads dump appeared because it takes a long time, doesn't matter. 
Please, try http://evstigneev.com/IDEA-Perl5-2.119.zip
Should work fine now with any file systems or files

**Comment by YuraKotov** [comment]
It works. Thanks

**Comment by hurricup** [comment]
Thank you for reporting this!
