### ISSUE TITLE
Colors & Fonts bold text not applying

### ISSUE THREAD

**Issue by Dgc2002** [Camelcade/Perl5-IDEA#1298]
#### Description:  
When editing the Colors & Fonts settings(Settings > Editor > Color & Fonts > Perl5) unchecking 'bold' for the Keyword entry updates the code in the preview window but not in the actual editor.

#### How to reproduce:  
http://puu.sh/q2HFP/7598c502ee.mp4  
  
For the video video I used  Fira Code as the font with "Enable font ligatures" checked.  
I've tested several fonts(Source Code Pro, Consolas, Segoe UI, and Calibri) and with ligatures disabled, the issue continued to occur.  

#### Proof of proper behavior:  
(Did you mean "Proof of improper behavior"?)

#### OS name and version:  
Windows 7 64bit

#### Java version:  
> JRE: 1.8.0_76-release-b216 x86
> JVM: OpenJDK Server VM by JetBrains s.r.o  

#### JetBrains product name and version:  
> IntelliJ IDEA 2016.2
> Build #IU-162.1121.32, built on July 9, 2016

#### Plugin version:  
2.117  

#### Priority:  
Low

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-2.118.zip
Should work fine now

**Comment by Dgc2002** [comment]
That did the trick, thank you!  
I was going to try these changes on my own but I currently don't have the time to set up the needed projects to modify/build an IntelliJ Plugin. I noticed some other discrepancies. On the left is how it is displayed in 'Editors > Colors & Fonts > Perl5' and on the right is in the actual editor.   
  
http://i.imgur.com/v8FuveG.png  

Ignoring syntax related issues:  
The following cannot be made non-bold
* `use strict;` (Both preview and editor remain bold)
* `use constant` 
* `#@method`
* `Scalar::Util::blessed();`
* `<STDIN>`  
  
Let me know if you'd rather me open a new issue for these.

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-2.119.zip
