### ISSUE TITLE
Feature : implementing typings for plugin

### ISSUE THREAD

**Issue by Zaitsev** [Camelcade/Perl5-IDEA#1300]
I just wonder if  it is possible to implement something like [Declaration Files](https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html) for typescript?

This decouples the plugin code and packages support and allows more developers to contribute to this excellent plugin. Also typings will make it possible to add support of the  custom packages and some static type checks. I believe auto-completion  will also be more intelligent.

**Comment by hurricup** [comment]
I guess you are talking about https://github.com/Camelcade/Perl5-IDEA/issues/1251

**Comment by Zaitsev** [comment]
Yes. BTW I propose some format for files and approach (IDEA has very decent support for TypeScript and typings so we could reuse some code/logic)
Should I remove issue or add comment to  #1251 ?

**Comment by hurricup** [comment]
I'll close this one. No need to duplicate same information there but any new ideas yes, better put in 1251.
