### ISSUE TITLE
Add warning for variables containing both Russian (or any) and English characters

### ISSUE THREAD

**Issue by almirus** [Camelcade/Perl5-IDEA#1309]
![image](https://cloud.githubusercontent.com/assets/16898685/17021163/c3c67746-4f4e-11e6-8e6e-262ba8dc4b6b.png)

**Comment by almirus** [comment]
for non utf8 source

**Comment by hurricup** [comment]
Please, check http://evstigneev.com/IDEA-Perl5-2.121.zip
