### ISSUE TITLE
Debugger stops at first executable line although "Debugger startup mode: Stop at first breakpoint" is set

### ISSUE THREAD

**Issue by dedeibel** [Camelcade/Perl5-IDEA#1310]
Hi,

I am using the setting **"Debugger startup mode: Stop at first breakpoint"** but when I connect to the IDE with emote perl debugging process (PERL5_DEBUG_ROLE=**client** ... perl -d:Camelcadedb) it initially **stops at the first executable line after BEGIN is done**.

It would be cool if this would work since it always costs some time to resume the debugger and then wait for the initialization to be finished before I can actually start debugging.
- IntelliJ IDEA 15.0.6 #IU-143.2370
- Perl5 Plugin version: Version: 2.117
- Camelcadedb Version: 1.6.1.6
- Perl Version: v5.14.2
- java version "1.8.0_91"
- Debian jessie 64bit

**Comment by hurricup** [comment]
Well, not sure what's wrong. Tried:

```
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

Summary of my perl5 (revision 5 version 14 subversion 2) configuration:

  Platform:
    osname=linux, osvers=3.16.0-4-amd64, archname=x86_64-linux
    uname='linux debian 3.16.0-4-amd64 #1 smp debian 3.16.7-ckt25-2 (2016-04-08) x86_64 gnulinux '
    config_args='-de -Dprefix=/root/perl5/perlbrew/perls/perl-5.14.2 -Aeval:scriptdir=/root/perl5/perlbrew/perls/perl-5.14.2/bin'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.9.2', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.19.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.19'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector'


Characteristics of this binary (from libperl):
  Compile-time options: PERL_DONT_CREATE_GVSV PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                        USE_LARGE_FILES USE_PERLIO USE_PERL_ATOF
  Locally applied patches:
        Devel::PatchPerl 1.38
  Built under linux
  Compiled at Jul 23 2016 12:44:51
  %ENV:
    PERL5_DEBUG_HOST="192.168.0.100"
    PERL5_DEBUG_PORT="12345"
    PERL5_DEBUG_ROLE="client"
    PERLBREW_BASHRC_VERSION="0.76"
    PERLBREW_HOME="/root/.perlbrew"
    PERLBREW_MANPATH="/root/perl5/perlbrew/perls/perl-5.14.2/man"
    PERLBREW_PATH="/root/perl5/perlbrew/bin:/root/perl5/perlbrew/perls/perl-5.14.2/bin"
    PERLBREW_PERL="perl-5.14.2"
    PERLBREW_ROOT="/root/perl5/perlbrew"
    PERLBREW_VERSION="0.76"
  @INC:
    /root/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/x86_64-linux
    /root/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2
    /root/perl5/perlbrew/perls/perl-5.14.2/lib/5.14.2/x86_64-linux
    /root/perl5/perlbrew/perls/perl-5.14.2/lib/5.14.2
```
with same as yours plugin and debugger versions.
And script like:
```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use v5.10;

say 'this';
say 'is';
say 'test';
```
And configuration like:
![this](http://joxi.net/823O6NqC60ZW32.png)

Starting script with: ` perl -d:Camelcadedb ./simpletest.pl`

If there is no breakpoints - just passes script. If there is at, let's say `say 'is';` it stops there.

**Comment by dedeibel** [comment]
Thanks a lot for looking into it!

I can reproduce it and I can recompile the plugin but I have no idea where to look.
Is there any way I could provide some helpful debug information, for example add some more logging output?

**Comment by hurricup** [comment]
My suggestion is that some module of your project doing something like `$DB::single = {some true value}`. This var is responsible for stepping in and i've seen such code in regular modules for debugging purposes I guess. 

The problem here is on the perl side and not depends on plugin at all.

**Comment by hurricup** [comment]
I'm afraid that i won't be able to help here without access to your codebase (or small example to reproduce). Anyway, it's something in your codebase (99%)

**Comment by cynovg** [comment]
У нас повторилась та же самая проблема. Не останавливается на брейкпоинтах. Причём, чуть раньше, примерно пол года назад у меня всё работало. Спросил у коллег, брекпоинты так же проскакивают. 

Проверит на примере. Согласно настройкам дебагер должен был остановиться на строке `say 'it';`, но этого не произошло. То есть, проблема повторяется.
![_165](https://user-images.githubusercontent.com/1086357/42807071-88aa1554-89b8-11e8-8488-768c80808494.png)

**Comment by hurricup** [comment]
Relates to #320

**Comment by Edorenta** [comment]
Can we reopen this? I am experiencing the exact same issue as @cynovg, with Perl 5.12, Camelcade and IntelliJ 2019.2.3

**Comment by hurricup** [comment]
@Edorenta please, start another issue and describe your case. Would be nice to see a screencast. In his case it was some local problem.
