### ISSUE TITLE
Go To Implementation(s)

### ISSUE THREAD

**Issue by nick2012** [Camelcade/Perl5-IDEA#1365]
Do you think that "Go To Implementation(s)" could be implemented?

**Comment by hurricup** [comment]
What do you mean? They are implemented.

**Comment by nick2012** [comment]
It shows a tooltip: No implementations found. http://imgur.com/r4uPokV

**Comment by hurricup** [comment]
You are looking at implementation. If you want to find usages, click alt-f7 or use context menu. Seems there is a bug with tooltip on declaration.

**Comment by nick2012** [comment]
Understood. One more side question. If I have lots of .pl script files in various folders, that use subroutines from various packages stored in a separate folder, can I do anything to maintain them easier, using IntelliJ + Perl5-IDEA? Can I import all of them somehow into one project?

**Comment by hurricup** [comment]
Have you read wiki? https://github.com/Camelcade/Perl5-IDEA/wiki

**Comment by nick2012** [comment]
I did, but I can only see how to create a module, and import an existing library. It doesn't say how to migrate a bunch of existing pl scripts under an intellij project.

**Comment by hurricup** [comment]
I'm not sure i understand what is the problem? Have you created project and module?

**Comment by nick2012** [comment]
Now I've created a module, using the root folder for the bunch of .pl scripts. It takes a long amount of time to index the files, because there are 15gb of non-related ones, scattered all over. Can I make it somehow to restrict indexing only to .pl and .pm files?

**Comment by hurricup** [comment]
Idea indexes all files it recognizes. So, only by moving perl files to a separate dir and/or mark non-related dirs as excluded

**Comment by nick2012** [comment]
There has to be some way to exclude files. SublimeText has a nice feature like this, but it lacks "find usages":

`{
	"folders":
	[
		{
			"path": "./folder/",
			"file_include_patterns": ["*.pl","*.pm"]
			
		},
		{
			"path": "./otherfolder/",
			"file_include_patterns": ["*.pl","*.pm"]
			
		}
	]
}
`
Can it be implemented? Or is there such an option available only through a regedit/xml config/ini file/etc?

**Comment by hurricup** [comment]
I'm not aware of such feature in idea. You may dig it's documentation.
Can we consider your question about 'go to declaration' solved?

**Comment by nick2012** [comment]
yes.
