### ISSUE TITLE
Something i would love to see in next version

### ISSUE THREAD

**Issue by davbizz** [Camelcade/Perl5-IDEA#1366]
1. Possibility to add a remote SDK for perl. I'm working a lot with linux remote servers and it will be fantastic to have all a remote SDK like the one for PHP or Python.
2.  Possibility to add Perl as additional framework to an existing project.

**Comment by hurricup** [comment]
1. Does remote sdk works in community version of pycharm? (for now plugin works similar in free/commercial IDEs)
2. Need more details here. You may add a perl module to the current project in IDEA or just configure perl interpreter in exisitng project in language-specific ides.

**Comment by hurricup** [comment]
Second one is fixed, for remote - please create another issue.
