### ISSUE TITLE
please make the debugger continue to listen for requests after disconnect when remote debugging

### ISSUE THREAD

**Issue by djstauffer** [Camelcade/Perl5-IDEA#1369]
Congrats on getting the debugger up and running!

I have one thing that I think would be very helpful for remote debugging.  If you are running against a Perl program that is part of a web application running on, say Apache, often the Perl program will be executed multiple times to handle different requests as part of the application.  Presently in order to debug this, you must restart the debugger in Intellij IDEA for every request.  This can be really annoying if you are wanting to debug multiple requests (for instance, when several ajax calls each hit a Perl program on the web server side).  

Is there a way to have the debugger in IDEA not stop listening to the port on behalf of Camelcade just because the first process that connected to it has disconnected?  It would be very nice if it would continue to listen unless it has been explicitly stopped by the user.

Thanks for all of your work on this!

**Comment by djstauffer** [comment]
As a workaround to this, I created a macro in IDEA that executes "Action:Resume" (F9), then "Action:Debug" (Shift-F9).  I assigned a single key to that macro.  That way, when I wish to resume execution of the remote Perl program (but continue debugging afterward), I can hit my assigned key instead of F9, and I get the behaviour I want.

**Comment by hurricup** [comment]
Ye, like the idea!

**Comment by alschbpk** [comment]
I think it is a very useful and necessary proposal.

Thanks for your work! The implementation work is greatly simplified.
