### ISSUE TITLE
Add support for methodName() function on Live Template creation. 

### ISSUE THREAD

**Issue by brnrc** [Camelcade/Perl5-IDEA#1370]
This is a feature request.
I would like to be able to use the set of language related [predefined functions](https://www.jetbrains.com/help/idea/2016.2/live-template-variables.html#pdtv) when creating Live Templates.
I don't know about the viability of this feature. (if JetBrains provide any mechanism to provide the implementation, or the required arguments for their predefined functions to work with any language. Thus, the viability investigation is implied in this ticket).

**Comment by hurricup** [comment]
IDEA's functions already works in perl templates. If request is still actual and you have specific needs - feel free to start an issue with them.
