### ISSUE TITLE
Can't choose HTML::Mason in Template Data Language

### ISSUE THREAD

**Issue by almirus** [Camelcade/Perl5-IDEA#1371]
IDE 15.0.6
Perl5 plugin version 2.2
JRE version JDK 1.7.0

![image](https://cloud.githubusercontent.com/assets/16898685/18202352/388b188a-7118-11e6-85c4-4cde471ba7fd.png)

**Comment by hurricup** [comment]
Template data language is different thing. 
For example: you may make HML::Mason with XML inside. XML here is data language.
If you need to make html files as mason, you should check Perl->HTML::Mason settings

**Comment by hurricup** [comment]
Not sure what Mason2 doing here :)
