### ISSUE TITLE
hash code format

### ISSUE THREAD

**Issue by nabat** [Camelcade/Perl5-IDEA#1384]
>   my $r_list = $Voip_sessions->reports( { PAGE_ROWS => 1000000,
>       COLS_NAME                                       => 1,
>       TYPE                                            => 'USERS'
>      } );

to

> ```
> my $r_list = $Voip_sessions->reports({
>   PAGE_ROWS => 1000000,
>   COLS_NAME => 1,
>   TYPE             => 'USERS'
> });
> ```

**Comment by hurricup** [comment]
Seems works now
