### ISSUE TITLE
cannot get CONSOLE output by intermittently

### ISSUE THREAD

**Issue by yasz** [Camelcade/Perl5-IDEA#1391]
i cannot get the below code output by intermittently in debug mode.
the debug console’s is always give the output together when the program exit. 

`print "1"."\n";
print "2"."\n";
print "3"."\n";
`

**Comment by hurricup** [comment]
And why not using debugger for debugging btw?

**Comment by kevinkenny** [comment]
@yasz don't forget to put:

`$| = 1; `

...at the start of your script if you want to see `stdout` output displayed in the debugger console window.

Just caught me out today after coming back to perl from a long hiatus:

http://stackoverflow.com/q/42398274/419
