### ISSUE TITLE
Subs not being resolved over 2nd level

### ISSUE THREAD

**Issue by grakkpl** [Camelcade/Perl5-IDEA#1393]
I'm getting error tooltip message "Unable to find sub definition, declaration..." on all 3rd level imported libraries. For example - in the code below I get error popups on "catdir" and "updir" only, "abs_path" and "dirname" work fine. Of course File::Spec::Functions is installed and Pycharm sends me to the declaration (the same way as in Cwd and File::Basename). It does not resolve any 3+ level subs.

use Cwd qw(abs_path);
use File::Basename qw(dirname);
use File::Spec::Functions qw(catdir updir);

our $INSTALL_DPATH = &abs_path( &**catdir**(&dirname(\_\_FILE\_\_), **&updir())** );

I'm working on Windows 8 and PyCharm Pro 2016.2 (IDEA-Perl5 2.200).

**Comment by hurricup** [comment]
There are no declarations/definitions of File::Spec::Functions. They are delegated somewhere at compile time. Plugin can't understand this yet
