### ISSUE TITLE
Can the grammar be used in standalone mode?

### ISSUE THREAD

**Issue by otrosien** [Camelcade/Perl5-IDEA#1405]
I'm working on a perl integration into sonarqube [1]. For this, I'm looking for a grammar that can parse perl as complete as possible. And from my understanding, that is yours. I would experiment with the standalone approach of Grammar-Kit [2] and try to load your perl grammar. Do you think it's feasible? What about licensing? Do you have stable versions of the grammar published somewhere?

Thanks in advance,
 Oliver

[1] https://github.com/otrosien/sonar-perl
[2] https://github.com/JetBrains/Grammar-Kit#standalone-usage

**Comment by VISTALL** [comment]
License - apache 2.
All grammars you can found here https://github.com/Camelcade/Perl5-IDEA/tree/master/grammar

>> Do you think it's feasible?
Nope. Perl parser have too many hacks and have very big dependency to intellij-platform.  

You need reuse all lexing/parsing code of Perl plugin, and evaluate IDEA environment (named Core). This way is not documented.

You need use this class for platform evaluation (https://github.com/JetBrains/intellij-community/blob/master/platform/core-impl/src/com/intellij/core/CoreApplicationEnvironment.java).

**Comment by hurricup** [comment]
Unsure if you can use at as is. But you may base your lexer/parser on our flex/bnf files.
