### ISSUE TITLE
Regex format bug

### ISSUE THREAD

**Issue by freemandigger** [Camelcade/Perl5-IDEA#1408]
`s/[^a-z0-9\-]//ig;`
after 1st format
`s/[ ^ a - z0 - 9\-]//ig;`
after 2nd format
`s/[ ^ a  -  z0  -  9\-]//ig;`
after XX format
`s/[ ^ a                 -                 z0                 -                 9\-]//ig;`
etc.

![img-2016-12-21-09-39-09](https://cloud.githubusercontent.com/assets/616983/21379768/68e5cbca-c761-11e6-97d2-cf63575f2c1d.png)

IntelliJ IDEA 2016.3.1
Build #IU-163.9166.29, built on December 9, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Plugin Version: 2016.3.1_7

macOS Sierra 10.12.2

[CodeStyle.txt](https://github.com/Camelcade/Perl5-IDEA/files/665635/CodeStyle.txt)

**Comment by hurricup** [comment]
Should be fine in next version

**Comment by freemandigger** [comment]
Thank you
