### ISSUE TITLE
Moose 'has' attributes not resolving or auto-completing?

### ISSUE THREAD

**Issue by StrikeForceZero** [Camelcade/Perl5-IDEA#1410]
I've read through the issues and can't exactly confirm if this is a part of https://github.com/Camelcade/Perl5-IDEA/issues/1260 or if there's another issue tracking it. 

the plugin doesn't seem to be resolving anything declared with 'has' in a moose package.

Perl5 plugin version: 2016.3.1_8
IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 17, 2016
JRE: 1.8.0_111-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

visually I get:
![image](https://cloud.githubusercontent.com/assets/983413/21504652/ccafc346-cc2e-11e6-9ba2-d0f3b90ac83b.png)

Source:

```perl
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

package Foo;
use strict;
use warnings FATAL => 'all';

use HTTP::Headers;
use HTTP::Response;
use HTTP::Status qw(:constants);

use Moose;
has 'response' => (
        is  => 'rw',
        isa => 'HTTP::Response',
    );

#@method
sub print_response_as_string {
    my Foo $self = shift;

    my $statusCode = HTTP::Status::HTTP_OK;
    my $response = HTTP::Response->new(HTTP::Status::status_message($statusCode), "hello world", HTTP::Headers->new());

    $self->{response} = $response;

    # all print a string containing "hello world"
    print $response->as_string();
    print $self->{response}->as_string();
    print $self->{'response'}->as_string();
    print $self->response->as_string();
}

no Moose;
1;
```

I've tried using [external annotations](https://github.com/Camelcade/Perl5-IDEA/wiki/External-Annotations) as a workaround. (which doesn't seem to have any effect, seperate issue?)

but currently the only workaround seems to be adding this to the package itself:

```perl
#@returns HTTP::Response;
sub response;
```

![image](https://cloud.githubusercontent.com/assets/983413/21504993/54e997e4-cc31-11e6-8a4a-5475559f41ec.png)

but that then offers the static reference as well:

```perl
Foo::response
```

**Comment by hurricup** [comment]
This is a probably bug of current version. Related to #1395 will address this asap, thank you.

**Comment by giddel** [comment]
It would be a great thing, if this would work. I often get the same effects because Moose is quite popular and often used.

**Comment by benignbala** [comment]
I too observe the same problem. It would be awesome if this gets fixed. Let me know if I can help in someway. And, thanks a lot for this plugin :)

**Comment by hurricup** [comment]
This is fixed now and should work in current plugin version.
