### ISSUE TITLE
Support `use variable`

### ISSUE THREAD

**Issue by slobo** [Camelcade/Perl5-IDEA#1411]
In one legacy code base, they utilize [variable](https://metacpan.org/pod/variable) extensively, so until it's exterminated it would be great if CamelCade could provide completion. 
So given something like this
```perl
package A;
use variable blah;

package B;
use base qw/A/;
```
Then we should be able to get `blah` as a suggestion on ```B->new->...```

If you point me in the right direction I can attempt to add support myself. Thanks.

**Comment by hurricup** [comment]
Sorry, but seems I won't find time for this :( too many actual issues and not enough time for really legacy stuff.
