### ISSUE TITLE
Support for Log4Perl

### ISSUE THREAD

**Issue by giddel** [Camelcade/Perl5-IDEA#1412]
First: Geat thanks for this wonderful plugin. It's reallly the best perl-pluging of all IDEs I've ever seen.

I'm heavily use the Log::Log4perl  logging framework in my projects. But the methods are not proper supported by Camelcade.

```
1 package MyPackage;
2  
3 use Log::Log4perl qw(get_logger); 
4 
5 sub myMethod {
6    my Log::Log4perl::Logger $logger = get_logger();
7 
8    $logger->debug("foo");
9 }
```

1)The type of the returned object (Log::Log4perl::Logger)  from the exported function get_logger() ist not regognized. I have to prefix ist manually (like line 6)
2) The exported sub "get_logger" ist marked by:
"Unable to find sub definition, declaration, constant definition or typeglob aliasing less... (Strg+F1) "
in line 6
3) If I type $logger->.. (line 8)  a lot of methods are suggested, but not the  most used logging-methods: debug, info,  warn, fatal.
4) The debug() - method itself is also remarked with the "Unable to find sub definition..."

Is it possible to fix it?

Here is a screenshot:
![log4perl](https://cloud.githubusercontent.com/assets/10463018/22506259/c6edba2c-e87f-11e6-82c1-37ab2ce1abff.png)

**Comment by hurricup** [comment]
There are no plain definitions of methods you've specified. They are all introduced using perl magick. Such kind of magick i s not yet supported.

**Comment by giddel** [comment]
I feared something like that.
Thanks anyway!

**Comment by hurricup** [comment]
Nono, don't close. may be sometime.

**Comment by giddel** [comment]
Wow, great. Thank you! I didn't belive for a solution after 2 years.
Unfortunately I'm not using Perl any more...
But hopefully someone else will enjoy on this now.
Good Job!

**Comment by exic** [comment]
Hey, I'm trying to use it now, but I still get 

```
Unable to find sub definition, declaration, constant definition or typeglob aliasing 
 Inspection info: Check if sub has been defined, declared or aliased with a typeglob. More information available in our wiki.
```

on all my log statements.

```
use Log::Log4perl qw(:easy);
Log::Log4perl->easy_init({ level => $DEBUG, layout => "%d %-5p %m%n" });
my $logger = Log::Log4perl->get_logger('blah');
$logger->info("...");
```

am I doing something wrong? I'm using version 2019.3.

**Comment by hurricup** [comment]
Works fine to me. 

![image](https://user-images.githubusercontent.com/2811330/72618637-9c409f80-394c-11ea-84c8-6b950be9ffa7.png)

Do you have `Log::Log4perl` installed in selected perl? What is perl version and module version?

**Comment by exic** [comment]
Hey, thanks for checking :-) I have those:

```
perl -v
This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
[...]
perl -MLog::Log4perl -le 'print $Log::Log4perl::VERSION'
1.49
perl test.pl                            
2020/01/19 13:20:52 INFO  ...
```
So Log4perl seems to be installed for this Perl (right?). In the settings, I just switched my Target Version to 5.28, too, but that didn't change anything:

![2020-01-19-132453_803x194_scrot](https://user-images.githubusercontent.com/242107/72680898-2d378800-3abf-11ea-94b1-a77018efa9ad.png)

Looking at your screenshot, it seems like your `info` is marked, too, isn't that the same warning as I am seeing?

If that's of relevance, I'm using PyCharm 2019.3.1.

**Comment by hurricup** [comment]
This is another story. https://github.com/Camelcade/Perl5-IDEA/wiki/Subs-resolution-status and https://github.com/Camelcade/Perl5-IDEA/wiki/Annotations

**Comment by exic** [comment]
Okay, I read both pages before but wasn't really able to see where Log4perl fits in there. Is it that it is a `$other_obj->method(); # we know that it's a Foo::Baz method` like in the example, but can't be found because it is not set up explicitly enough inside the Log4perl package (indeed, I didn't find a `sub info` in the module..)? I expected it to be fixed because of point `4)` in the original issue. Looks like you were able to fix `2)` which was similar, right?

Is there anything I can do except disabling the inspection altogether?

**Comment by hurricup** [comment]
Can't check myself atm, but its one of:
1. We can't understand what class object is $logger  (for this you may hint with annotation or exlicit typing)
2. There is no explicit definition or declaration of `info` method in that class. and this requires additional efforts on plugin side (or you may make a file with fake declarations, but this may be a bad way)
