### ISSUE TITLE
@INC not adding source paths while running test.

### ISSUE THREAD

**Issue by rlzaleski** [Camelcade/Perl5-IDEA#1414]
So I was trying to set up https://github.com/GrantStreetGroup/gitc

I got my perl environment set up, added a src and test source folder.  Navigation is working into libs, but from the test to code it's not seeing the lib dir.  When I try to run a test I get the following error.

It looks to me like the lib folder isn't getting added into @INC for the test directory.

/usr/bin/perl /home/rzaleski/IdeaProjects/gitc/t/reversible.t
1..18
Can't locate App/Gitc/Reversible.pm in @INC (you may need to install the App::Gitc::Reversible module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/rzaleski/IdeaProjects/gitc/t/reversible.t line 20.
BEGIN failed--compilation aborted at /home/rzaleski/IdeaProjects/gitc/t/reversible.t line 20.
# Looks like your test exited with 2 before it could output anything.

![image](https://cloud.githubusercontent.com/assets/623972/21989698/f07f8c9c-dbd9-11e6-8ef9-194d3c0efbf5.png)

2016.3.2 Dec 21 build.  I just started with a fresh installed, and added camelcade Friday.  

Perl Plugin 2016.3.1_8

Perl version 5.18.2

JAVA - openjdk version "1.8.0_112-release" - just what comes bundled with IntelliJ

System Java preinstalled is:
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)

Ubuntu 14.04.5 LTS

Overall the IDE is pretty kool.

**Comment by hurricup** [comment]
have you marked lib dir as library root as described in getting started wiki?

**Comment by rlzaleski** [comment]
It looks to me like I have it set up correctly.

![image](https://cloud.githubusercontent.com/assets/623972/21994658/cfec2192-dbee-11e6-9184-7eaadaf99be8.png)

**Comment by hurricup** [comment]
I see. Please, delete module and create perl module.

**Comment by rlzaleski** [comment]
Wait, looking at it closer, I guess the "you mark your lib directory as a library source" is where I'm getting lost.

**Comment by rlzaleski** [comment]
That did it, thanks!   I'm not sure why my original import failed though :(
