### ISSUE TITLE
Readonly support

### ISSUE THREAD

**Issue by pJunger** [Camelcade/Perl5-IDEA#1415]
Hi,

when using the Readonly module with shallow-readonly variables, Camelcade shows a syntax error (Semicolon expected).
    
    use Readonly;

    Readonly my $test_var => 2;

The space between 'Readonly' and 'my' is underscored and the hover text 'Semicolon expected' is shown.

Versions:
IntelliJ CE: 2017.1 EAP - Build #IC-171.2014.21
Perl Plugin: 2016.3.1_8
JRE: 1.8.0_112-release-b621 amd64
OS: Windows 7 Prof. SP1

**Comment by hurricup** [comment]
crap. Well, it's a hack in our perl lexer (cause it works in different way). 

In short: any unknown camelcased bareword considered to be a package. Cause it's uncommon for perl to have such subs. I'll check what can i do here.

**Comment by pJunger** [comment]
Thank you! In any case it is not a showstopper ;)
