### ISSUE TITLE
Formatting ranges breaks code

### ISSUE THREAD

**Issue by pJunger** [Camelcade/Perl5-IDEA#1418]
Hi,

calling the formatter on any ranges separates the '..' operator and breaks for-loops etc.

`my @a = [1..2];`
becomes
`my @a = [ 1.  .  2 ];`
which effectively creates a ['12'].

Versions:
IntelliJ CE: 2017.1 EAP - Build #IC-171.2014.21
Perl Plugin: 2016.3.1_8
JRE: 1.8.0_112-release-b621 amd64
OS: Windows 7 Prof. SP1

**Comment by codehead** [comment]
I can confirm that this bug still exists, regardless of the "Spaces/Around Operators/Range operators" setting.
This is only a problem for ranges that start with an integer. Does not happen to ranges that start with a variable. i.e.
`my @a = $a..$b; # OK`
`my @a = $a..10; # OK`
`my @a = 10..$a; # NOT OK: turns into "10. .$a"`

WebStorm 2017.1.4
Build #WS-171.4694.29, built on June 7, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

**Comment by hurricup** [comment]
Sorry, I've missed this one :( for now - help before .. should help
