### ISSUE TITLE
Additional classpath not used in execution

### ISSUE THREAD

**Issue by bboehmke** [Camelcade/Perl5-IDEA#1421]
I have some additional classpaths configured for a perl SDK and they are working great in the editor.

If I execute a script with this SDK the modules in the additional classpaths are not found.
As workaround I can manually set the PERL5LIB and the script works fine but this is not really convenient.

OS: Windows 7 64bit
Java: 1.8
Intellij: 2016.3.3
Plugin: 2016.3.1_8
Perl: ActivePerl 5.16

**Comment by hurricup** [comment]
It seems to me that there is no real problem with classroots. The point is that perl works with it's own source types: libraries (they are transparently added as classroots). And they are being added with -I param when running the script:

![screenshot](http://dl4.joxi.net/drive/2017/01/30/0004/3351/294167/67/1835b0c264.png)

This source root available in Perl5 modules.

You may check a proper setup in [our wiki](https://github.com/Camelcade/Perl5-IDEA/wiki/Getting-started:-IntelliJ-IDEA)

Your approach have few flaws:
1. What if you've got perl5lib from other project?
2. What if you've got different SDK on module?
3. What if you are working in PHPStorm or smth (they have a PHP/Python/etc) as sdk and perl has it's own settings. 
4. Currently, library paths being handled in com.perl5.lang.perl.util.PerlRunUtil#getPerlCommandLine(com.intellij.openapi.project.Project, java.lang.String, com.intellij.openapi.vfs.VirtualFile, java.lang.String...)

Sorry thati've not answered you earlier and thanks for your efforts :)

**Comment by bboehmke** [comment]
You are right if I add the library directory to the project it may work but this is not very useful for our setup at work:
There we are using a perl environment that is extend with some additional classes outside the default class path. For better reuse of this environment it is stored on a different location that the project specific scripts. So it is not very easy to add this lib directories to the project.

If I add this directories to the class path it works fine for the inspection and it would be great if also the execution work without manually setting the PERL5LIB environment variable.


Regarding your remarks:
1. That is right I only handled it if it was set from run configuration -> see 4.
2. That is right too but I think it should be possible to detect the module of the file that is be executed (I mean I see a similar function the code)
3. That is also right and for this I have no solution.
4. I have already searched for some time to find com.perl5.lang.perl.idea.run.PerlRunProfileState#calcEnv(...) and it seems I missed this function that already handles the other libraries. The handling of the class path would be better at this location and I will try to reimplement my code here (with handling of 1. & 2.)

If you answered earlier I might not have looked into the code and see how much work was spend to write this plugin.

**Comment by hurricup** [comment]
For now there are no support for external libraries in perl module. I'm using symlinks myself (or git submodules). There are some plans, but requires project structure rework. 
Your solution may be work fine for your case but not for most cases :(

**Comment by bboehmke** [comment]
I think there are not so much changes required.
I updated the pull request with a better solution that should work for the most requirements.
Maybe this is a solution for this problem or can be used to solve the issue.
