### ISSUE TITLE
Complete Current Statement behavior

### ISSUE THREAD

**Issue by Dgc2002** [Camelcade/Perl5-IDEA#1425]
Currently the 'Complete Current Statement' behavior is inconsistent with other JetBrains IDEs, as far as I know anyway.  
  
Here is how it behaves in PHPStorm:  
[A colon is appended to the statement](http://i.imgur.com/LRqTXiC.gifv)  
  
And here it is in the Perl plugin:  
[A new line is inserted below the statement and the cursor jumps to it](http://i.imgur.com/NDQtlsY.gifv)  
  
Could the PHPStorm behavior be introduced as the default or configurable behavior?  
  
Edit:  
  
The Perl5 plugin is being run in IntelliJ IDEA 2017.1 EAP, though I believe this behavior has been present in non-EAP releases.

**Comment by Dgc2002** [comment]
I was about to open an issue about this but I beat myself to it.  
  
Any idea when/if this might make it in the plugin @hurricup?

**Comment by hurricup** [comment]
Well, I could do some dumb implementation. But proper one could be tricky because of nature of perl

**Comment by Dgc2002** [comment]
Understood. Personally a dumb implementation would likely fit my needs, but it's your call if you want to include a 'dumb implementation' in your plugin.  
  
Very often I'm just trying to use it to complete simple things like  
  
    print("blalba_CURSOR_")
to

    print("blalba");_CURSOR_

or 

    if($foo == "bar"_CURSOR_)  

to  

    if($foo == "bar"){
        _CURSOR_
    }  
  
  
Though even the simple one-line semicolon completion would be amazing.

**Comment by hurricup** [comment]
The last one supposed to be handled with livetemplate `if`, but i've got your point. I'll try to make something in next release, but no promisses. Big plans.

**Comment by Dgc2002** [comment]
Sounds great. Thanks for all your work on this plugin =)

**Comment by MenkeTechnologies** [comment]
Love the plugin.  Are you planning to add support for Complete Current Statement statement eventually?  That is the only functionality I miss.  Thanks a lot.

**Comment by hurricup** [comment]
@MenkeTechnologies could you please provied cases you'd like to be handled? There is on fix-all solution, more like per-case

**Comment by hurricup** [comment]
Related to #753
