### ISSUE TITLE
Unable to set Perl5 interpreter

### ISSUE THREAD

**Issue by pgl-carma** [Camelcade/Perl5-IDEA#1431]
IDE name: Webstorm 2017.1
Perl5 plugin version: 2017.1.1
JRE version: unknown - `java --version` prompts to install Java
OS: macOS Sierra

----

When I load a perl file, I get a yellow warning box saying

> Perl5 interpreter not configured

When choosing "Configure", the input box for the interpreter path doesn't let me type anything in, and when I try and choose something (eg, `/usr/bin/perl`), it doesn't fill out the field.

**Comment by hurricup** [comment]
This is a IDEA mac ui problem. Please, choose /usr/bin folder, not perl file itself.

**Comment by pgl-carma** [comment]
Thanks! That worked. Perhaps renaming the setting to "Perl5 interpreter directory" might be more clear to dummies like me. :)

**Comment by hurricup** [comment]
Nah, it shouldn't work this way. Should not allow you to choose files at all. Thinking about add a hack there to fix such selections

**Comment by drmmr763** [comment]
ran into this issue this morning. thanks for having an issue to help me figure it out. Wouldn't mind a note in the wiki or even a code fix if possible. Cheers!
