### ISSUE TITLE
High cpu usage while inspecting file

### ISSUE THREAD

**Issue by giddel** [Camelcade/Perl5-IDEA#1432]
Since the latest update of IntelliJ IDEA the inspection of my perl files  in the editor (gray eye symbol in the top right corner) consumes a hughe amount of cpu.  My notebook sounds like a drohne when taking off ;-) When the inspection is done (yellow quadrat in the top right corner) the cpu usage goes to normal level.

Is it a point of intelliJ or of CamelCade or of booth?

Versions:

IntelliJ IDEA 2017.1.1
Build #IC-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-71-generic

Camelcade plugin:
Version: 2017.1.1

**Comment by hurricup** [comment]
can be any of them. Would be nice to have a sample to reproduce.

**Comment by giddel** [comment]
Hmm.
The project I'm working on is pretty large .. and internal only.
But I will set up a new empty project and look what happens.

**Comment by hurricup** [comment]
Is problem is still actual?
