### ISSUE TITLE
Add feature to switch alignment of hash properties and variable assignments

### ISSUE THREAD

**Issue by samosad** [Camelcade/Perl5-IDEA#1433]
Please add an option to disable automatic alignment in code style settings.
Now it always aligns hash properties by `=>` sign:
```perl
my $hashref = {
        veryveryverylongkey1 => 42,
        key2                 => [ 69 ],
};
```
And TT variables by  `=` sign:
```
[% WRAPPER
        classes                            = ''
        size                               = 'small'
        is_added_card_add_checkbox_visible = 0
    %]
```
Also in files TT formatter sometimes adds extra indent before closing `%]` tag.

It would be great to have an option to tweak this alignment logic in settings, for example like in JavaScript code style settings ([screenshot](https://s.mail.ru/6shN/1pLCN7xwr))

**Comment by hurricup** [comment]
Fixed in perl
