### ISSUE TITLE
Perl5 libs settings (from perl5shared.xml) is not pulled on startup

### ISSUE THREAD

**Issue by YuraKotov** [Camelcade/Perl5-IDEA#1436]
I open a project;
"use strict;" - is in error - "Unable to find ...";
Open File->Settings->Perl5 libs
Add Content Root: C:\Strawberry\perl
Make lib subfolder as Library and click Apply;

perl5shared.xml after that is:
< project version="4">
< component name="Perl5Settings">
< option name="libRootUrls">
< list>
< option value="file://C:/Strawberry/perl/lib"/>
< /list>
< /option>
< /component>
< /project>

No error for "use strict;" after that!

Then I close Clion window and reopen it.
"use strict;" - is in error again...

I have to repeat steps above each time...

CLion 2017.1.1
Build #CL-171.4073.41, built on April 12, 2017
Licensed to EMC Corporation / Yuri Kotov
Subscription is active until September 13, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Perl plugin version - 2017.1.1

**Comment by hurricup** [comment]
Is this problem actual?
