### ISSUE TITLE
Can't debug array or hash?

### ISSUE THREAD

**Issue by kelvenchi** [Camelcade/Perl5-IDEA#1437]
When I debug the program , I need to know all elements of an array , but it show me a number? Does the debugger only use scalar environment?

e.g.: I have got pieces of data from MySQL database and each row of the data was a hash and  was in an array. How can I see the whole content of this array?

**Comment by hurricup** [comment]
no

**Comment by kelvenchi** [comment]
so, what should I do if I wanna know the content of an array?

**Comment by hurricup** [comment]
you may start from reading issue template

**Comment by kelvenchi** [comment]
ok, thanks
