### ISSUE TITLE
'Show usages of Sub definition' not working

### ISSUE THREAD

**Issue by CaballerosTeam** [Camelcade/Perl5-IDEA#1476]
### About
**IDE:** IntelliJ IDEA 2017.1.4, Build #IU-171.4694.23, built on June 6, 2017
**JRE:** 1.8.0_112-release-736-b21 amd64
**JVM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o
**OS:** Linux 4.4.72-18.12-default
**Plugin:** 2017.1.2

### Example project
[pview.zip](https://github.com/Camelcade/Perl5-IDEA/files/1094702/pview.zip)

### Description
'Show usages of Sub definition' not working.

#### How to reproduce
1. setup project from archive
2. open package FL::PVIEW::SpamUrl
3. `Ctrl + click` (or `Ctrl + B`) on `append_to_name` subroutine call in `encode_to` (line 12)
* 3.1. It should navigate to `append_to_name` subroutine definition (at this step all works well)
* 3.2. You can perform one more check of 'Go to declaration' from `pview/FLPview_0.0.1.161_2080/FLPview/www/cmd/view` perl script
4. `Ctrl + click` (or `Ctrl + Alt + 7`) on `append_to_name`
* 4.1. **expected result:** show subroutine usages
* 4.2 **actual result:** 'No usages found in All Places'

**Comment by hurricup** [comment]
It works for me with this project

**Comment by CaballerosTeam** [comment]
Solved. The reason is that the project library root directory was added as external library in SDK configuration.
