### ISSUE TITLE
Indentation problems with subtests and moose attributes

### ISSUE THREAD

**Issue by aptituz** [Camelcade/Perl5-IDEA#1525]
Hi,

I stumbled upon several cases where the indentation mechanisms in CamelCade adds to many spaces in front of a continuation line. First noticed that issue while writing tests, utilizing the subtest functionality of Test::More, but it also affects Moose attributes.

As it seems the problem occurs when an anonymous sub, a hash or block ist part of a subroutine's argument list.

Example:
```
subtest "foo" => sub {
        # this line is indented wrongly (8 instead of 4 spaces)
    };
```

What I'd expect:
```
subtest "foo" => sub {
    # this line is indented right
};
```

The same applies for hash arguments like in Moose attribute definitions:
```
has "foo" => (
         # too much space
         is => 'ro'
    );
```

As it seems CamelCade does not properly detect where the opening of the sub/hash/etc. occurs, since the indenting is exactly the same when moving the braces to the next line, e.g.

```
has "foo" =>
    (
        is => 'ro'
    );
```

## Version information
* Idea Version: Build #IU-171.4424.56, built on May 12, 2017
* JRE: 1.8.0_112-release-736-b21 x86_64
* OS: Mac OS X 10.12.5
* Perl5 Plugin version: 2017.1.3

**Comment by hurricup** [comment]
The question here is how we should handle sequentional constructions. I like version:
```
subtest foo => sub{
   # code
};
```
but what if we've got:
```
something bla => sub{
   #code
} => sub{
   # bla
}, 
$a;
``` 
not so pretty...

**Comment by aptituz** [comment]
That's maybe just me, but: Not exactly sure how this is related, to be honest?

**Comment by hurricup** [comment]
What exactly?

**Comment by aptituz** [comment]
I have trouble to imagine what kind of real world example this problem could apply to. Maybe do you have a less contrived example, e.g. real code?

**Comment by hurricup** [comment]
This is a valid code. How should it be formatted? List of anon subs, hashes, arrays, mixed with references, pretty possible. No time for search proofs though.

**Comment by aptituz** [comment]
Well, I haven't seen such constructs so far and I wonder if it's worth optimising for them. So I think what you consider to be "not so pretty" is okayish, given that the subtest and has-Case is actually wrong.

**Comment by hurricup** [comment]
Feel free to build from master and check if it's ok now.
