### ISSUE TITLE
Variable shadowing inspection false positive in signtatures

### ISSUE THREAD

**Issue by elcamlost** [Camelcade/Perl5-IDEA#1532]
* PhpStorm 2017.1.4 Build #PS-171.4694.2, built on May 16, 2017
Perl 
   * Perl5 plugin 2017.4
  * JRE: 1.8.0_112-release-736-b21 x86_64
  * JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  * Mac OS X 10.12.5

This code before version 2017.3 was correctly parsed by perl plugin 
```perl
use perl 5.026;
use feature qw/signatures/;
no warningns qw/experimental::signatures/;

sub t ($aa, $bb) {
   return $aa + $bb;
}

t(1,2);
```

Starting from 2017.3 all variable definitions before sub body doesn't parse correctly. I see warning about $aa and $bb variables `current variable declarations shadows previous declaration at line 5`.

**Comment by hurricup** [comment]
what is the meaning of `$$bb`?

**Comment by elcamlost** [comment]
Oh, just a typo, i mean `$bb`, of course.

**Comment by hurricup** [comment]
Ok, than I see the problem. will fix. Thank you.

**Comment by hurricup** [comment]
Problem is solved, but I won't release right now. If it's necessary, you may build plugin yourself. Just fetch this repo, and run `gradlew buildPlugin` than install built plugin from `build/distributions` directory.
