### ISSUE TITLE
Incorrect reader handling with bare constraints

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1533]
Found some strange behaviour with isa type contsraint, Types::Standard type library and syntax highlighting.

```perl
use Moo;
use Types::Standard -all;

has 'attr1' => ( 'is' => 'ro', isa => Int );
has '_attr2' => ( 'is' => 'ro', isa => Int, 'reader' => 'attr2' );
has '_attr3' => ( 'is' => 'ro', isa => Maybe[Int], 'reader' => 'attr3' );
```

`attr1`, `attr2` (after reader) and `_attr3` (not `attr3` after reader)  are highlighted as function names (with yellow in my theme).

So complex constraints from Type::Tiny break highlighting somehow.

That's very minor bug which doesn't affect my work at all. Just for your knowledge, that such syntax for type constraints exists.

**Comment by hurricup** [comment]
Looks like a bug, I'll check.
Also, please note, that types are not currently supported so, this won't work right. Atm isa is treated like package name and should be quoted to work. like `isa => 'Foo::Bar'`
I've not yet investigated types deeply (see #1509) but possibly bare types won't ever work. Not sure yet.

**Comment by hurricup** [comment]
Or may be the will be:
```
use Moo;
use warnings;
use strict;
use Types::Standard ('-all');
has('attr1', ('is', 'ro', 'isa', &Int()));
has('_attr2', ('is', 'ro', 'isa', &Int(), 'reader', 'attr2'));
has('_attr3', ('is', 'ro', 'isa', &Maybe([&Int()]), 'reader', 'attr3'));
```

**Comment by elcamlost** [comment]
In Moo type constraint is a plain function which must die if constraint fails.
So syntax like 
```perl
has 'attr1' => ( 'is' => 'ro', isa => sub { die unless $_[0] =~ /^(-|+)?[0-9]+$/ );
```
also quite popular in Moo.
