### ISSUE TITLE
Feature Request: Switch Package Support

### ISSUE THREAD

**Issue by jasekiw** [Camelcade/Perl5-IDEA#1544]
It would be great if when the Switch package in included as a library for the editor not show syntax errors for writing a switch case.

[Example](http://search.cpan.org/~chorny/Switch-2.17/Switch.pm)

**Comment by hurricup** [comment]
IDEA utilizes incremental parsing, like when you editing statement - parses only this statement. So there is no ay to know that there is a Switch somewhere. Also this won't be 100% reliable. 
So only manual option for now. (in case you don't know there is a switch support, see Perl5 settings)
