### ISSUE TITLE
Headless engine how-to?

### ISSUE THREAD

**Issue by aronlurie** [Camelcade/Perl5-IDEA#1546]
I want to use Camelcade for its Perl autocompletion and parsing, but I am limited to using an editor that I can run in a terminal via ssh. (e.g. vim, emacs.)

Is it possible to invoke the parser and autocompletion engines from the command line? If so, how?

If you can point me in the right direction, I'll happily contribute to the wiki with a page on the topic.

Thanks!

**Comment by hurricup** [comment]
As far as I know - there is no such possibility. The only way in your case is to have local project, configure remote server  and auto-uploading to the remote server (available in commercial products only)
So, you will work with local project but changed files being uploaded automatically.

**Comment by aronlurie** [comment]
Can you tell me more about how to setup the remote/local configuration? Is there documentation somewhere? I know it is out of the scope of this project, but I appreciate the help.

**Comment by hurricup** [comment]
You may start here https://www.jetbrains.com/help/idea/deployment-working-with-web-servers.html
