### ISSUE TITLE
Q: On the Fly Syntax Checker supported?

### ISSUE THREAD

**Issue by bakkiaraj** [Camelcade/Perl5-IDEA#1557]
Hi,

I had migrated from Eclipse + EPIC plugin to IDEA + CamelCade. Its awesome in syntax highlights and understanding Moose objects. Thanks :)

Seems that I miss on the fly syntax check from Eclipse + EPIC. Any plan to adopt Syntax Checks and mark lines as red?

**Comment by hurricup** [comment]
I've never used Eclipse, so I guess i need more details.

**Comment by bakkiaraj** [comment]
I have uploaded [Eclipse + EPIC screen shot](https://ibb.co/giBBKv)

You could see , Syntax check and it high lights error because I did not declare variable with "my / our" and I have used "use strict". Basically, on the fly it does "perl -c <filename.pl>" and high-lights errors.

[Eclipse EPIC Settings screen shot](https://ibb.co/duTaev) shows that the "Syntax Check" behaviour can be controlled via "Validate Source when ..." option

Please also check , http://www.epic-ide.org/  and click "On-the-fly syntax check"

**Comment by hurricup** [comment]
Have you tried the same code in Camelcade?

**Comment by bakkiaraj** [comment]
Yes. CamelCade is not showing Syntax Error. [IDEA+ CamelCade Screenshot](https://ibb.co/dyLCcF)

**Comment by hurricup** [comment]
Do you see that $abc is marked by inspection? hover it. Than you may check `File->settings->Editor->Inspections->Perl`

**Comment by bakkiaraj** [comment]
Thanks. :) , I had made perl inspection to mark "Unresolved Variable" to Error. Now IDE Marks it as ERROR.
