### ISSUE TITLE
Spellchecker doesn't work with *.pm or *.pl

### ISSUE THREAD

**Issue by akashr** [Camelcade/Perl5-IDEA#1571]
IntelliJ IDEA 2017.2.1 Build #IU-172.3544.35, built on July 31, 2017
Perl5 plugin version: 2017.3 
JRE: 1.8.0_152-release-915-b6 x86_64
Mac OS X 10.12.5

**Comment by hurricup** [comment]
Feel free to build plugin and try. Spell checking should work now. (see main repo page for build instructions)
