### ISSUE TITLE
Cannot Add Perl Interpreter

### ISSUE THREAD

**Issue by SeattleRex** [Camelcade/Perl5-IDEA#1575]
MacOS 10.12.6
IntelliJ 2017.2.2 Build IU-172.3757.52
Perl 5.18
Plugin Version 2017.3
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

I am unable to configure an interpreter from within IntelliJ.  When I do the New Project -> Add JDK routine, I have a choice of several JDKs, but no Perl interpreter.  

I've installed/uninstalled/re-installed the plugin, restarted IJ each time of course, but to no avail.

I just switched from Eclipse (EPIC for Perl in that IDE) to IntelliJ this week, so I assumed it was low-familiarity, but I followed the directions very closely, and no dice.  Settings for a Perl Interpreter never appear.

Thank you.

P.S. Edit to add, my issue does not appear to be the same as:

https://github.com/Camelcade/Perl5-IDEA/issues/1404

I never see Perl at all in the JDK/Interpeter list, and am therefore never given a fileChooser to pick an interpreter.

**Comment by hurricup** [comment]
Just create a project with any (or without SDK). Than go to `File->Settings->Languages & Frameworks->Perl5`, not yet updated documentation for the new approach

**Comment by SeattleRex** [comment]
Thank you.  In the editor, I'm still getting the yellow bar that says "No SDK Configured", and when I go into the settings, I do get the option to set the IDE, however, selecting it does nothing.  I navigate to /usr/bin/perl or /usr/bin/perl5.18, and I change the version accordingly, but when I do ... it stays on Disable Perl5 support.

![perl_screenshot](https://user-images.githubusercontent.com/1728109/29755638-bb6a521e-8b4f-11e7-9d8f-7cf460d335bb.png)

**Comment by hurricup** [comment]
Click `new` and select directory with perl executable. It should be added to the combobox.

**Comment by thomaslindgaard** [comment]
I have the same issue. Clicking the `New` button and then selecting the Perl executable (`/usr/local/ActivePerl-5.24/bin/perl` in my case) and clicking OK does not add anything to the combobox. No matter what it stays on "Disable Perl5 support".

**Comment by akalitenya** [comment]
i had same issue 
5.18 perl 
OSX 10.12.6
IntelliJ 2017.2.2 Build IU-172.3757.52

"select directory" - not the file!

**Comment by hurricup** [comment]
@thomaslindgaard files should not be shown at all and you should choose a directory. This is a bug on MacOs #1404

**Comment by SeattleRex** [comment]
Works for me as well. Thank you very much!

**Comment by yulinzxc** [comment]
Yeah, saved my life! Thanks!!

**Comment by chenpeijiayou** [comment]
Thanks! saved my life too!

**Comment by dmorel** [comment]
Couldn't the interpreter finder check the directory when you select the interpreter, if a directory is what it needs? It's quite confusing.

**Comment by hurricup** [comment]
@dmorel current version should work fine both ways.

**Comment by dmorel** [comment]
On 2 Sep 2018, at 10:29, Alexandr Evstigneev wrote:

> @dmorel current version should work fine both ways.
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Camelcade/Perl5-IDEA/issues/1575#issuecomment-417913788


I have the latest version from the jetbrains repo, and it failed on all 
attempts until I selected the directory instead of the interpreter. Do 
you mean the current git head?

**Comment by hurricup** [comment]
@dmorel nope, I ment the one from repo. Please, provide your system description.

**Comment by dmorel** [comment]
@hurricup 
Mac OS 10.13.6
PyCharm 2018.2.2 (Professional Edition)
Build #PY-182.4129.34, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
Camelcade version 2018.2.1

**Comment by hurricup** [comment]
@dmorel thank you. will check asap
