### ISSUE TITLE
Throws exception when opening another intellij editor in new window when not a perl project

### ISSUE THREAD

**Issue by rogersprint** [Camelcade/Perl5-IDEA#1583]
I also created https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-756 but I didn't  have an account to add comments so I am adding them here. 

It happens every time.  Steps to reproduce: 

Open a perl project in Intellij 

Open another non perl project in intellij in a new window. 

New project will have the event Exception in Perl  asking to disable the plugin.

**Comment by hurricup** [comment]
This is a known conflict with Golang ide/plugin

**Comment by hurricup** [comment]
Fixed in https://github.com/Camelcade/Perl5-IDEA/commit/7a0e23d6886c4a9e454c7d7dea69e78aa414dddc and https://github.com/Camelcade/Perl5-IDEA/commit/72fd347a9a7f165ab862bdf6444533af2a0ce918

**Comment by hurricup** [comment]
Btw, you may try to build plugin yourself and check if problem is gone. See repository README
