### ISSUE TITLE
"View -> Context Info(ALT+Q)" and "Autoscroll from Source" do not work

### ISSUE THREAD

**Issue by johndunlap** [Camelcade/Perl5-IDEA#1585]
I'm trying to switch over from the Eclipse EPIC Perl plugin and one issue that I'm really struggling with is being inside a .PM file and not knowing what function my cursor is in unless I scroll up to the subroutine declaration. I like that "Autoscroll to Source" works and I use it a lot. However, not having "Autoscroll from Source" or, at least, the breadcrumbs provided by ALT+Q is very limiting. This is something that the Eclipse EPIC plugin does exceptionally well and it's why I've used it for years, despite my general dislike of Eclipse.

I'm using plugin version 2017.3, IntelliJ Ultimate 2017.2.5, Perl v5.20.2, JDK 9+181 64 bit, and Debian 8.7 64 bit.

**Comment by hurricup** [comment]
I've got your point about context, but autoscroll from source works: 
![image](https://user-images.githubusercontent.com/2811330/31372804-2cd353b6-ada0-11e7-8d25-0a3da851e050.png)

**Comment by johndunlap** [comment]
That's strange because that's exactly what I've tried. I've also gone into project config and added a source folder but that didn't help. Is there a way that I can debug this?

**Comment by hurricup** [comment]
You may download IDEA, download this repo and use Run Plugin run configuration
Could you describe more what you've tried and expected/got?

**Comment by johndunlap** [comment]
What I expect:
Open a .pl or .pm file, jump to a specific line number(usually obtained from a stack trace) using CTRL+G, click into a function, and watch the Structure view highlight the function that I clicked into.

What I have tried:
* Selecting/Unselecting all combinations of "Scroll to Source" and "Scroll from Source"
* View -> Context Info
* ALT+Q
* Adding source folders in "Project Structure -> Modules"
* Starting IDEA with both JDK 1.8 and 1.9
* IDEA version 2016.3, 2017.1, 2017.4, 2017.5

**Comment by johndunlap** [comment]
In all cases, when I click into a function, the Structure view never highlights the function that I clicked into.

**Comment by hurricup** [comment]
`click into a function, and watch the Structure view highlight the function that I clicked into` i don't understand what do you mean. May be screencast from eclipse?

**Comment by johndunlap** [comment]
Eclipse example:
https://www.youtube.com/watch?v=gDs_xmNkyvM

IntelliJ example:
https://www.youtube.com/watch?v=TiXIESm_pJ8

**Comment by hurricup** [comment]
Now I got it! :) Thanks !

**Comment by hurricup** [comment]
You may build a plugin from repo as described here https://github.com/Camelcade/Perl5-IDEA/blob/master/README.md
and try. Alt+Q and Alt-Up/Down should work fine now. And navigate from/to source
Thank you for the nice request!

**Comment by johndunlap** [comment]
It works! Thanks a lot!
