### ISSUE TITLE
Method autocomplete not working with type annotations

### ISSUE THREAD

**Issue by bakanov** [Camelcade/Perl5-IDEA#1598]
With syntax without type annotations everything works perfectly:
https://imgur.com/a/jlsym

But with type annotations it's not:
https://imgur.com/a/l4G9l

It's also not working, if annotation is used in the construction like that:
my ( 
    $var1, 
    $var2,
    #@type Foo::Bar
    $var3 
) = @_;

Idea Community 2017.2.5
plugin version: 2017.3.1
Active Perl 5.16.3
Windows 10

**Comment by hurricup** [comment]
Put it before my.
It can be:
```
#@type Foo::Bar
my $var;

my Foo::Bar $var; # perl syntax

my (
   #@type Foo::Bar
   $var ); # such format works for parenthethiszed (supposed to be multi-declarations) Probably should change this.
```

**Comment by bakanov** [comment]
I don't know. Still can't get the right result:
https://imgur.com/a/qFBHt

**Comment by hurricup** [comment]
Dam. Something magic is going on:

1. It seems not working
2. Your version should work too 
3. It's covered with tests and they seems ok :) 

Thanks. will investigate this today.

**Comment by bakanov** [comment]
I can try other idea or plugin versions, if you want

**Comment by hurricup** [comment]
You may try to build and test, see https://github.com/Camelcade/Perl5-IDEA/blob/master/README.md

**Comment by hurricup** [comment]
Question: has it worked like ever? 

Because the root of problem is in old long time not modified code. But could be other reasons. Tests covered resolve or already written code but not completion. And resolve worked but completion didn't.

**Comment by bakanov** [comment]
Now it works, thanks. 
Probably, it didn't work for a long time. I checked it about 3 weeks ago.
