### ISSUE TITLE
__PACKAGE__ is not recognized in "my" and "our" declarations

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#1599]
Hi,

Not sure if this is really a bug, but... sometimes there are declations like:

```perl
package Pack;

my __PACKAGE__ $var;
```

It is perfectly legal, but Perl plugin says "Unable to find namespace definition", while "my Pack $var" works as expected.

Idea Community 2017.2.5, Perl plugin 2017.3.2

**Comment by hurricup** [comment]
It's a bug and feature. Didn't know about such syntax and haven't implemented it, thank you!

**Comment by hurricup** [comment]
Feel free to build plugin and test (see repo readme)
