### ISSUE TITLE
Unable to configure Perl5 SDK in Intellij on Ubuntu for plugin version 2017.3.2

### ISSUE THREAD

**Issue by gerymate** [Camelcade/Perl5-IDEA#1603]
Unable to configure Perl5 SDK in Intellij on Ubuntu for plugin version 2017.3.2

Steps to produce the issue are:

1.    Click File, than Project Structure
2.    On the Project tab, the Project SDK dropdown shows <No SDK>
3.    Click the dropdown: Perl 5 is not listed
4.    Click the New button
5.    Perl 5 is nor listed there (JDK and Python SDK is shown)

IDE is IntelliJ IDEA 2017.2.5 #IC-172.4343.14
JRE is 1.8.0_152-release-915-b12 amd64 OpenJDK 64-bit Server VM by JetBrains
System is Ubuntu 16.04 LTS with all official updates

![no_perl_shown](https://user-images.githubusercontent.com/16536316/31604577-08719456-b264-11e7-80ae-6da8e991ea44.png)

**Comment by hurricup** [comment]
I'm sorry, still not updated wiki for new approach. Please, read this: https://groups.google.com/forum/#!topic/camelcade/6C-OUZ9ZtW4

**Comment by hurricup** [comment]
Updated wiki: https://github.com/Camelcade/Perl5-IDEA/wiki/Getting-started

**Comment by gerymate** [comment]
Thank you, now it's clear how to do it!
