### ISSUE TITLE
Inspection: unable to find sub definition....

### ISSUE THREAD

**Issue by reidrgb** [Camelcade/Perl5-IDEA#1621]
Thank you for the great plugin for Perl. But I am facing a issue.
In this simple script, a warning message is shown on cursor. Though the script works properly.
> Unable to find sub definition, declaration, constant definition or typeglob aliasing
> Unused sub definition

I don't know why the messages are shown. Please give me a help.
I checked in wiki, Perldoc, and copy & pasted some sample codes. But I couldn't solve the problem.

```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

hello();

sub hello{
    printf "hello\n";
}
```

![2017-11-15 18 47 11](https://user-images.githubusercontent.com/33683545/32829687-27372682-ca36-11e7-8aa8-d2bbdb1cbcd0.png)

> IntelliJ IDEA 2017.2.6
> Build #IU-172.4574.11, built on November 14, 2017
> Perl Plugin: Version: 173.3622.1
> JRE: 1.8.0_152-release-915-b12 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by hurricup** [comment]
Guess that problem here is that hello is above definition. Will check. Try to move it before usage

**Comment by reidrgb** [comment]
Thank you for a response. I moved the hello below definition, but the message remains.

![2017-11-15 20 01 27](https://user-images.githubusercontent.com/33683545/32832778-04f6175e-ca40-11e7-8146-d7ab985327ad.png)

**Comment by hurricup** [comment]
Oh, this file is not inside your project? Subs resolve may not work outisde the project.

**Comment by hurricup** [comment]
Yep, just tested, works as it is in initial message.
