### ISSUE TITLE
Modules are not being found and thus wrongly highlighted

### ISSUE THREAD

**Issue by cjelli** [Camelcade/Perl5-IDEA#1648]
Core modules
Data::Dumper
Storable
are being marked as 'not found':
![storable-data-dumper](https://user-images.githubusercontent.com/10471722/33517695-a2716b46-d73d-11e7-913a-52fcf01a2a87.png)

**Comment by hurricup** [comment]
Need additional information: OS, Perl. Also, please, show your external libraries in project tree:

![image](https://user-images.githubusercontent.com/2811330/33518674-fbc8768c-d7a9-11e7-84fd-dac8dca05a9d.png)

Looks like some inc path is missing.
Also, please, provide the output of:

`perl -E "say for @INC"`

**Comment by hurricup** [comment]
Also, I'd tried to remove and add back perl interperter in the settings window.

**Comment by cjelli** [comment]
For some reason, restarting whole of IDEA solved the problem.
