### ISSUE TITLE
Unable to find variable declaration of lexical named foreach VAR in anonymous sub

### ISSUE THREAD

**Issue by jimpudar** [Camelcade/Perl5-IDEA#1654]
```text
IntelliJ IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.127, built on November 27, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6
Camelcade plugin version 2017.4
```

After upgrading to IntelliJ 2017.3, I see an issue with lexically named VAR of `for` / `foreach` loops inside anonymous subs.

For example, in the following snippet `$var` is highlighted and the error message is "Unable to find variable declaration"
```perl
my $x = sub {
	my @arr = (1, 2, 3);

	for my $var (@arr) {
		print $var;
	}
};
```
<img width="335" alt="screen shot 2017-12-05 at 9 25 29 am" src="https://user-images.githubusercontent.com/12876828/33620990-4ef94598-d99e-11e7-92ed-faa7c87253b4.png">

Outside of anonymous subs, I do not see this issue:
```perl
sub x {
	my @arr = (1, 2, 3);

	for my $var (@arr) {
		print $var;
	}
};
```
<img width="220" alt="screen shot 2017-12-05 at 9 26 59 am" src="https://user-images.githubusercontent.com/12876828/33621055-78df4858-d99e-11e7-91d3-efcb03ce14dd.png">

This is high priority for me as it is a very basic feature, my codebase is filled with anonymous subs and all my files show hundreds of errors. Please let me know if I can be of any additional help.

**Comment by hurricup** [comment]
Dupe #1646

**Comment by jimpudar** [comment]
@hurricup - Thanks for the fast response!
