### ISSUE TITLE
Devel::Cover breaks perl 5.26.1

### ISSUE THREAD

**Issue by cjelli** [Camelcade/Perl5-IDEA#1665]
```
9:22 PM	Deparser Execution Error
			lstat() on filehandle isa at /usr/local/lib/perl5/5.26.1/File/Find.pm line 187.
			lstat() on unopened filehandle isa at /usr/local/lib/perl5/5.26.1/File/Find.pm line 187.
			Bizarre copy of CODE in scalar assignment at /usr/local/lib/perl5/5.26.1/File/Find.pm line 184.

```
Ready to provide any auxiliary data.
**This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi**

**Comment by hurricup** [comment]
Suppose this should be reported to perlporters. Some perl internal error

**Comment by cjelli** [comment]
But there wasn't any problem until the latest update. I installed Devel::Cover and this update (2017.4.1), and here came the problem.

**Comment by cjelli** [comment]
Ok, it's an issue that involves Devel::Cover, too:			

> $VAR1 = *Devel::Cover::Condition_or_3::isa;
> 			lstat() on filehandle isa at /usr/local/lib/perl5/5.26.1/File/Find.pm line 189.
> 			lstat() on unopened filehandle isa at /usr/local/lib/perl5/5.26.1/File/Find.pm line 189.
> 			Bizarre copy of CODE in anonymous array ([]) at /usr/local/lib/perl5/5.26.1/x86_64-linux-thread-multi/Data/Dumper.pm line 602.

**Comment by hurricup** [comment]
As far as IDE does not change perl itself, it is perl or some perl module. IDE has just few helper scripts. They can't cause such effect.

**Comment by cjelli** [comment]
Camelcade has some Devel::Cover involved features. As soon as I removed Devel::Cover, everything is back to normal.

**Comment by hurricup** [comment]
Guess you should report this fact to `Devel::Cover` repo.  https://github.com/pjcj/Devel--Cover
