### ISSUE TITLE
Plugin is ignoring custom HTML::Mason tags

### ISSUE THREAD

**Issue by miparnisari** [Camelcade/Perl5-IDEA#1668]
* IDE name and version: IntelliJ IDEA 2017.3 (Community Edition). Build #IC-173.3727.127, built on November 27, 2017
  * Perl5 plugin version: 2017.4
  * JRE version: JRE: 1.8.0_152-release-1024-b6 x86_64
  * Your OS name and version: Mac OS X 10.12.6

I added custom tags for HTML::Mason but i don't see them rendered differently.

![mason bug](https://user-images.githubusercontent.com/5374887/34012422-87a01d28-e0c8-11e7-903b-c934386301f6.png)

Also, `once` is a valid Mason tag but it's not rendered as such.

**Comment by hurricup** [comment]
by default, `*.mi` files assiciated with `Mason2` framework. `HTML::Mason` using `*.mas`.
Seems you should change associations 

![image](https://user-images.githubusercontent.com/2811330/34025689-53b48f7c-e162-11e7-9bc1-db82ccad4708.png)

Guess we need different icons. Suggestions are welcome.

**Comment by miparnisari** [comment]
That works! Thank you!
