### ISSUE TITLE
Resolving Moose `has` attributes (revisit)

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1669]
In https://github.com/Camelcade/Perl5-IDEA/issues/1410 Moose's `has` attributes were fixed to resolve correctly. The fix works great in cases where the method is declared using perl's usual `sub` notation:

```perl
has bar => (
	is        => 'ro',
	predicate => 1,
);

#@method
sub foobar {
    my $self = shift;
    return $self->bar;
}
```

However it still doesn't work using Moose's `method` notation:

```perl
has bar => (
	is        => 'ro',
	predicate => 1,
);

method foobar {
    return $self->bar;  # the 'bar' here is highlighted with "Unable to find sub definition ..."
}
```

Given that `has` is a Moose feature, I believe this is a bug as `method` is also a Moose feature.

**Comment by hurricup** [comment]
Feel free to build from git and check. See README
