### ISSUE TITLE
Wiki suggestion for annotations

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1670]
Heya, quick suggestion for the Wiki (seeing as Github don't let me send pull requests for it!)

I might not be obvious to people (as it wasn't to me) but you can use the `#@returns` annotation to label Moose properties:

```perl
#@returns Some::Class
has some_class => (
	is => 'lazy',
);
```

**Comment by hurricup** [comment]
Thanks. Added clarification to the https://github.com/Camelcade/Perl5-IDEA/wiki/Annotations#returns
FYI: isa parameter should work too.
