### ISSUE TITLE
How to toggle breakpoints?

### ISSUE THREAD

**Issue by simPod** [Camelcade/Perl5-IDEA#1671]
In IDE, it's impossible to toggle brakpoints. How to do that? It only breaks on the first line. Thanks

![image](https://user-images.githubusercontent.com/327717/34043114-e5d4e374-e19f-11e7-90d8-11d6684ab410.png)

IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1
Plugin version: 2017.4.1

**Comment by hurricup** [comment]
Your file is parsed wrong. Should not contain syntax errors. Looks like file association is wrong. What is the file extension?

**Comment by simPod** [comment]
it is `test.pl`

```#!/usr/bin/perl
use strict;
use warnings;

print "hi NAME\n";
```

**Comment by simPod** [comment]
Ah, thanks. I had registered .pl extension to Prolog type :/
Thanks a lot
