### ISSUE TITLE
Extend #@type annotation to include optional variable name

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1675]
(Yeah, I'm gonna owe you a beer or two from all these issues I'm opening!)

I'd like to be able to optionally include the variable name in an `#@type` annotation rather than it attempting to determine it from the following line.

In PHPStorm, you type-hint a variable using a comment like this:
```php
/* @var ClassName $object */
```

In this plugin, there is no option to include the variable. Which means things like this don't work:
```perl
#@type ClassName
foreach my $object ( @array_of_class ){
   ...
}
```

If we could include the variable name, then all these would work:
```perl
#@type ClassName $object
foreach my $object ( @array_of_class ){
   ...
}

# maybe this could unfold to realise that `$object` was a `ClassName`?
#@type ClassName @array_of_class
foreach my $object ( @array_of_class ){
   ...
}

# Even lists of variables could be pre-declared rather than having to split up the list 
sub do_something {
    #@type Some::Class $some_obj
    #@type Another::Class @list_of_another_obj
    my( $some_obj, @list_of_another_obj ) = @_;

}
```

**Comment by RickMeasham** [comment]
(I'm just chucking these up in case you want something to do .. they're not bugs clearly)

**Comment by hurricup** [comment]
Yep, thnking about this. For now you may only use unpacking with `shift` or something ugly like:
```
my (
  #@type Foo
 $var1, 
  #@type Bar
  $var2
) = @_;
```
Types for array contents are not yet supported.

**Comment by RickMeasham** [comment]
I assume this possible with the JetBrains API and just needs implementing. But it makes me ask: How much access do you get to annotations? Just thinking about other PHPStorm stuff that's supported like `@param` to describe subroutine parameters. The docs you provide there are then shown in the hinting when you use that method. Ignoring the work to do it, does the API give you the ability to implement that sort of thing in third party code integrations like Camelcade.

I'm sick of Perl's instance on using POD, a formatting language, for documenting code and might look at doing something better

**Comment by hurricup** [comment]
This is not some kind of common API. May be just look similar in some languages, but different implementations.

**Comment by vlad-ghita** [comment]
This would be great.

+1

**Comment by targzeta** [comment]
+1

**Comment by elcamlost** [comment]
> I'm sick of Perl's instance on using POD, a formatting language, for documenting code and might look at doing something better

In the mean time, reading type annotations from pod section can be useful to parse type annotations from pod. These way you do not pollute your source code with unnecessary comments, that can reduce readability.

**Comment by hurricup** [comment]
@elcamlost is there some conventional way to write such things in pod?

**Comment by elcamlost** [comment]
> @elcamlost is there some conventional way to write such things in pod?

I'll make a research on cpan how different modules solves the problem.

**Comment by elcamlost** [comment]
> I'll make a research on cpan how different modules solves the problem.
I didn't found any common syntax on cpan. Usually it's just a comment in the body of sub documentation.
For example, Mojolicious does it this way.
```pod
=head2 types
 
  my $types = $app->types;
  $app      = $app->types(Mojolicious::Types->new);
 
Responsible for connecting file extensions with MIME types, defaults to a
L<Mojolicious::Types> object.
```
I don't think it could be any useful for our case.

Another way I found is [Data::Object](https://metacpan.org/pod/Data::Object) (and other projects of @alnewkirk).
```pod
=head2 args
 
  Args(HashRef $data) : InstanceOf["Data::Object::Args"]
 
The Args function returns a L<Data::Object::Args> object.
```

It's much better and should be considered. 

And, finally, last suggestion. Dave Mitchel (the creator of perl signatures code) suggests [this syntax](https://www.nntp.perl.org/group/perl.perl5.porters/2019/11/msg256683.html) for the core to support type checks with signatures. It's probably will be part of the core, so experimental support for parsing such syntax from pod can be very useful. 
```pod
=head2 Synopsis:
    sub f(
            $self isa Foo::Bar,         # croak unless $self->isa('Foo::Bar');
            $foo  isa Foo::Bar?,        # croak unless undef or of that class
            $a!,                        # croak unless $a is defined
            $b    is  Int,              # croak if $b not int-like
            $c    is  Int?,             # croak unless undefined or int-like
            $d    is PositiveInt,       # user-defined type
            $e    is Int where $_ >= 1, # multiple constraints
            $f    is \@,                # croak unless  array ref
            $aref as ref ? $_ : [ $_ ]  # coercions: maybe modify the param
    ) { ...};
```

**Comment by hurricup** [comment]
@elcamlost thank you for investigating this. Would be nice to have some core perl syntax for this at some point. 
Still. The question was if there is existing commonly-used way to handle this atm. Seems there is not. 
Anyway - it is a food for thought. Thanks again!

**Comment by iamalnewkirk** [comment]
@elcamlost @hurricup Fwiw, the POD in my distributions is driven by a specification I came up with which is documented here https://metacpan.org/pod/Test::Auto#SPECIFICATION. For example, the POD that you pasted comes from this, https://metacpan.org/pod/Data::Object#args, which is automatically generated from this, https://metacpan.org/source/AWNCORP/Data-Object-2.05/t/Data_Object.t#L75-101.

This documentation (using the specification) is done in the test matching the module so that the test is the source of truth for how the module works. The style of documentation is based on Golang package documentation. I'm not sure how many others use the Test::Auto specification and automation. Hope this helps!

**Comment by hurricup** [comment]
Still feels like we need a different syntax (see `@param` tag in YARD):
```
#@type [varname_with_sigil] type_description

#@type $something Foo::Bar
#@type Foo::Bar
```

Later, when array and hash values annotaions going to be supported, we may extend this like:

```
#@type %hash Foo::Bar - means all elements are Foo::Bar
#@type $hash{key} Foo::Bar - means particular element is Foo::Bar
#@type @array Foo::Bar - means all array elements are Foo::Bar
#@type $array[1] Foo::Bar - means that element at index 1 is Foo::Bar
```
I think that for now we should keep the scope to the next line of the code (or statement beginning on the next line). Not sure if we should use annotations with block scopes.

**Comment by hurricup** [comment]
![image](https://user-images.githubusercontent.com/2811330/201836564-5bb0b606-adc8-467a-897f-4daf6d4cee3e.png)

**Comment by hurricup** [comment]
- [ ] support multiple type annotations processing
- [ ] support filtering by variable name and type
- [ ] resolve from variable in annotation to the real one (test unresolved inspection and refactoring)
- [ ] completion of variables
- [ ] Test for statements and subs

**Comment by hurricup** [comment]
- There are explicit annotations (with variable name) and wildcard annotations (without variable name).
- Wildcard annotation going to be used to every variable in context (next line after annotations block)
- First matching annotation wins.
- Explicit annotation may override the wildcard, not vice versa.

Multiple declarations may be annotated in the nice way:
```
#@type $var2 Boo::Baz
#@type Foo::Fallback
#@type $var1 Foo::Bar
my($var1, $var2, $var3);
```

Signature elements `sub` may now be annotated before sub:
```
#@type $var1 Foo::Bar
#@type $var2 Bla::Bla
#@returns Foo::Bazz
sub something($var1,
              $var2){
   return $var1->convert($var2);
}
```

Variable in the `for` loop may now be annotated outside of it:
```
#@type Class::Apple
for my $var (@something){
   ... eating an apple...
}
```

**Comment by hurricup** [comment]
![image](https://user-images.githubusercontent.com/2811330/201924253-655e1a46-ae7c-4103-a066-151d9d6ae4f8.png)
