### ISSUE TITLE
Indentation on 'has'

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1702]
I'd like a way to auto-format Moose's `has` blocks so the closing brace lines up with the `has` keyword.

![image](https://user-images.githubusercontent.com/79414/34471659-f4c10596-efa2-11e7-82ea-1a6057376f45.png)

Currently, the closing brace (and content) is indented from the start of the line. I'd like to be able to pull it back one tab-stop (see 'desired' in the screen shot)

**Comment by hurricup** [comment]
This should already work in master, try to build and check.
