### ISSUE TITLE
Игнорировать все файлы, указанные в .gitignore

### ISSUE THREAD

**Issue by ivanych** [Camelcade/Perl5-IDEA#1707]
Если в проекте есть файл .gitignore, то можно игнорировать все указанные в нем файлы. Можно сделать это опцией в настройках.

Зачем это нужно? Если файл указан в .gitignore, то почти гарантированно он не нужен в процессе использования редактора. Ненужные файлы приходится помечать как exclude, но это ручная работа, вместо этого можно просто использовать .gitignore.

Где это может быть полезно? Например, при поиске - не нужно искать в игнорируемых файлах и зашумлять результаты поиска ненужными вхождениями. Или при инспекции кода - если не проигнорировать каталог blib, инспекция ломается из-за того, что находятся "другие" файлы с теми же объявлениями неймспейсов и функций. Причем, если один конкретный каталог blib еще можно исключить вручную для починки инспеции, то исключать вручную все игнорируемые файлы при поиске - это нереально.

**Comment by hurricup** [comment]
папочку блиб нужно просто заэксклудить.

**Comment by ivanych** [comment]
> Причем, если один конкретный каталог blib еще можно исключить вручную для починки инспеции, то исключать вручную все игнорируемые файлы при поиске - это нереально.

**Comment by hurricup** [comment]
В личной практике подобные файлы лежат в одном месте. А не просто в корне. Либо поиск в них практически не аффектит работу.
Суть в том, что подобный функционал скорее платформенный (IDE). И подобный реквест лучше писать в трекер JetBrains. В раздел VCS как я думаю.
