### ISSUE TITLE
Сообщение о переопределении названия пакета или функции сделать информативнее

### ISSUE THREAD

**Issue by ivanych** [Camelcade/Perl5-IDEA#1709]
Если инспеция обнаруживает в файле переопределение названия пакета или функции, то выводится сообщение типа "Namespace definition clashes...". По этому сообщению можно понять, что есть конфликт с каким-то другим файлом, но нельзя понять с каким.

Хорошо бы в этом сообщении сразу писать, с каким именно файлом конфликт.

**Comment by hurricup** [comment]
Duplicates #1704
