### ISSUE TITLE
Missing "New" Perl 5 Interpreter button in Project Settings 

### ISSUE THREAD

**Issue by alexqfredrickson** [Camelcade/Perl5-IDEA#1714]
## Summary

The <kbd>New</kbd> button isn't showing up for me under Project Settings, so I effectively can't select the Perl executable on my machine to use as the interpreter.  All I see is a "disable" option in the dropdown.

Not sure if it matters, but this plugin was sitting on another drive when I installed it.  Beyond that, I'm out of luck and out of ideas.

Thanks!

## Technical details

IntelliJ IDEA 2017.2.2 (Build #IU-172.3757.52)
Perl 5.20.2
Perl IntelliJ plugin 2017.3.2
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by hurricup** [comment]
Here is one good idea: https://github.com/Camelcade/Perl5-IDEA/wiki/Getting-started :)

**Comment by alexqfredrickson** [comment]
Can you elaborate on what you mean by "Here is one good idea"?  I read through this documentation prior to asking the question.

![projectsettings](https://user-images.githubusercontent.com/7747782/35081318-9094d002-fbe1-11e7-8c07-f8b2b9cf87a2.png)

The red circle with the white `4` inside of it is what I am referring to by the <kbd>New</kdb> button.  It isn't there.

**Comment by hurricup** [comment]
Oh, sorry than, in most such cases peple do not read anything  ;) 
could you please provide a screenshot?

**Comment by alexqfredrickson** [comment]
No problem, here is a screenshot:

![ss](https://i.imgur.com/h68sZge.png)

The only option in "Perl5 Interpreter" is the "Disable Perl Support" option.  (Ignore the External Libraries thing - I was just experimenting).

**Comment by hurricup** [comment]
I'll try to reproduce this. Could you please try to resize Settings window and make it wider?
Thanks.

**Comment by hurricup** [comment]
Well, it solved your problem, but it should not work this way.
