### ISSUE TITLE
New inspector: Truthiness

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1715]
It's often tempting to write code like:

```perl
if( $variable ){ ... }
```

... without thinking about how many things are falsey in perl. Particularly `"0"`. 

It would be nice to have an inspection where that flags conditionals that depend on truthiness rather than being more explicit. (That is, they don't have a comparison operator)

**Comment by hurricup** [comment]
I'll make an MVP with explicit variables and casts. But there is a still problem with invocation.
```
if(some_sub()){

}
```
May be valid or not and it's not possible to analyze atm. Probably later as a separate task.
