### ISSUE TITLE
Associate `cpanfile` with Perl 

### ISSUE THREAD

**Issue by Nowaker** [Camelcade/Perl5-IDEA#1716]
cpanfile, although it has special meaning, is - first of all - Perl code. Perl syntax highlighting should apply there by default.

- IDE name and version, including build, (e.g. `#IU-143.2370`, available in `Help: About` menu)
  - RubyMine 2017.3.1, Build #RM-173.3942.35
- Perl5 plugin version (available in `File: Settings: Plugins` menu)
  - 2017.4.1

**Comment by hurricup** [comment]
Yep, cool idea. Thanks

**Comment by hurricup** [comment]
Fixed in https://github.com/Camelcade/Perl5-IDEA/commit/a8e64c807c0da9fbf3843651fd3dceb8906fb591

**Comment by hurricup** [comment]
Feel free to build plugin from branch 173 or master (if you are using 2018 EAP).
See readme for more information
