### ISSUE TITLE
Alignment of catch blocks

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1717]
When formatting the following code, I cannot convince the IDE to align the `catch` block with the `try` block. It should follow the same rules as the `if` and `else` blocks. 

```perl
try {
	x();
}
catch {
	die( $_ );
}
```

Here's the formatting I'm getting:
![image](https://user-images.githubusercontent.com/79414/35256848-086ac886-004a-11e8-8016-ebc8ef917705.png)

**Comment by hurricup** [comment]
Have you tried  current dev version? Try to build from 173 branch.

**Comment by RickMeasham** [comment]
Fantastic! Works great. Closing.
