### ISSUE TITLE
Syntax Highlighting work not on *.pl Files

### ISSUE THREAD

**Issue by gmuc** [Camelcade/Perl5-IDEA#1721]
Intellij 2017.3.3
OSX 10.12.6
perl5-IDEA 2017.4.1

Syntax highlighting work only for *.pm files not for *.pl?

How can I change this?
![perl-syn1](https://user-images.githubusercontent.com/15010627/35343848-edcf78b8-012b-11e8-98ad-17e10e92b258.png)

![perl-syn2](https://user-images.githubusercontent.com/15010627/35343869-f9f1718c-012b-11e8-91a5-aa97fe8f91de.png)

**Comment by hurricup** [comment]
Suppose the same as https://github.com/Camelcade/Perl5-IDEA/issues/1671

**Comment by gmuc** [comment]
Solution: 
https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html#create
Go to Perl scripts and add *.pl

**Comment by hurricup** [comment]
You can also uninstall/disable prolog's plugin. Should help too.
