### ISSUE TITLE
Navigate > Declaration not working properly

### ISSUE THREAD

**Issue by mikewenzel** [Camelcade/Perl5-IDEA#1722]
After installing camelcade:
* I created a new project opening a folder containing my perl code
* then configured the perl interpreter for my project (Preferences > Languages & Frameworks > Perl5)  which seems to work fine 
  * when I use Navigate > Declaration [CMD + B on MAC] on e.g. `use Data::Dumper;` I jump into the correct file and declaration
* then I marked a folder in my project as **_Perl5 libraries_** which seems to work fine too
  * when I use Navigate > Declaration [CMD + B on MAC] on a sub which is written by me, I jump into the correct file and declaration
* now I added a new module containing Perl-Modules. I marked them as Perl5 libraries. For `use SomeModule;` lines it works, but not for subroutines.  Here I get `Unable to find sub definition, declaration, constant definition or typeglob aliasing`

Now what I'm wondering about is: when I use **_Find in Path_** on the Project and I'm searching for `sub subnameIWantedToJumpTo` he find's all occurences.

Are there any specific rules how subroutines have to be defined in order to find them?
I can't get this working properly.

**Environment:**
* macOS High Sierre (10.13.2)
* IntelliJ IDEA 2017.3.3 (Community Edition)
Build #IC-173.4301.25, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Plugin: Perl 2017.4.1

<img width="1531" alt="20180131125658" src="https://user-images.githubusercontent.com/35995896/35622220-55a114e6-0687-11e8-92b7-bab7d006b24e.png">

**Comment by hurricup** [comment]
Please, check https://github.com/Camelcade/Perl5-IDEA/wiki/Subs-resolution-status
To be able to resolve this, plugin should know what is type of `$metainfo`. Plugin resolves only if it 100% sure that it's right, so there is no text-based resolves just by names.
In your case you should annotate argument, or explicitly specify the name with per-variable unpacking.
