### ISSUE TITLE
Improve perl native signatures support

### ISSUE THREAD

**Issue by elcamlost** [Camelcade/Perl5-IDEA#1723]
Perl5 signatures can be used with anonymous subroutine

```perl5

my $sub = sub ($p1, $p2) {
    ...
}

$sub->(1,2);
```
 
Also, we can skip parameter assigning with special syntax
```perl5
sub examples ($p1, $, $p3) {
     ...
}

example (1, 2, 3);
```

Both of these cases are unsupported by plugin ((
It doesn't recognize variables defined for anonymous subs http://prntscr.com/icgmts
![image](https://user-images.githubusercontent.com/2811330/36167426-e6c570be-1106-11e8-9145-ab04c4d06751.png)

or even worse, reports syntax errors http://prntscr.com/icgn69
![image](https://user-images.githubusercontent.com/2811330/36167436-ed243d28-1106-11e8-809a-a5863d93f307.png)

#### IDE name and version, etc
  ```PhpStorm 2017.3.4
  Build #PS-173.4548.32, built on January 30, 2018
  Perl5 plugin: 2017.4.1
  JRE: 1.8.0_152-release-1024-b11 x86_64
  JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  Mac OS X 10.13.3
  ```

**Comment by hurricup** [comment]
This was the nice one. Thank you. Feel free to build from 173 branch (or master if you are on the EAP builds)
