### ISSUE TITLE
Feature Request: Docker Container Remote Interpreter Support

### ISSUE THREAD

**Issue by drmmr763** [Camelcade/Perl5-IDEA#1740]
JetBrains has great php remote interpreter support for Docker (https://blog.jetbrains.com/phpstorm/2016/11/docker-remote-interpreters/)

The value of this is that all your PHP Dependencies can be stored in your `Dockerfile`, and PHPStorm can use the same Dockerfile which has your php libraries installed. This avoids having all those dependencies on your host machine, containing them nicely within the Docker container. 

It would be great to have the same support with Perl5-IDEA. Basically in the interpreter selection one could select the associated remote interpreter, which could be a Docker container. All perl module dependencies would then be resolved as external libraries.

**Comment by drmmr763** [comment]
Awesome @hurricup ! I can't wait to try this out!

**Comment by hurricup** [comment]
@drmmr763 feel free to build from master and try :) see instructions in the readme

**Comment by drmmr763** [comment]
The build worked okay but PHPStorm doesn't like me trying to install:

![image](https://user-images.githubusercontent.com/643104/48351220-9a4bc400-e657-11e8-938d-c8eaf2f0bbe9.png)

Wonder if I have to uninstall the formal plugin?

**Comment by hurricup** [comment]
You need a EAP of PhpStorm. 2018.3
