### ISSUE TITLE
Can't add a new Perl interpreter while IDEA is indexing

### ISSUE THREAD

**Issue by brnrc** [Camelcade/Perl5-IDEA#1741]
* IDE name and version: Intellij Community 2017.3.4
  * Perl5 plugin version: 2017.5
  * Your OS name and version: macOS High Sierra 10.13.3

![image](https://user-images.githubusercontent.com/440797/36676614-6b4a5566-1b0c-11e8-8d82-d372f9ed4461.png)

I found myself saying a few wtfs when I couldn't add a new Perl interpreter in the configuration screen. My suspicion is that the plugin blocks the selection while IDEA is indexing the project. After the indexing was done, the gear icon was clickable again.

Can we improve this? Maybe a message next to the gear icon?

**Comment by hurricup** [comment]
Shouldn't be this way. thanks.
