### ISSUE TITLE
Perl tidy to format selection

### ISSUE THREAD

**Issue by vdtn359** [Camelcade/Perl5-IDEA#1744]
Right now, if I select a section of code and then right click > Reformat with Perl::Tidy, it always reformat the whole file, which is really not what I want since I am using version control. Is there a way to only reformat a selection?

**Comment by ElMoselYEE** [comment]
"Show Reformat File Dialog" can be performed using Option + Shift + Cmd + L. This dialog has the option of only formatting a selection, only VCS changed text, or the entire file.

**Comment by hurricup** [comment]
@ElMoselYEE this works with plugin formatter, not perltidy
@vdtn359 does `Perl::Tidy` can re-format part of file? Also, what exact options you are using in `Perl::Tidy` which are missing in plugin's formatter?

**Comment by ElMoselYEE** [comment]
Perl Tidy cannot format a partial file, but in theory you could create a temporary file with the current selection, format that, then inject the result.

**Comment by hurricup** [comment]
It's easier (and in my opinion - better) to improve built in parser

**Comment by vdtn359** [comment]
@hurricup: I use this plugin for atom https://github.com/kraih/atom-perltidy. It can reformat partial file

**Comment by hurricup** [comment]
@vdtn359 ofc it's possible. But as I've mentioned above - not the best way in my opinion. I'd prefer not to use external toos if possible.

**Comment by hurricup** [comment]
If you need some `Perl::Tidy` options in the native formatter - feel free to submit a request. This won't be done.
