### ISSUE TITLE
Make perl5 code insight settings available in find action

### ISSUE THREAD

**Issue by RickMeasham** [Camelcade/Perl5-IDEA#1746]
I type. I don't look at the screen. So now I have colons EVERYWHERE because after 20 years of typing perl, I type "::". There's very little benefit to the feature as it's just saving double-tapping the same key.

**Comment by RickMeasham** [comment]
Nevermind. Found it. The search function in settings didn't find it. 

![image](https://user-images.githubusercontent.com/79414/36873816-c356f25c-1dfd-11e8-85ff-695dc5ebe59e.png)

**Comment by hurricup** [comment]
![image](https://user-images.githubusercontent.com/2811330/36884027-3ffb33ae-1def-11e8-89ff-81def882ff5c.png)
Searching in Settings works wierd though.

**Comment by hurricup** [comment]
Should work now, thank you.
