### ISSUE TITLE
Импорт функции из списка @EXPORT_OK

### ISSUE THREAD

**Issue by ivanych** [Camelcade/Perl5-IDEA#1749]
Похоже, плагин не учитывает импорт функций, указанных в массиве `@EXPORT_OK`. Это те функции, которые не импортируются по умолчанию, их нужно указывать явно.

Пример:

```
#!/usr/bin/perl

use Encode qw(encode_utf8 utf8_upgrade);

encode_utf8();
utf8_upgrade(); # упс...
```
![_059](https://user-images.githubusercontent.com/466311/37248207-956a525e-24dc-11e8-8a10-1fd0380dd745.png)

Функция encode_utf8 находится в `@EXPORT` и плагин видит, что она импортируется, всё нормально.

А вот utf8_upgrade находится в `@EXPORT_OK` и плагин её не видит, она подсвечена желтым.

**Comment by hurricup** [comment]
EXPORT_OK должен работает норм. Где определена или объявлена функция?

**Comment by ivanych** [comment]
Хм. Видимо, я неправильно диагностировал причину. Тогда, _похоже_, проблема не просто в @EXPORT_OK, а совместно с тегами:

**Ttt.pm**

```
package Ttt;

use Exporter qw(import);

our @EXPORT_OK = qw(
    foo
);

our %EXPORT_TAGS = (
    all => [
        'foo'
    ]
);

sub foo {
    return 1111;
}

1;
```

**ttt.pl**

```
#!/usr/bin/perl

use lib 'lib';

use Ttt qw(:all);

print foo();
```

foo не распознается.

**Comment by hurricup** [comment]
Никакого совместно. Это две разные проблемы. Теги сейчас не поддерживаются и на это есть таска. В случае utf - неясно где декларация.

**Comment by ivanych** [comment]
А, оке.

https://github.com/Camelcade/Perl5-IDEA/issues/386
