### ISSUE TITLE
Support Data Type Renderers

### ISSUE THREAD

**Issue by cdalvaro** [Camelcade/Perl5-IDEA#1750]
Please, add support for showing complex structures with pretty printers.

e.g. DateTime objects

DateTime objects are difficult to see at first-sight by default

<img width="660" alt="datetimevariabledebugger" src="https://user-images.githubusercontent.com/16347742/37477839-f9126374-2878-11e8-8c58-fe98a70011d4.png">

It would be very useful if the debugger view showed something like this

<img width="660" alt="datetimevariabledebugger-pretty" src="https://user-images.githubusercontent.com/16347742/37478126-b5b0e8de-2879-11e8-8a76-eaaedb10cbaa.png">

**Comment by hurricup** [comment]
Well, in Java, for example, every object has `toString` method, which is doing exactly the thing. But perl doesn't have such mandatory method or convention.

Is there any unified method to do this? May be some module that can represent popular modules in the cool way?

I don't really want to hardcode this for every possible object.

**Comment by cdalvaro2** [comment]
Well, I know the module [Data::Printer](https://metacpan.org/pod/Data::Printer), that might can be useful for this purpose, like it is shown in [this article](https://www.effectiveperlprogramming.com/2011/11/use-dataprinter-to-debug-data-structures/)

**Comment by hurricup** [comment]
As far as i know this is just a pretty (and may be more flexible/configurable) Data::Dumper. Not exactly what are you talking about.

The only way I can see here is to hardcode some cases and make a convention, like "if class has a `to_string` method it's going to be used"

**Comment by pablrod** [comment]
Although there is no `toString` in Perl, many objects [overload](http://perldoc.perl.org/overload.html#Declaration) the `""` operator (aka _stringification_). That is called when a reference to a object is evaluated in string context. 

Maybe this can be used as a kind of preview. With [DateTime](https://metacpan.org/pod/DateTime) objects this works perfectly. Indeed this is what [Eclipse Perl Plugin](http://www.epic-ide.org/) does.

![image](https://user-images.githubusercontent.com/490880/37566183-c8e8b10a-2ab5-11e8-9968-dff19f90054c.png)

**Comment by juanradiego** [comment]
Are there plans to include this feature? I would find this very useful.

**Comment by hurricup** [comment]
@juanradiego there is still no concept for this. How do you see this? I don't like the idea to hardcode serializing for different classes.

**Comment by hurricup** [comment]
This won't work everywhere. After some investigation, seems we need something like this: https://www.jetbrains.com/help/idea/debugger-data-type-renderers.html

**Comment by cdalvaro** [comment]
Thanks @hurricup for developing this great plugin!

**Comment by hurricup** [comment]
Ok, I've got something like this (for the Foo::Baz, there is a configured renderer):

![image](https://user-images.githubusercontent.com/2811330/52861460-90989780-3143-11e9-91bf-11db6a5cd2d7.png)

![image](https://user-images.githubusercontent.com/2811330/52861388-5f1fcc00-3143-11e9-9f65-421146c19b4e.png)
