### ISSUE TITLE
Facet support

### ISSUE THREAD

**Issue by rshingleton** [Camelcade/Perl5-IDEA#1755]
I have a few projects that are not entirely Perl project, yet require some support from this plugin. I was able to get it to work for the most part by manually editing the project.iml, but it would be nice to be able to designate a Perl facet similar to the python facet in the project settings.

In the Perl facet you should be able to set at least:
- Project interpreter
- perl-library settings

**Comment by hurricup** [comment]
You don't need facet. Perl may be configured as a second language for any project. Without facets. 
https://github.com/Camelcade/Perl5-IDEA/wiki/Getting-started
