### ISSUE TITLE
Remote Debugging Remote Project root does not save with just `/` 

### ISSUE THREAD

**Issue by slobo** [Camelcade/Perl5-IDEA#1773]
When debugging remote project (in this case it is app running in container), remote path is `/perl/some-script.pl` and also our project path is `/perl/some-scrpit.pl`. So I think I need to set "Remote project root" to `/` to have it properly map the file to the project file. But there seems to be overly agressive removal of trailing `/` when saving:

https://github.com/Camelcade/Perl5-IDEA/blob/aff5c310ee2cdda74baccbce6aa38b890cb6d2d9/src/com/perl5/lang/perl/idea/run/remote/PerlRemoteDebuggingConfiguration.java#L109-L114

And project root is set to blank after save (need to re-open settings to see it cleared out). Or is there another way to set project root so that source mapping works? Thanks

**Comment by hurricup** [comment]
ye, this is probably a problem. Unexpected case :)

**Comment by hurricup** [comment]
Feel free to build from master and check. Should work fine
