### ISSUE TITLE
subroutine in script - Unable to find sub definition

### ISSUE THREAD

**Issue by mattjb1222** [Camelcade/Perl5-IDEA#1784]
IntelliJ IDEA 2018.1.5 (Community Edition)
Build #IC-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Perl Plugin Version: 2018.1.2

Java SE Runtime Environment (build 1.8.0_151-b12)

This is similar to Issue #1621, but I'm seeing the behavior with a file that was created and saved within the project. Subroutine is defined before the call as seen here:
![testing](https://user-images.githubusercontent.com/20169719/42530255-535bbd98-8446-11e8-8d46-6612770692dc.jpg)

```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

sub testing {
    printf "hi\n";
}

testing();

```

Running the script works just fine, but the IDE is showing it as a warning.

**Comment by hurricup** [comment]
Could you please show me your project structure? Seems like you don't have any modules and this file is basically outside of the project scope, inspite it's in project root. Here is how it should look like:

![image](https://user-images.githubusercontent.com/2811330/42531009-75e551a4-848b-11e8-8e77-06578040f42a.png)

Have you checked our getting started wiki?

**Comment by mattjb1222** [comment]
Ah, that explains it! I selected New Project -> "Empty Project" configured with the Perl interpreter instead of the New Project -> "Perl5 module" configured the same way. I was thinking the "Perl5 module" was only for .pm files, but I now see the tooltip over it is "Anything written in Perl5." Looks like syntax for subroutine calls is registering fine now. Thanks for the quick response and sorry for the newbie mistake. :)

**Comment by hurricup** [comment]
Not a problem. It's not necessary to be a perl module. But project must have one.
