### ISSUE TITLE
Coverage do not work (with perl version manager)

### ISSUE THREAD

**Issue by floreal** [Camelcade/Perl5-IDEA#1787]
Hello,
I've been trying to use code coverage on some of my perl project, but I get no coverage result.
Here are the log when running my
```
/home/floreal/.plenv/versions/5.18.2/bin/perl -I/home/floreal/work/my-project/t/lib -I/home/floreal/work/RnD/my-project/lib /home/floreal/work/RnD/my-project/t/testsuite.t
 - PERL5OPT=-MDevel::Cover=-silent,1,-db,/home/floreal/.IdeaIC2018.2/system/coverage/my-project$testsuite_t.json,-dir,.
# test run

Process finished with exit code 0
```

Here is what displayed in the event log:
```
13:45	Perl5 Library Devel::Cover is Missing: Library is require to perform an action. Please, install it first
```

I use plenv and Carton so I modified script environment variables such as PERL5LIB and PATH to add appropriate pathes, and Devel::Cover is present in those.

I'm using IntellJ Idea CE 2018.2 Build IC-182-3684.101 with JVM 1.8.0_152 for amd64 architechture (OpenJDK)

Where can I find more log that could help solving this issue ?

**Comment by hurricup** [comment]
The problem is a `.plenv` i believe. There is no proper support for version managers yet. The only way I can see here is to close IDEA, open terminal, switch to 5.18.2 and start IDEA from terminal, so IDE has the proper environment.

**Comment by floreal** [comment]
Hello, thanks for you answer. I tried it, and it din't work, I also tried installing a system-wide Devel::Cover library but nothing more happened.

**Comment by hurricup** [comment]
Just in case, are  you sure that you have a `Devel::Cover` installed for 5.18.2?

**Comment by hurricup** [comment]
And you still getting 
`13:45	Perl5 Library Devel::Cover is Missing: Library is require to perform an action. Please, install it first`?

**Comment by hurricup** [comment]
Could you please make a screenshot of your expanded dependencies  in project tree?

**Comment by floreal** [comment]
Here are some screenshots (couldn't fit everything inside only one). Do you expect to see some other libraries ?
![devel-cover](https://user-images.githubusercontent.com/386442/43315190-8261d2a6-9195-11e8-83d2-54f1c9d8bb0d.png)
![devel-cover-2](https://user-images.githubusercontent.com/386442/43315198-876216ee-9195-11e8-98b2-319ffce6c325.png)
![devel-cover-3](https://user-images.githubusercontent.com/386442/43315205-8b8e5b92-9195-11e8-9d84-d4d052eaee26.png)

**Comment by hurricup** [comment]
Relates to #320
