### ISSUE TITLE
Issue with literal annotation for here-doc strings 

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#1789]
Hi,

When working with DBI, I often use construction like:

```perl
$st = $db->prepare(<<__SQL);
SELECT * FROM ...
__SQL
```

When here-doc is used in this style (as argument or member of a list), it is not recognised by `@inject` annotation (it is even worse if there is more than one of them).

Word "SQL" in delimiter is not recognized as injection language as it starts with underscores (which really helps to visually highlight here-docs start/end).

It would be really nice either to allow `@inject` to annotate such construction or to ignore non-letters and underscores in delimiter when trying to match injected language, or (probably even better) only try to match last word (letters only) in delimiter string.

Thank you!

**Comment by elcamlost** [comment]
@hurricup I faced similar issue. My colleague uses lowercase to define injections via here doc, something like

```perl5

$db->query(<<~\sql, $entity->id);
            select * from table where true
                and id = ?
            sql
```

As far as I can understand, injection list is defined [here](https://github.com/Camelcade/Perl5-IDEA/blob/86a71036f73633d2679550d0ebd532f30a91cfb6/src/com/perl5/lang/perl/idea/intellilang/AbstractPerlLanguageInjector.java#L32) and is not configurable at all.

Maybe it will be a good feature, to configure bindings between inject keyword and language, supported by IDEA?

**Comment by hurricup** [comment]
Ye, good point.
