### ISSUE TITLE
File extension .psgi

### ISSUE THREAD

**Issue by sysdef** [Camelcade/Perl5-IDEA#1790]
Sadly PSGI/PLACK files are not getting recognized as Perl files.

---

Perl5 plugin version 2018.2

PhpStorm 2018.2.2
Build #PS-182.4129.45, built on August 22, 2018
Licensed to PhpStorm Evaluator
Expiration date: September 27, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.0-7-amd64

**Comment by hurricup** [comment]
Open settings and find file assiciations there. You may change them as you want.
https://www.jetbrains.com/help/phpstorm/settings-file-types.html
