### ISSUE TITLE
When remote project root is symlink, debugging doesn't function

### ISSUE THREAD

**Issue by marrem** [Camelcade/Perl5-IDEA#1793]
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
Licensed to Marc Remijn
Subscription is active until February 2, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

My server (remote debugging) runs FreeBSD

Home dirs live under a symlink at the server I'm using. 
/home -> /usr/local/home/

When I enter /home/myHome/myProject as project root, debugging doesn't work (doesn't stop at breakpoints).
However when I enter /usr/local/home/myHome/myProject, debugging does work OK.

I don't know whether this counts as an issue, since symlinks are platform dependent.

**Comment by hurricup** [comment]
Nope, I believe it's not an issue. Remote root should be specified as perl sees it. And seems it sees resolved one.
