### ISSUE TITLE
Показывать в дебагере fileno файлового дескриптора

### ISSUE THREAD

**Issue by ivanych** [Camelcade/Perl5-IDEA#1794]
В дебаггере, при просмотре переменной, если эта переменная - файловый дескриптор, хотелось бы видеть `fileno` этого дескриптора.

**Comment by hurricup** [comment]
Is this ok? 

![image](https://user-images.githubusercontent.com/2811330/46629510-bd132600-cb49-11e8-96d7-863e6e7d70d0.png)

![image](https://user-images.githubusercontent.com/2811330/46629521-cb614200-cb49-11e8-89bd-a45f072e1bd5.png)

**Comment by ivanych** [comment]
То, что нужно!
