### ISSUE TITLE
Inline documentation "Ctrl+Q" not found correctly

### ISSUE THREAD

**Issue by Christoffen** [Camelcade/Perl5-IDEA#1795]
Hello,

I installed the plugin a week ago and it is pretty awesome. But I have an issue with inline documentation. Maybe someone can help me out. Thank you.

### first of the system informations:
  * IntelliJ IDEA Community 2018.2.4 Build #IC-182.4505.22
  * Perl5 plugin version:  2018.2.1
  * JRE version : 1.8.0_152 release-1248-b8 amd64
  * Ubuntu 14.04.4 LTS

### Short version:
I have a project with two ".pm" files in a library folder. The first file contains a class (package) called string_operation. It has several subroutines, each has a POD block directly before it. The second file contains just one subroutine and is called inside the string_operation function with "main::get_argument()". It also has a POD block in front of it. 
In the "string_operation" file, I can "Ctrl + left click" on "main::get_argument()" and it will open the file in a new tab. If I click "Ctrl + Q" on "get_argument", then the documentation for "string_operation" is opened. But I expected, that "Ctrl +Q" would open the inline documentation of "get_argument".
I would appreciate, if someone could help me out.

Kind regards,

Christoffen

### Longer version/ additional Info:
Maybe it is a problem with a setting. While installing I followed the "getting started" Wiki page step by step. The project has the structure:

project 
 * .idea
 * sub_project
   * other_folder
      * main_routine.pl
   * library
      * get_argument.pm
      * string_operation.pm

the project folder is marked with a teal square. The library is marked in purple.

Also, if I press "Alt +Q" in a sub in "string_operation" I expected, that it would highlight the function name (e.g. "string_operation::split_string()"). I expect that, because I understand issue #1585 this way. But instead, "Alt + Q" highlights the namespace/package name ("string_operation"). 
Maybe this has something to do with it.

I hope that these information are sufficient. If I can provide any additional information let me know.

Thank you and kind regards,

Christoffen

**Comment by hurricup** [comment]
sample project could be very helpful.

**Comment by Christoffen** [comment]
sure, sry. This sample project (stored as zip) works (and doesn't work) as described above.

[sample_project.zip](https://github.com/Camelcade/Perl5-IDEA/files/2450541/sample_project.zip)
