### ISSUE TITLE
Incorrect inspection on do {} while() loop

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#1832]
Hi,

The following code:
```perl
use strict;
use warnings;

do {
    last;
    continue;
} while (0);
```

produces errors on inspections:

`last can't be used inside the block with return value, such as 'eval'/'sub'/'do'`
`continue can't be used inside the block with return value, such as 'eval'/'sub'/'do'`

Which is not exactly right, as do {} while (0) is just another variation of while() loop, not intended to produce any value.

IDEA 2018.2.5 Build #IU-182.4892.20, Perl plugin 2018.2.1

**Comment by hurricup** [comment]
According to perldoc - it does not. https://perldoc.perl.org/functions/last.html
However, doc is wrong and these keywords works very differently. And this fact is mentioned in the inspection description.

**Comment by aldem** [comment]
Hmm, indeed... Strange though, as I have found this in old code which was running in production mode (and very old perl, obviously - perhaps sometime it could work).

Well, then please forget this ticket :)
