### ISSUE TITLE
bug in Perl settungs dialog

### ISSUE THREAD

**Issue by SergBobrovsky** [Camelcade/Perl5-IDEA#1833]
ubuntu 18.10
RubiMine 2018.2.4
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b8)
OpenJDK 64-Bit Server VM (build 25.152-b8, mixed mode)
Perl plugin 2018.2.1
![screenshot from 2018-11-14 02-04-20](https://user-images.githubusercontent.com/13639764/48449445-8d43e780-e7b3-11e8-951d-d6dc18953ec8.png)
контрол доступен, но полускрыт.

**Comment by hurricup** [comment]
dupe #1786 
hard to discover, sorry. Also, why do you need to add `/usr/bin` as an external library? It's fro out-of-project non-interpreter libraries, e.g. other project.
