### ISSUE TITLE
Template Toolkit Support v2018.3 has no effect on WebStorm v2018.3

### ISSUE THREAD

**Issue by ConnorSinnott** [Camelcade/Perl5-IDEA#1843]
> WebStorm 2018.3
> Build #WS-183.4284.130, built on November 19, 2018
> JRE: 1.8.0_152-release-1343-b15 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.15.0-39-generic

I have just updated WebStorm to version 2018.3 and updated the Perl plugin. I noted that some features have been separated and installed Template Toolkit Support from the link provided. Unfortunately, while Perl works, the editor still has no support for Template Toolkit. There is no syntax highlighting and I have not found any entries into the preferences menu related to Template Toolkit other than the plugin installation page.

**Comment by hurricup** [comment]
Thank you. Investigating.

**Comment by ConnorSinnott** [comment]
This has resolved the issue! Thank you!
