### ISSUE TITLE
Unresolved variable inspection inside Perl5 libiraries not working

### ISSUE THREAD

**Issue by Zaitsev** [Camelcade/Perl5-IDEA#1868]
In project I have `lib` directory marked as _Perl5 lib_

for modules _inside_ `lib`  _unresolved variable_ inspections stop working in Idea 2018.3,
for modules _outside_ lib all is good.
Removing directory mark  _Perl5 lib_  enables inspection again

![image](https://user-images.githubusercontent.com/127843/49642023-9292fb80-fa1a-11e8-8f48-49fdae91e575.png)

```
IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

with 2018.2 it was OK
```
IntelliJ IDEA 2018.2.6 (Ultimate Edition)
Build #IU-182.5107.16, built on November 6, 2018
JRE: 1.8.0_152-release-1248-b22 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
![image](https://user-images.githubusercontent.com/127843/49642910-f0284780-fa1c-11e8-9bf3-afa4665e5324.png)

**Comment by hurricup** [comment]
Caused by Kotlin plugin. Disabling should help.
Do you have it in 2018.2?

**Comment by Zaitsev** [comment]
I have Kotlin enabled in 2018.2 .
Disabling Kotlin in 2018.3 resolves issue.
