### ISSUE TITLE
Debugger won't start - exit code 2

### ISSUE THREAD

**Issue by dankasak** [Camelcade/Perl5-IDEA#1877]
I'm setting up a new dev laptop, and I can't get the debugger to start. I've configured my system perl in Intellij, installed Devel::Camelcadedb from cpan, and set up a debugging profile for one of my projects. Instead of starting a debugging session, I get:

---

Connecting to 0.0.0.0:44193...
Disconnected
/usr/bin/perl -d:Camelcadedb -I . /home/dkasak/work/Smart/Smart_Framework/smart_gui/main.pl --no-redirect --open=browser
Listening for the IDE connection at 0.0.0.0:44193...

Process finished with exit code 2

---

Interestingly, I *have* been able to connect IntelliJ directly to a Camelcadedb session ( ie remote debugging ) ... but it doesn't seem to honour my breakpoints :/

---

* IDE name and version, including build:
IntelliJ IDEA 2018.3.2 ( Community Edition )
#IC-183.4886.37
* Perl5 plugin version
v2018.3.5
* JRE version
1.8.0_152-release-1343-b26 amd64 ( as reported in Help => About )
* Your OS name and version
Gentoo, current

**Comment by hurricup** [comment]
Looks like https://github.com/Camelcade/Perl5-IDEA/issues/1854 but this been fixed exactly in 2018.3.5
Are you sure about your plugin version?
Missing breakponts usually related to wrong `Remote project root` configuration see wiki.

**Comment by dankasak** [comment]
Hi there. Thanks for the response. Yes, I'm certain about the plugin version:

![shot-2019-01-18_19-43-39](https://user-images.githubusercontent.com/7410307/51375290-948fc480-1b59-11e9-9664-379f9e3fc57b.png)

Thanks for the tip about missing breakpoints. I'll look into this.

**Comment by hurricup** [comment]
Is it possible to get a sample script?

**Comment by dankasak** [comment]
Thanks again for the response. I've played around, simplifying things, until discovering that even this fails to start:

`use strict;
use warnings;

print "Hello, world\n";`

**Comment by dankasak** [comment]
Yikes :) Maybe it's a perl-5.28 thing? I've never had any Gentoo-related issues, and I've been using Gentoo & IntelliJ/Camelcade/Perl5-IDEA for years. Anyway ... I've never done any Java development / debugging. Is it simple to set up? Got any docs? Sorry ... I've managed to completely avoid Java up until now.

**Comment by hurricup** [comment]
Prior the last version perl process connected to the IDE. Now it works opposite. And this caused some problems.
Yes, it's pretty straightforward. you need to have JDK on your machine. Then just clone this repo and open directory by IDEA. It will suggest to import `gradle` project - do it. 
Then you'll have a `Run Plugin` run configuration. Debug it. Use breakpoints and see what is going on with socket. There is nothing specific to the IDE/platform/jave, just some `Socket` thing.

**Comment by dankasak** [comment]
I've started with a fresh profile ( rm -rf .IdeaIC2018.3 ) and opened the directory ~/src/Perl5-IDEA in IntelliJ. It did ask me to import some gradle stuff, so I accepted. I don't see the 'Run Plugin' configuration. Is this what it should look like so far?

![shot-2019-01-19_11-16-56](https://user-images.githubusercontent.com/7410307/51419108-09a3de00-1bdc-11e9-9f11-b71f52ab38e6.png)

There were a bunch of errors and warnings when I tried to compile ...

**Comment by dankasak** [comment]
I have it working! Thanks a lot for your help. It turns out I hadn't fully completed my network setup - my hostname was defaulting to localhost.localdomain ... which wasn't resolving. Setting a fixed IP in my router and adding an entry to /etc/hosts has fixed things.

I should note that the part that logs the error that was occurring:

```
    catch (Exception e) {
      LOG.warn(e);
    }
```

 ... around line 182 of PerlDebugThread.java ... I don't know where this was logging to, but I didn't see the error inside IntelliJ / Perl5-IDEA. If it *had* logged into IntelliJ's console, it would have been easier to fix, obviously.

Anyway, thanks again for your help!
