### ISSUE TITLE
Feature request: Code injection with PSI statement

### ISSUE THREAD

**Issue by Christoffen** [Camelcade/Perl5-IDEA#1878]
Hi Hurricup and others,

In other languages (e.g. python, java, sql) code injection can be automated with rules defined over the PSI patterns. 
These rules can be defined under Settings -> Editor -> Language Injections by creating a new rule or importing a .xml file. 
Here is an example .xml file (converted to .txt), which tells the python parser to check each PsiElement "pyStringLiteral" for the Keywords "SELECT, DROP, etc" and if true, then the String is interpreted as PostgreSQL. 

[example_code_injection.txt](https://github.com/Camelcade/Perl5-IDEA/files/2772907/example_code_injection.txt)

I tried creating such an automation by using the "PsiPerlStingSqImpl" (which I recieved from the PSI Viewer), and changing the injector-id of the .xml file to "perl5", "Perl5", "perl" or "Perl". 
When importing it says "no new entries have been imported", probably because it does not understand the injector-id.

It would be great, if you could think about this feature for a moment, because I think, that it has great potential. For example auto injecting SQL statements or injecting bash code in perl's qx() / system() function.

Kind regards,

Christoffen

  * PyCharm 2018.3.3, build #PY-183.5153.39
  * Perl5 plugin version 2018.3.5
  * JRE version: 1.8.0_152-release-1343-b26 amd64
  * Ubuntu 18.04

**Comment by hurricup** [comment]
I'll check this feature. However, are you aware about injecting by heredoc marker and `#@inject` annotation?

**Comment by Christoffen** [comment]
Ah, I did not know about the Injection Markers in the settings page. This works great now. Thank you for your help.

**Comment by hurricup** [comment]
What patterns would you like to have?
Only two cases comes to mind: strings matching regexps and positional argument to the sub. 
E.g. `subArgument('DBD::_::selectrow_arrayref', 1)` meaning that first argument of such call should be injected.

**Comment by hurricup** [comment]
Thank you for the cool request. Didn't know about this IDE feature :) Should be available in the next plugin EAP for 2019.1 EAP testers, so you may try. For now added only regexp-based literal injections. Feel free to submit a new issue if you need additional patterns.

**Comment by Christoffen** [comment]
Thank you hurricup. you are a great developer! :)

regexp is pretty handy to automate injection
