### ISSUE TITLE
Unable to set Perl5 Interpreter Windows

### ISSUE THREAD

**Issue by EdenOaksConsulting** [Camelcade/Perl5-IDEA#1879]
* IDE: #PY-183.4284.139
  * Perl5 plugin: v2018.3.5
  * JRE version on PyCharm About: JRE 1.8.0_152
  * JRE version from 'java -version': 1.8.0_201
  * Windows Server 2016

I'm unable to add the Perl5 interpreter on Windows.  Checking some of the other threads, they mention selecting the folder and not the executable, but the dialog box will only allow a file selection and not directory.  My Perl system is delivered/installed as support for another application.  I'm using the "Add system Perl" option and have target version set as v5.10.

When the perl executable is selected (tried both perl.exe and perl5.10.0.exe), error returns: "Failed to fetch perl version, see logs for more details"

When checking the idea.log, I see this command line: "Executing: C:/Hydstra/hyd/sys/perl/bin/perl.exe -v"
"    environment: {} (+CONSOLE)"
"    host = local; vm = system; pty = false; charset: windows-1252 "

When I run "C:/Hydstra/hyd/sys/perl/bin/perl.exe -v" command manually, I see this Perl response: "This is perl, v5.10.0 built for MSWin32-x86-multi-thread"

**Comment by hurricup** [comment]
This is the case. Regexp expects `\([^)]+\) built for .+`. Seems this is not always true.

**Comment by EdenOaksConsulting** [comment]
Is there a way I can edit the Regexp to allow for the returned string I see?

Thanks

**Comment by hurricup** [comment]
Here is it. https://github.com/Camelcade/Perl5-IDEA/blob/master/core/src/com/perl5/lang/perl/idea/sdk/PerlSdkType.java#L313
I'm thinking about proper solution here, but you can hack and build a plugin for yourself. See readme for instructions

**Comment by hurricup** [comment]
As workaround you may also try:
1. Add some system perl
2. Close the IDE
3. Find file `config/options/jdk.table.xml` in [IDEA config dir](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)
4. Open it in editor, find a section related to just added interpreter and adjust path to interpreter. 
5. Close file and start IDE
6. Open or create any project
7. Select this hacked interpreter as perl interpreter for the project, click ok
8. Press `Ctrl-Shift-A` and type `refresh` in opened `find action` window. 
9. There should be `Refresh Interpreter Information` action. Run it. It should update `@INC` for your interpreter. 

This should help.

**Comment by EdenOaksConsulting** [comment]
> As workaround you may also try:
> 
> 1. Add some system perl
> 2. Close the IDE
> 3. Find file `config/options/jdk.table.xml` in [IDEA config dir](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)
> 4. Open it in editor, find a section related to just added interpreter and adjust path to interpreter.
> 5. Close file and start IDE
> 6. Open or create any project
> 7. Select this hacked interpreter as perl interpreter for the project, click ok
> 8. Press `Ctrl-Shift-A` and type `refresh` in opened `find action` window.
> 9. There should be `Refresh Interpreter Information` action. Run it. It should update `@INC` for your interpreter.
> 
> This should help.

Thanks for the suggestions, this is now working.  The jdk.table.xml never showed a perl interpreter.  I added a configuration to `config/options/perl5.xml` instead.

```
<application>
  <component name="Perl5ApplicationSettings">
    <option name="pluginVersion" value="2018.3.5" />
    <option name="popupShown" value="true" />
  </component>
  <component name="PerlInterpreters">
    <perl version="2">
      <name value="Local, System: Perl v5.10.0" />
      <type value="Perl5 Interpreter" />
      <homePath value="C:/Hydstra/hyd/sys/perl/bin/perl.exe" />
      <roots>
        <classPath>
          <root type="composite">
            <root url="file://C:/Hydstra/hyd/sys/perl/lib" type="simple" />
            <root url="file://C:/Hydstra/hyd/sys/perl/site/lib" type="simple" />
          </root>
        </classPath>
        <sourcePath>
          <root type="composite" />
        </sourcePath>
      </roots>
      <additional>
        <host id="localhost" />
        <implementation id="porters" />
        <versionManager id="system" />
      </additional>
    </perl>
  </component>
</application>
```

**Comment by hurricup** [comment]
Oh, sorry, right, perl sdks stored separately, forgot :)
