### ISSUE TITLE
Не инспектится POD после __END__

### ISSUE THREAD

**Issue by ivanych** [Camelcade/Perl5-IDEA#1907]
Если POD расположен после метки `__END__`, то он не отображается в закладке "Structure".

Пример:

```perl
1;
 
# ABSTRACT: A postmodern object system for Perl 5
 
__END__

=pod
 
=encoding UTF-8
 
=head1 NAME
```

Если стереть `__END__` - всё отлично начинает отображаться.

**Comment by hurricup** [comment]
Duplicates https://github.com/Camelcade/Perl5-IDEA/issues/1896
