### ISSUE TITLE
Add color settings for the Pod Text

### ISSUE THREAD

**Issue by tomk3003** [Camelcade/Perl5-IDEA#1931]
![pod_text_high](https://user-images.githubusercontent.com/15907646/53330549-0db7cf80-38ef-11e9-9400-362549287503.png)
* PyCharm 2018.3.4 (#PC-183.5429.31)
* Perl5 plugin version v2018.3.5
* JRE version 1.8.0_152
* Windows 7 with strawberry perl 5.26.1

I cannot get POD Text to highlight correctly. The selected colors will be applied to the space **after** the text (see attached image, I used pink as the backgroud color for clarification).

**Comment by tomk3003** [comment]
I see that the entry for `Text` has been removed in 2019.1. 
Does that mean that Pod text cannot be colored differently? At the moment I can only modify it via "General/Text/Default Text".
I would like to be able to separate Whole Pod Blocks visually. Preferrable by background color. If that is not possible, I would like to set it for the Pod Text.

**Comment by hurricup** [comment]
Yep, it's just uses default text color. Let's rephrase this issue to a new feature request. There are some problems to change it at once and existed approach was obviously wrong.
