### ISSUE TITLE
Make a run configuration to run with prove

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1935]
This is a light implementation for test support. 
Kinda subtask of #805

From @tomk3003
 > Ok, my description was a bit too short. What I want to do is, run the tests in the current .t script with Ctrl+Shift+F10 and being able to run this in the debugger if needed. For this to work I'll need to run prove -m instead of the perl interpreter. Running just the script works, but diag output is not where it should be. Setting perl/bin/prove as perl5 parameter works for run, but debugging will then debug the prove script itself instead of the test script.
The nicest to have option would be, being able to run an arbitrary command as the current interpreter. That way I could run whatever I want.

**Comment by hurricup** [comment]
@tomk3003 sounds nice and shouldn't be hard to implement. However, how should command line looks when starting prove with debugger? The only option I've googled is using `PERL5OPT` but shouldn't it affect `prove` itself, as far as it's a perl script?

**Comment by tomk3003** [comment]
My problem with running prove (via `Perl5 parameters:`) in the debugger was, that the breakpoints I set in the `.t` script were ignored. This works fine when debugging the script directly. When you want to support running prove, the parameters to prove should be configurable in the run configuration.
The `-I` option reflects that of perl itself and should be set automatically. 
If you could fix the debugger/breakpoint problem, the solution with `Perl5 parameters:` would work without having to change anything else.

**Comment by hurricup** [comment]
Just deployed build `191.5849.1` check it out

**Comment by tomk3003** [comment]
Should I be able to get this from a repo or do I have to build it myself?

**Comment by hurricup** [comment]
If you are using IDEA eap, should be available from the IDEA Plugins UI

**Comment by tomk3003** [comment]
I have now installed PyCharm eap. At a first glance it looks fine. Did you link `.t` files to automatically use the **'Perl 5 Test'** run configuration? If one is defined Ctrl+Shift+F10 uses this. That's cool. Even cooler would be, if I didn't have to create that manually when running a `.t` file for the first time. But this is not a complaint :wink:
I will evaluate further and give feedback if something comes up.
Thanks!

**Comment by hurricup** [comment]
Published next build with original issue resolve. Fancy test runner ui and stuff. Feel free to check.
