### ISSUE TITLE
Class cast exception with new plugin version (v191.6014.4)

### ISSUE THREAD

**Issue by macrivello** [Camelcade/Perl5-IDEA#1959]
I updated the Perl plugin this morning, and my previously working remote debug configuration is now throwing the following error:
`com.perl5.lang.perl.idea.run.remote.PerlRemoteDebuggingConfiguration cannot be cast to com.perl5.lang.perl.idea.run.GenericPerlRunConfiguration
`
I'm not sure where I can get more information on the error, other than what is shown in the Event Log of Inteliji. 

Perl plugin v191.6014.4

IntelliJ IDEA 2019.1 Beta (Ultimate Edition)
Build #IU-191.6014.8, built on March 5, 2019
IntelliJ IDEA EAP User
Expiration date: April 4, 2019
JRE: 1.8.0_202-release-1483-b31 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.20.11-200.fc29.x86_64

**Comment by hurricup** [comment]
Uploaded build 191.6014.5
Restart IDE, you will be able to update. Thanks for report.

**Comment by macrivello** [comment]
Np, thanks for the quick fix and all the work you've done on this plugin!
