### ISSUE TITLE
Warnings for perlcritic via STDIN on .t files

### ISSUE THREAD

**Issue by tomk3003** [Camelcade/Perl5-IDEA#1997]
* PyCharm 2019.1 (Community Edition) Build #PC-191.6183.50, built on March 19, 2019
* JRE: 1.8.0_181-b13 amd64
* Perl5 plugin version 191.6183.RC2
* Windows 7 with strawberry perl 5.26.1

When perlcritic is automatically run for a single file in the editor, the source is fed via STDIN to perlcritic. This implicitly disables the "program-extensions" parameter set in .perlcriticrc, since there is no file and no extension. As a result perlcritic assumes .t files are modules not scripts and complains about the missing "package" directive and true statement at the end.

**Comment by tomk3003** [comment]
Just found out, that adding a shebang line to the .t file seems to tell perlcritic to treat the input from STDIN as script. So there is an easy workaround.

**Comment by hurricup** [comment]
I'm not so familiar with the `Perl::Critic`. Isn't it possible to enforce expected behavior with `perlcritic` command line options? Enforcing to  add a shebang to every test may be not so cool idea.

**Comment by tomk3003** [comment]
There is only `--program-extensions ".pl .t"`. But if the script is fed via STDIN this will not work. Somehow you have to determine, what is coming over STDIN. The default is expecting a package, if there is no shebang.

**Comment by tomk3003** [comment]
What about not using STDIN at all and always using the file?

**Comment by hurricup** [comment]
Not a chance.
IDE does not saving file after each change. Only on demand or by timer
(with larger span).
Also, automatic saving may be disabled by user.
Also some ppl have hooks on running tests on saving a file in project.
Also this is unnecessary overhead.
However, we could add a shebang when sending script (non pm file) and strip
it on the way back.

ср, 27 мар. 2019 г. в 17:14, tomk3003 <notifications@github.com>:

**Comment by hurricup** [comment]
But still feels like it should be handled on perlcritic side. If there is no such option, probably nice thing for a pull request, or at least feature request at https://github.com/Perl-Critic/Perl-Critic

**Comment by tomk3003** [comment]
I'll try to get a change into Perl::Critic. I don't think you should worry about handling this. Feel free to close the issue.
