### ISSUE TITLE
Updating to 2019.1 breaks the plugin

### ISSUE THREAD

**Issue by rohanahata** [Camelcade/Perl5-IDEA#2000]
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 11.0.2+9-b159.30 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

 Perl5 plugin - v2018.1.1
  

java version "1.8.0_161"
    Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
     Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

 MacOS Mojave 10.14.3

**Comment by hurricup** [comment]
Just update the plugin. v2018.1 is suitable for IDEA 2018.1 only.
