### ISSUE TITLE
Race condition when starting debugger on Docker interpreter

### ISSUE THREAD

**Issue by asdfg** [Camelcade/Perl5-IDEA#2040]
Sometimes when I debug with my Docker interpreter (simple CentOS 7 image), the debugger does not start properly. It happens randomly, maybe around 40% of the time. I just try rerunning again and eventually it will connect and work as expected.

Full console output (total run time < 1s):
> Connecting to 0.0.0.0:53220...
> Connected
> Disconnected
> Process finished with exit code 0

It seems to be fixed if I add a 5s Thread.sleep before prepareAndConnect() in PerlDebugThread.
https://github.com/Camelcade/Perl5-IDEA/blob/6efaa04d67c573f73da759f853d067c927c0ddd4/core/src/com/perl5/lang/perl/idea/run/debugger/PerlDebugThread.java#L171-L173

Windows 10 Professional
IntelliJ IDEA 2019.2 Ultimate EAP
Perl plugin & Docker support 2019.1.1

Thank you!

**Comment by hurricup** [comment]
I'm a bit confused - is this a remote debug (Remote debug configuration) or just regular debug with docker interpreter?

**Comment by hurricup** [comment]
Probably when exposing ports from docker, docker daemon starting listening ports before inner process actually do this. And when we are trying to read/write to socket we are getting EOF.

**Comment by asdfg** [comment]
> I'm a bit confused - is this a remote debug (Remote debug configuration) or just regular debug with docker interpreter?

Sorry, it's indeed regular debug with the docker interpreter.

**Comment by hurricup** [comment]
Would be nice if you could build plugin from github and check if this change helps. 
See https://github.com/Camelcade/Perl5-IDEA/blob/master/README.md for instructions

**Comment by asdfg** [comment]
Working great, debugger's totally reliable now. Thank you so much!

**Comment by hurricup** [comment]
Thanks for reporting and verifying!
