### ISSUE TITLE
Quick fixes for Truthiness inspection are broken

### ISSUE THREAD

**Issue by Zastai** [Camelcade/Perl5-IDEA#2041]
IDEA Ultimate 2019.1.1 (#IU-191.6707.61)
Perl plugin v2019.1.1
JRE: Oracle JDK 1.8.0_202
OS: Windows 10

There seems to be a new "Truthiness" inspection.
While I'm not sure this should be on by default, the main issue is that the quick fixes are broken.

For
```perl
if ($foo) { ... }
```
it offers 3 quick fixes, resulting in:
```perl
if (defined $foo) { ... }    # Add defined check
if ($foo eq '')   { ... }    # Add empty string equality check
if ($foo == 0)    { ... }    # Add zero equality check
```
The first one is fine (although it would be better style to use `defined($foo)`).
However, the other two *invert the semantics of the check*!
Similarly, `!$foo` gets incorrectly quick-fixed to `$foo ne ''` and `$foo != 0`, so it looks like a trivial thing to correct.

**Comment by hurricup** [comment]
Crap
