### ISSUE TITLE
Running test in debug mode won't make IDE attach to debugger

### ISSUE THREAD

**Issue by floreal** [Camelcade/Perl5-IDEA#2052]
## How to reproduce

1. I wrote a few tests scripts (using Test::Class)
2. Running them in normal mode works fine

## Result

Running them in debug mode get stucks with this output:
```
Listening for the IDE connection at 0.0.0.0:38673...
Waiting for process to start...
Waiting for process to start...
Waiting for process to start...
(...)
Disconnected
```

If i run one of them as a script with debug mode, The IDE is able to connect to debugger.

I tried this with single job test and several jobs test, the result is the same.

**Comment by floreal** [comment]
I believe the perl argument -d:Camelcadedb is not provided by the command line that are running test as debug:

```bash
/home/floreal/.plenv/bin/plenv exec perl5.18.2 /home/floreal/.plenv/versions/5.18.2/bin/prove -PPassEnv --formatter TAP::Formatter::Camelcade --merge --recurse --jobs 1 $TEST
```

**Comment by hurricup** [comment]
It's passed with environment, check IDE's log. Probably this is regression from  recent change for docker lagging. https://github.com/Camelcade/Perl5-IDEA/issues/2040

**Comment by hurricup** [comment]
This subsystem lacks of tests atm.

**Comment by floreal** [comment]
Hello, just tried with version 2019.1.3, and I confirm that the issue is solved. Thank you !

**Comment by hurricup** [comment]
Thanks for reporting!

**Comment by avanp** [comment]
I have the same problem here, the debugger won't attach with the very same message on IJ Ultimate 2020.1.3. 
Verified that the interpreter is started with proper -d option and also checked the log for strange oddities. Also tried to restore IDE's configuration and even reinstalling. 

Does not happens each time and often, launching a debugging session on other projects (java, for examples) solves the issue for a moment.

Any idea that can help? 
Thank you!

**Comment by hurricup** [comment]
Please start another issue. This one been fixed. you probably got something else.
