### ISSUE TITLE
Very strange behaviour when typing colon character in keyboard in text files in CLion 2019.2 EAP

### ISSUE THREAD

**Issue by maxim-banaev** [Camelcade/Perl5-IDEA#2055]
In a file associated with type 'text' if I type : then the character will:
* Appear then disappear
* Not appear (preceding text has '#define' )

This is not evident with other file type associations. The workaround, for now, is to paste the desired text in from another text editor.

Bug present in Windows Server 2012 R2 and Ubuntu 18.04

CL-192.4205.36, JRE 11.0.3 12-b248.2x64 JetBrains s.r.o, OS Windows Server 2012 R2(amd64) v6.3 , screens 1920x1080

https://youtrack.jetbrains.com/issue/CPP-16343

**Comment by hurricup** [comment]
Seems it was https://github.com/Camelcade/Perl5-IDEA/commit/f49bdbab72aab30956d7a9824dcd18e9c4926ad7 fixed from analyzer

**Comment by hurricup** [comment]
I'll add check for not my file.
