### ISSUE TITLE
Multiple readings from STDIN doesn't work

### ISSUE THREAD

**Issue by igra** [Camelcade/Perl5-IDEA#2058]
**Multiple readings from STDIN doesn't work**

Try to execute following code 

```
print "Your name: ";
chomp(my $name = <STDIN>);

print "Your age: ";
chomp(my $age = <STDIN>);

print "Hello, ", $name, ". You are ", $age, " years old!", "\n";
```

from command line - it works fine.

But when you're running in IntelliJ Idea using the plugin - **it doesn't read second input**.

_perl 5, version 18, subversion 2 (v5.18.2)_

**Comment by hurricup** [comment]
Please also specify your os and interpreter type (local/docker/wsl)

**Comment by igra** [comment]
macOS Mojave , Version 10.14.1
Interpreter type - local

**Comment by hurricup** [comment]
Seems works fine on linux. I'll check on Mac as soon as I get the chance.

![image](https://user-images.githubusercontent.com/2811330/59141892-900b6180-89bd-11e9-95b2-a2f8a2f00d74.png)

**Comment by hurricup** [comment]
Reproduced on mac-os

**Comment by hurricup** [comment]
Looks like it works in 2019.2 EAP. Probably something was wrong with console.

**Comment by hurricup** [comment]
@igra could you please try 2019.2 eap?

**Comment by igra** [comment]
@hurricup I'm using only release versions. Updated from  IDEA 2019.1.1 ->  IDEA 2019.1.3.  Still doesn't work.

This looks like a bug in IntelliJ Idea release version, right ?

**Comment by hurricup** [comment]
Hard to say. I'm not suggesting you to use EAP. Just to check if it fixes your case. You can still use the 2019.1 for your work and wait till 2019.2 is released.

**Comment by hurricup** [comment]
Yes, it should work fine in 2019.2, sorry for inconvenience.
For now enter is doubled, so as workaround you may add an extra `<>;` between inputs.

**Comment by igra** [comment]
@hurricup In case of using the proposed workaround program will work differently from command-line and from IntelliJ IDEA.
So, it is better to use command line until 2019.2 is released.

**Comment by hurricup** [comment]
Yes, I know that. Just saying.

**Comment by igra** [comment]
@hurricup thanks
