### ISSUE TITLE
Mojolicious improvements

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2062]
- [x] Mojo project model
- [x] Action to install mojo
- [x] Action to generate app
- [x] Action to generate lite_app
- [x] Action to generate plugin
- [x] Templates source root with actions
- [x] Actions localization
- [x] Validator for app name
- [x] Validator for plugin name
- [x] lite app may have a name
- [x] Handle mojo lite imports (dsl and stuff)

**Comment by elcamlost** [comment]
Is there any chance to add support for mojo method resolutions?

For example, small snippet
<img width="267" alt="image" src="https://user-images.githubusercontent.com/5188593/59565397-df0b6380-905b-11e9-8738-67d45f184e63.png">

Second methods in chains unresolved.

**Comment by hurricup** [comment]
Have you tried 2019.2 EAP? It's should be better

**Comment by elcamlost** [comment]
Not yet. Is there a way to test plugin without upgrading IDEA?

**Comment by hurricup** [comment]
With toolbox you may install both versions
