### ISSUE TITLE
SQL injection marker is ignored when variable is referenced in heredoc

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2080]
Not sure if this is intentional or not, but when variable is referenced inside of SQL injection, injection marker is ignored:

![image](https://user-images.githubusercontent.com/754722/60834681-809c5580-a1c1-11e9-8215-0cf3d8cbaf25.png)
(__SQL mapped to PostgreSQL).

What puzzles me is that in regular string it does work as expected:

![image](https://user-images.githubusercontent.com/754722/60834908-133cf480-a1c2-11e9-9345-744d9dad2657.png)

IntelliJ IDEA 2019.1.3 (Ultimate Edition) Build #IU-191.7479.19, built on May 28, 2019 | Perl v2019.1.3 | JRE: 1.8.0_202-release-1483-b58 amd64|Windows 10 10.0|

**Comment by hurricup** [comment]
There is a setting for that. Enable injection with interpolation or smth like that. The reason for disabling this by default is that interpolation may break injected syntax and cause error highlighting.
