### ISSUE TITLE
Method resolution doesn't work with straight assignments and type hints in sub definition

### ISSUE THREAD

**Issue by a1111exe** [Camelcade/Perl5-IDEA#2092]
The last upgrade a few days ago broke some things that worked until that. This issue is about method resolution (when you can navigate to method definition or find its usages). Versions are at the bottom of the message.

So the problem is as described in the subject: method resolution doesn't work with straight assignments and type hints in sub definition. 

Screenshot demonstrating the problem:
![image](https://user-images.githubusercontent.com/9428898/62206682-05caf280-b39b-11e9-99f0-e2c999ae8637.png)

Also zip with sources to reproduce is attached:
[camelcade-issues.zip](https://github.com/Camelcade/Perl5-IDEA/files/3451363/camelcade-issues.zip)

**IDE**:
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-54-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3038M
Cores: 4
Non-Bundled Plugins: Scratch, String Manipulation, com.perl5, BashSupport, de.espend.idea.php.annotation, com.vladsch.idea.multimarkdown, fr.adrienbrault.idea.symfony2plugin, org.toml.lang, org.rust.lang, org.zalando.intellij.swagger

**Perl5 plugin version**: 2019.2

**JRE version**:
*System*:
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
*PhpStorm*:
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**OS**:
Ubuntu 18.04.2 LTS, kernel 4.15.0-54-generic

**Comment by hurricup** [comment]
I believe the problem is tricky bless usage. 
Try to replace
`bless my $self = {}, $class;` with `my $self = bless {}, $class;`

**Comment by a1111exe** [comment]
> I believe the problem is tricky bless usage.
> Try to replace
> `bless my $self = {}, $class;` with `my $self = bless {}, $class;`

Done. It fixed the straight assignment, but not the sub definition with a type hint:

![image](https://user-images.githubusercontent.com/9428898/62215840-5a2c9d00-b3b0-11e9-95c0-3c44440b880f.png)

Ehh... Anyways, I don't think that I could realistically fix all the blesses over the whole project (about 50000 lines) that has a lot of classes with complex constructors. Also I won't be allowed to do this: the project is in production and has to work as stable as possible.

Is there any way to downgrade the plugin to the previous version without breaking things further?

**Comment by hurricup** [comment]
Only with downgrading IDE. I'm going to fix this.

**Comment by a1111exe** [comment]
Thanks a lot! By the way, your plugin with Phpstorm is the best IDE for Perl I ever worked with. A wonderful language and a wonderful plugin, so be blessed for all your hard work! :)

**Comment by hurricup** [comment]
Finished tunings with 7c685b5382c5a5aace2c37978d17c7e7ecdd71ad
