### ISSUE TITLE
Hash slices within references is incorrect

### ISSUE THREAD

**Issue by elcamlost** [Camelcade/Perl5-IDEA#2105]
This perl snippet is parsed uncorrectly by IDE

```perl
sub BUILDARGS ($, %args) {
    $args{_meta} = {delete %args{qw/ssp_id dsp_id/}};
    return \%args;
}
```

<img width="696" alt="image" src="https://user-images.githubusercontent.com/5188593/62844950-89ef7500-bccd-11e9-95f2-6acaf73af20b.png">

IDEA information
```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Licensed to Ilya Rassadin
Subscription is active until August 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: 
Non-Bundled Plugins: YAML/Ansible support, com.intellij.ideolog, com.github.jk1.ytplugin, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, com.perl5, com.perl5.lang.embedded, com.perl5.lang.mojo, com.perl5.lang.tt2, BashSupport, com.jetbrains.php, com.jetbrains.php.blade, de.espend.idea.laravel, com.wix.eslint, org.jetbrains.plugins.go, org.jetbrains.plugins.phpstorm-remote-interpreter, com.perl5.transport.docker, org.jetbrains.plugins.phpstorm-docker, Pythonid, org.toml.lang, uk.co.ben-gibson.remote.repository.mapper
```
Plugin version - 2019.2.2

**Comment by hurricup** [comment]
Did you mean `@args{qw/ssp_id dsp_id/}` ?

**Comment by elcamlost** [comment]
No. I meant exactly what I've written.
See https://perldoc.perl.org/perldata.html#Slices, **Key/Value Hash Slices** part.

**Comment by hurricup** [comment]
Oh, I see. 5.20 hash slices are not yet supported. Guess I have a ticket for them.

**Comment by elcamlost** [comment]
Strange. I was sure, that it worked in 2019.1 version

**Comment by hurricup** [comment]
I doubt it. There is a chance that this syntax not produced an error but parsed in some wrong way. 
https://github.com/Camelcade/Perl5-IDEA/issues/1279

I'll investigate a possibility to implement this into bugfix update, but this change may be too significant for it.

**Comment by hurricup** [comment]
Sorry, too dangerous for the bugfix update. Only in next version.
