### ISSUE TITLE
Help: How to debug perl script from browser

### ISSUE THREAD

**Issue by simonschaufi** [Camelcade/Perl5-IDEA#2127]
* IDE: Phpstorm 2019.3
* Perl5 plugin version: 2019.3
* JRE version: openjdk version "1.8.0_222"
* Ubuntu 18 LTS
* Also installed Devel-Camelcadedb with `sudo cpan Devel::Camelcadedb`

I browsed through the wiki (https://github.com/Camelcade/Perl5-IDEA/wiki/Perl-Debugger) and all the issues that are related to debugging and couldn't find anything helpful on how to setup browser debugging. Debugging within the IDE works fine but I have no idea how to configure my system in order to call `http://localhost/cgi-bin/test.cgi` and debug the test script which looks like this:

```
#!/usr/bin/perl
print "content-type: text/html\n\n";
print "Hi";
exit;
```

I use nginx with fcgiwrap and the following config:

```
server {
    ...

    location /cgi-bin/ {
        gzip off;

        fastcgi_pass unix:/var/run/fcgiwrap.socket;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    ...
}
```

The script is executed without problems and I can see "Hi" in my browser.

What do I need to do in order to debug this script when called from the browser? This is just a test script but later on I want to debug a whole perl application.

**Comment by hurricup** [comment]
There is no high-level way to debug a scripts opened in browser. You should configure remote debugging for that manually.

**Comment by simonschaufi** [comment]
I tried the remote debugging but still don't really know how to configure everything. PhpStorm listens on 0.0.0.0:12345 but now I'm stuck.

**Comment by hurricup** [comment]
Probably this issue will help https://github.com/Camelcade/Perl5-IDEA/issues/1771

**Comment by simonschaufi** [comment]
I was reading that issue before already and it was not helpful at all. Even googling for a couple of hours about other solutions didn't help as nobody seams to debug web applications but only cli scripts.

**Comment by simonschaufi** [comment]
@hurricup I got it working! Finally! :tada: 

Let me document it here even though the wiki would be a better place.

Setup IDE like this:
1. Add remote debugger with server host: `127.0.0.1` and port `12345` (can be any random number)
1. Change Shebang line to `#!/usr/bin/perl -d:Camelcadedb`

Setup nginx like this (port must match with IDE port):
```
server {
    listen 80;
    server_name .example.test;
    root "/home/username/Code/example.test";

    index index.html;

    charset utf-8;

    location / {
        index index.html;
    }

    location /cgi-bin/ {
        gzip off;

        fastcgi_pass unix:/var/run/fcgiwrap.socket;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PERL5_DEBUG_ROLE "client";
        fastcgi_param PERL5_DEBUG_HOST "127.0.0.1";
        fastcgi_param PERL5_DEBUG_PORT "12345";
        charset iso-8859-1;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/example.test-error.log error;

    sendfile off;
}
```

Then click "Debug..." in IDE in order to start listening and then open the perl script in the browser.

The key for me was not to set the environment variables in my home directory but right in the browser config and then change the Shebang.

Problem solved!

**Comment by hurricup** [comment]
referenced in documentation. thanks.
