### ISSUE TITLE
Remote debugging issue with IntelliJ IDEA Ultimate 2019.3

### ISSUE THREAD

**Issue by Slushnas** [Camelcade/Perl5-IDEA#2129]
First, thank you for creating these tools. They have been very helpful to my work.

I am experiencing an issue with remote debugging on the latest versions of IntelliJ and the Perl5 plugin that are preventing me from using it. The affected versions are:
```
IntelliJ IDEA 2019.3.1 (Ultimate Edition) Build #IU-193.5662.53
Perl5 plugin version 2019.3
```

I have two files on a remote server. The main file I am trying to remotely debug includes the other file in a require statement.

Main file:
```
#!/usr/bin/perl

use strict;
use warnings;
require './include_file.pl';
...
```

The include file has a few variables and a bunch of subroutines in it.
Include file:
```
#!/usr/bin/perl
my $var_1 = 'foo';
my $var_2 = 'bar';
my $var_3 = 'baz';

sub method_one {
...
1;
```

I connect to the remote server and it breaks on the `require './include_file.pl';` line of the main file. When I step over (F8) this line it loads the include file. I hit F8 again to step over the first variable ($var_1) and another tab appears with the message `# No source found for ./include_file.pl` which prevents me from debugging further.

If I do the same steps with the previous version of IntelliJ and the Perl5 plugin this does not happen. I am able to step over the three variables and the `1;` line at the bottom of the include file and continue debugging the main file as expected.

The working versions are:
```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)Build #IU-192.7142.36
Perl5 plugin 2019.2.4
```

My OS/Java info
```
Mint 19.2 (Ubuntu 18.04)
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
```

**Comment by hurricup** [comment]
does it work properly with local debugging?

**Comment by Slushnas** [comment]
Yes. As long as the working directory is set correctly in the local debug configuration it loads the include file and I can continue debugging.

**Comment by hurricup** [comment]
I could reproduce this only if `Remote project root` is incorrect in remote debugging run configuration. Or you don't have a local copy of the project.

Still, this behavior is unexpected and need to be fixed.

**Comment by hurricup** [comment]
Can you confirm that problem was with remote root?

**Comment by Slushnas** [comment]
I can't reproduce this bug with the newest version of IntelliJ Ultimate 2020.1 so I think this can be closed.
