### ISSUE TITLE
Use consistent indentation in Perl5.bnf

### ISSUE THREAD

**Issue by rillig** [Camelcade/Perl5-IDEA#2130]
When I view [Perl5.bnf on GitHub](https://github.com/Camelcade/Perl5-IDEA/blob/639e03a47083797aed72cc247279ea25f4ed80d3/plugin/core/grammar/Perl5.bnf), the lines look indented randomly. Some of the lines are indented [using tabs](https://github.com/Camelcade/Perl5-IDEA/blob/639e03a47083797aed72cc247279ea25f4ed80d3/plugin/core/grammar/Perl5.bnf#L1108), others are indented [using 4](https://github.com/Camelcade/Perl5-IDEA/blob/639e03a47083797aed72cc247279ea25f4ed80d3/plugin/core/grammar/Perl5.bnf#L1123) or [2 spaces](https://github.com/Camelcade/Perl5-IDEA/blob/639e03a47083797aed72cc247279ea25f4ed80d3/plugin/core/grammar/Perl5.bnf#L1130). The indentation should be made consistent.

**Comment by hurricup** [comment]
Seems there is no auto-format option in grammar-kit, and it doesn't bothers me enough to fix this manually. Feel free to submit a pull request.
