### ISSUE TITLE
Breakpoints lost when using auto reconnect

### ISSUE THREAD

**Issue by jonas-lindmark** [Camelcade/Perl5-IDEA#2133]
When using the "Perl connects to IDE" mode and allowing automatic reconnects the breakpoint queue is lost. This makes breakpoint debugging impossible on all but the first connection.

The breakpoints in PerlDebugThread.java are managed by a queue sending only updates to the Perl-side debugger module and all previously sent breakpoints are lost. 

My use case is for mod_perl with Apache2::Camelcadedb module that connects the debugger at every http request so the IDE have to keep track of all set breakpoints between reconnects.

I have a working fix for this, will try to post a pull request.

**Comment by hurricup** [comment]
Fixed with 0d98d97
