### ISSUE TITLE
no tooltip of variable value when mouse is hoovering over a variable

### ISSUE THREAD

**Issue by terapackets** [Camelcade/Perl5-IDEA#2135]
I have been using Jetbrain IDE for Java (Intellij), javascript (WebStorm) and C/C++ (Clion). 

I installed perl plugin on my CLion (ver ) running on Ubuntu 19.04, but there is no tooltip about variable value when hoover mouse over a variable.  Wonder if anyone has seen this issue, and if there is a workaround.

**Comment by hurricup** [comment]
Control-hover works fine to me in actual version of the plugin. Please, provide your versions information.

**Comment by hurricup** [comment]
Feel free to re-open when get more details.
