### ISSUE TITLE
Incompatible with IDEA 2020.x

### ISSUE THREAD

**Issue by allter** [Camelcade/Perl5-IDEA#2138]
Looks like something has to be bumped to work with newer IDEA:

```
Plugin Error: The Perl (id=com.perl5, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.5259.13/IntelliJ IDEA 2020.1 EAP.app.plugins/perl5.plugin, version=2019.3) plugin is incompatible (target build range is 193.5233 to 193.*).
```

**Comment by hurricup** [comment]
There is a version for early eaps, but still no versions for actual one. sorry. Should be available soon.

**Comment by hurricup** [comment]
Should be fixed in https://github.com/Camelcade/Perl5-IDEA/commit/c2c0b84a69615f115695d6f96d4cd390e29fec30

Waiting for the CI confirmation and release today.
