### ISSUE TITLE
Passing arguments to test files

### ISSUE THREAD

**Issue by TBSliver** [Camelcade/Perl5-IDEA#2139]
There is currently no way to pass arguments to a test file. One use case is when using `Test::Class::Moose`, where you can pass the specific test class to run, to limit the tests. An example:

```bash
prove -v t/class.t :: TestsFor::MyApp::Controller::Users
```

(Full documentation on this particular use is from [Test::Class::Moose::CLI](https://metacpan.org/pod/Test::Class::Moose::CLI))

There is also an issue with formatting in the test runner when using this module, it seems that the subtest grouping is dependant on `# Subtest: test name` rather than indentation - I cant seem to find the TAP specs for either Subtest or indentation unfortunately... (unsure if this is perl side or IntelliJ IDEA side so putting it here for now)

**Comment by hurricup** [comment]
I'd suggested to rephrase this issue to `Test::Class::Moose` support.
Tree related things are most likely from perl side, but arguments may be passed using https://github.com/Camelcade/App-Prove-Plugin-PassEnv

**Comment by TBSliver** [comment]
Except its not an environment variable. The test file is basically:

```perl
use strict;
use warnings;

use Test::Class::Moose::Load 't/tests';
use Test::Class::Moose::Runner;
Test::Class::Moose::Runner->new( test_classes => \@ARGV )->runtests;
```

Which doesnt use environment vars - The test has (optional) CLI arguments for limiting tests. There is no way in the current interface to pass something that comes after the test name, and adding arbitrary parts after the test name causes an error.

**Comment by hurricup** [comment]
Oh, right. Sorry, my bad

**Comment by hurricup** [comment]
I've added test script parameters to the configuration.
Problem with tests formatting should be filled in here: https://github.com/Camelcade/TAP-Formatter-Camelcade

Feel free to build plugin from sources or wait for the next EAP release (next week). Please note, current releases are compatible with 2020.1 EAP only.

**Comment by TBSliver** [comment]
Ok cool thanks :smile: knowing its coming is good enough as ive got my current 'workarounds' for now (also known as a terminal window :stuck_out_tongue:) I'l go file an issue on TAP Formatter for the other side as I may have an example output at least!
