### ISSUE TITLE
Perl doesn't include lib folder

### ISSUE THREAD

**Issue by thed0ctor** [Camelcade/Perl5-IDEA#2140]
Hello, when I set one of the project directories that include perl code the plugin doesn't seem to show it exists. It doesn't include the lib dirs I mark as Perl5 libraries. It says `Unable to find a package file for baz1::MyModule` What setting do I use to include my package?

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35
Perl Plugin is version 202
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS: macOS 10.15.3
Perl: perlbrew (perl-5.28.0)

**Directory Structure:**

```
.
|____t
|____foo
| |____bar
| | |____baz2
| | | |____example.pl
|____lib
| |____MyModule.pm

```

**example.pl**
```perl
use utf8;
package baz;


use FindBin qw($Bin);
#use lib "$Bin/..";

use baz1::MyModule;

print "Hello";
```

**MyModule.pm**
```perl
package baz1::MyModule;
use strict;
use warnings FATAL => 'all';

print("In baz1::MyModule");

1;
```

![image](https://user-images.githubusercontent.com/3771427/76021249-f395d180-5ef2-11ea-90d9-7e7ae8d7f7eb.png)

**Comment by hurricup** [comment]
as far as i can see, it should not from terminal either. 
`use baz1::something` meaning `to find file baz1/something.pm` in one of the `@INC` folders. There is no such file in your project.

**Comment by thed0ctor** [comment]
That fixed it. Thanks
