### ISSUE TITLE
Method hints do not work on objects returned by helpers

### ISSUE THREAD

**Issue by Wmn** [Camelcade/Perl5-IDEA#2142]
When you use Mojo helper returning an object and try to call a method on return of the helper, IDEA does not provde method hints for the package, only SUPER::.... 

# Example script to reproduce the issue:

```perl
#!/usr/bin/env perl

package Test1;

use feature qw(signatures);
no warnings qw(experimental::signatures);

sub new($class) {
    return bless {}, $class;
}

sub test($self) {
    return 'works';
}

1;

package main;

use feature qw/say/;
use Mojolicious::Lite -signatures;
use Test1;

helper test => sub {
    state $pkg = Test1->new
};

get '/' => sub($c) {
    say $c->test->... # <- Hint is only SUPER here, while there should be the list of methods from Test1 package
};

app->start;
```

# Environment info:
* IntelliJ IDEA 2019.2.1 Build #IC-192.6262.58
* Plugin version 2019.2.4
* openjdk version "1.8.0_222"
* FreeBSD 13.0-CURRENT

**Comment by hurricup** [comment]
Ok. there are two problems here:
1. Plugin don't understand definition with `helper`, but understand with `$self->helper`
2. Plugin don't understand the type of returned declaration. Meaning:
```
# Doesn't work
$self->helper test => sub {
    state $pkg = Test1->new
};

# Works
$self->helper test => sub {
    state $pkg = Test1->new;
    $pkg
};
```

Investigating

**Comment by hurricup** [comment]
I'm afraid this can be fixed only in the next major release.
