### ISSUE TITLE
Plugin "Perl WSL Support" is incompatible (until build 193.SNAPSHOT < IU-201.6668.121)

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2149]
Hi, me again :)

Perl plugin is OK, only WSL support  is not (yet?).

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020

**Comment by hurricup** [comment]
You don't need it anymore. It's included in base plugin along with docker
