### ISSUE TITLE
arrayref dereferences incorrectly uses code block space setting

### ISSUE THREAD

**Issue by todd-richmond** [Camelcade/Perl5-IDEA#2155]
OSX with Intellij 2020.1 and Perl Plugin 2020.1

Reformatting code with "spaces / within / code block" enabled, causes arrary ref dereferences to also get spaces. This is how you can set a caller's argument when performance is critical instead or returning a new array. Disabling the code block option removes the spaces

sub foo($$) {
    ${$_[1]} = 'set_caller_string argument';
}

turns to
${ $_[1] }

**Comment by hurricup** [comment]
The reason is that dereference is applied to the code block actually. 
E.g.
```
${
   my $result = ....
   ....
   \$result
}
```
But this probably should be handled with a separate setting.

**Comment by todd-richmond** [comment]
same issue with @{ and %{ but they can all share the same setting
