### ISSUE TITLE
return ($a, $b) deletes space between return and paren

### ISSUE THREAD

**Issue by todd-richmond** [Camelcade/Perl5-IDEA#2156]
OSX with Intellij 2020.1 and Perl Plugin 2020.1

return ($a, $b) eats the space after return even when return $a does not. No spaces are enabled within parens, but they are enabled before the paren in if/else conditional expressions. I could not find a setting which did not eat the space in this case

output: return($a, $b);

**Comment by hurricup** [comment]
There is none. But you are right, it shouldn't.
