### ISSUE TITLE
Unable to build from source on 3 different systems

### ISSUE THREAD

**Issue by todd-richmond** [Camelcade/Perl5-IDEA#2165]
I am trying to verify your recent fixes for me, but am unable to build on any of 3 completely different systems. ./gradlew buildPlugin creates a zip file that has 2 nearly empty jars in it and so Intellij complains about missing manifest

1) OSX with java 12
2) Centos 6 with java 8
3) Centos 8 with java 11

I do see several of the following errors during build

,
> Task :perl5.transport.wsl:buildSearchableOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to field java.awt.event.InvocationEvent.runnable
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-04-23 16:49:34,445 [   5256]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options

**Comment by hurricup** [comment]
According to README.md: `5. Choose plugin file in the build/distributions directory of the respective plugin root`
There are several plugins here. And each plugin is in it's own build dir, not the topmost one. 
E.g. `plugin/build/...`

**Comment by hurricup** [comment]
And don't worry about this warnings.

**Comment by todd-richmond** [comment]
ah - I was just looking at the toplevel build/distributions. Which of these need to be updated:
```
./build/distributions/perl5-2020.1.1.SNAPSHOT-1.zip
./docker/build/distributions/perl5.transport.docker-2020.1.1.SNAPSHOT-1.zip
./embedded/build/distributions/perl5.lang.embedded-2020.1.1.SNAPSHOT-1.zip
./htmlmason/build/distributions/perl5.lang.mason.htmlmason-2020.1.1.SNAPSHOT-1.zip
./mason-core/build/distributions/perl5.lang.mason.framework-2020.1.1.SNAPSHOT-1.zip
./mason2/build/distributions/perl5.lang.mason.mason2-2020.1.1.SNAPSHOT-1.zip
./mojo/build/distributions/perl5.lang.mojo-2020.1.1.SNAPSHOT-1.zip
./mojo/core/build/distributions/perl5.lang.mojo.core-2020.1.1.SNAPSHOT-1.zip
./mojo/idea/build/distributions/perl5.lang.mojo.idea-2020.1.1.SNAPSHOT-1.zip
./plugin/build/distributions/perl5.plugin-2020.1.1.SNAPSHOT-1.zip
./plugin/core/build/distributions/perl5.core-2020.1.1.SNAPSHOT-1.zip
./plugin/coverage/build/distributions/perl5.core.coverage-2020.1.1.SNAPSHOT-1.zip
./plugin/idea/build/distributions/perl5.core.idea-2020.1.1.SNAPSHOT-1.zip
./plugin/intelliLang/build/distributions/perl5.core.intelliLang-2020.1.1.SNAPSHOT-1.zip
./tt2/build/distributions/perl5.lang.tt2-2020.1.1.SNAPSHOT-1.zip
./wsl/build/distributions/perl5.transport.wsl-2020.1.1.SNAPSHOT-1.zip

```

**Comment by hurricup** [comment]
Some of these are not real plugins, this is a flaw of building system, it builds zips even for internal modules. The main plugin is `./plugin/build/distributions/perl5.plugin-2020.1.1.SNAPSHOT-1.zip`

**Comment by todd-richmond** [comment]
that worked and the bug fixes you did over the last few days work perfectly - thx
You might change the path in the readme to point to just this one zip

**Comment by hurricup** [comment]
I've updated build script to avoid unnecessary zips building. Thanks for pointing on such inconvenience.
