### ISSUE TITLE
RFE: support Copyright formatting

### ISSUE THREAD

**Issue by todd-richmond** [Camelcade/Perl5-IDEA#2168]
Not sure if this is possible to extend in a plugin, but Intellij supports copyright reformatting for Java/HTML/XML... The "Properties" format uses # signs just like Perl so if there was a way to assign that style to .pm files, this might be doable
Reformatting even supports template variables so things like the date can be updated

**Comment by hurricup** [comment]
I'm not sure there is a formatting. It just can update existing copyright with new one. With templates support.

**Comment by todd-richmond** [comment]
yeah - we are talking the same thing. Just want to update the copyright block using the configured text. Intellij intelligently picks the comment format for the file type - i.e. /* or #, but it doesn't seem that Perl is hooked up to use # because it doesn't get updated (unless I'm missing some alternate command?)

**Comment by todd-richmond** [comment]
@hurricup  thx for the amazing responsiveness on this and other issues! Will give it a try soon
