### ISSUE TITLE
Issue with 1251 encoding in *.pm

### ISSUE THREAD

**Issue by almirus** [Camelcade/Perl5-IDEA#2169]
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Non-Bundled Plugins: CMD Support, Lombook Plugin, com.perl5, com.perl5.lang.mason.framework, com.perl5.lang.mason.htmlmason, com.arcbees.plugin.idea, com.jetbrains.plugins.ini4idea, com.intellij.plugins.watcher, me.laria.code.idea_caseconv, MavenRunHelper, ImportCost, izhangzhihao.rainbow.brackets
Perl plugin version 2020.1
JRE - openjdk version "1.8.0_232"
windows 10 (x64)

After plugin update, files (with cp1251) are forced to open in UTF-8 (only *.pm)

![image](https://user-images.githubusercontent.com/16898685/81172600-36356200-8fa7-11ea-99b2-a60bc9e06558.png)
![image](https://user-images.githubusercontent.com/16898685/81172699-654bd380-8fa7-11ea-8452-23534ee87681.png)

**Comment by hurricup** [comment]
Could you please try to do the same with txt files? Plugin should not mess with encoding in any way, so this looks like IDE problem, not plugin's.
Also, some sample to reproduce would be nice to have.

**Comment by almirus** [comment]
hm, seem to be it's IDEA problem, to reproduce:
open project with default project encoding utf8
open another project with default  project encoding cp1251, last opened files will get wrong encoding utf8 :(

**Comment by hurricup** [comment]
you should report it do idea tracker then.
