### ISSUE TITLE
Incorrect "unreachable code" detection in for/when construction inside of a sub

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2176]
This:

![image](https://user-images.githubusercontent.com/754722/82598769-6d149600-9bab-11ea-8e69-f4d067abe52a.png)

Works perfectly (no errors) when on file level (in or outside of a block), but gives an error when used inside of a sub, and only for `die`, anything else also works:

![image](https://user-images.githubusercontent.com/754722/82598876-a1885200-9bab-11ea-9f8c-a65b725298c0.png)

  * IntelliJ Idea 2020.1.1, Win10
  * Perl Plugin 2020.1, perl support level set to 5.16

**Comment by aldem** [comment]
And a bit more, this time with `return` inside of `when`:

![image](https://user-images.githubusercontent.com/754722/82601116-52442080-9baf-11ea-8dbb-e64e6153b69b.png)

Seems that using of `return`/`die` anywhere (but within a sub only) triggers this behavior.

**Comment by hurricup** [comment]
Additionally we need to control when/default outside the topicalizer
