### ISSUE TITLE
Problems with system perl on centos

### ISSUE THREAD

**Issue by targzeta** [Camelcade/Perl5-IDEA#2179]
I have written a little .t file. When I run with Perl5 Test I have:
```
13:25	Missing Packages (Test::Harness)
			Library is necessary to perform an action.
			Install with cpan
			Install Bundle::Camelcade

13:25	Error running 'Tests from 'getpdd.t'': Unable to find prove script for Docker[notifier_notifier:latest], System: Perl 5.10.1
```
but:
```
$> docker run -it notifier_notifier:latest
$> prove --version
TAP::Harness v3.42 and Perl v5.10.1
$> cpanm Test::Harness
Test::Harness is up to date. (3.42)
```

What I'am doing wrong?

Thank you in advance,
Emanuele

**Comment by hurricup** [comment]
Would be nice to have a Dockerfile to reproduce. Looks strange.
Also it's hard to say if  you are really inside the docker by your console. Same prompt.

**Comment by targzeta** [comment]
You can try with this simple Dockerfile:
```
FROM centos:6

RUN yum install -y \
        gcc \
        perl-CPAN \
    && yum clean all

RUN cpan App::cpanminus \
    && cpanm Time::HiRes \
    && cpanm TAP::Formatter::Camelcade \
    && cpanm Bundle::Camelcade \
    && rm -rf /root/.cpan*
```

And with this useless test file:
```
#!/usr/bin/perl
use strict;
use warnings;
use Test::More;

done_testing();
```

Best regards,
Emanuele

**Comment by hurricup** [comment]
You can try to build plugin from master and install it into the current IDEA EAP. 
It should work properly with centos images.

**Comment by targzeta** [comment]
It doesn't seem to work:
![screenshot_20200604_155905](https://user-images.githubusercontent.com/2431105/83769001-9dfecb80-a67f-11ea-9c2b-6c6a07eb443b.jpg)

Do I have to do anything else?

Best regards,
Emanuele

**Comment by hurricup** [comment]
Sorry, yes. You need to open Navigate -> Search everywhere dialog and type `refresh interpreter information` and run it. It will re-sync files and after that it should work.

**Comment by targzeta** [comment]
Yes! It works!

Thank you,
Emanuele

**Comment by hurricup** [comment]
I just pushed re-worked approach for you problem. Would be nice if you could check it too. 
It should be faster.
