### ISSUE TITLE
Syntax error in valid code when using "//" operator after block or hash

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2304]
Strange error in recent update (not sure if it was present in previous versions):

![image](https://user-images.githubusercontent.com/754722/92527446-4e541100-f227-11ea-94a3-1a803a261bc0.png)

Looks like any block followed by `//` is affected. Target perl version is set to 5.16 (but it does not matter), system perl is 5.26.

Perl plugin 2020.2.3, IntelliJIdea 2020.2.1

**Comment by hurricup** [comment]
You can try fixed version from https://github.com/Camelcade/Perl5-IDEA/actions/runs/246821063
