### ISSUE TITLE
NYTPROF profiler with Windows OS is not working 

### ISSUE THREAD

**Issue by bakkiaraj** [Camelcade/Perl5-IDEA#2317]
My environment:

  * IDE name and version, including build: IntelliJ IDEA 2020.2.2 (Ultimate Edition) , Build #IU-202.7319.50, built on September 15, 2020

  * Perl5 plugin version: 2020.2.4

  * JRE version : openjdk-11.0.7+10-x64

  * Your OS name and version: Windows 10, version 1909.

* Perl: perl 5, version 22, subversion 3 (v5.22.3) built for MSWin32-x64-multi-thread , strawberry perl

I tried to profile a simple perl script with NYTProfiler in IDEA IDE. But the profiling step failed with following error,
`
NYTProf set_option: invalid option at C:/tools/Strawberry/perl/site/lib/Devel/NYTProf/Core.pm line 48.
`
Then I try to debug more and then print the variables in NYTProf/Core.pm , line 48. Here is the output,

`
C:/tools/Strawberry/perl/bin/perl.exe -II:/perltest/src/test/perlscripts/lib -d:NYTProf -d:NYTProf I:/perltest/src/test/perlscripts/test.pl

 *********** [stmts] , [0]
 *********** [calls] , [2]
 *********** [savesrc] , [0]
 *********** [slowops] , [1]
 *********** [addpid] , [1]
 *********** [file] , [C]
NYTProf set_option: invalid option at C:/tools/Strawberry/perl/site/lib/Devel/NYTProf/Core.pm line 48.
Compilation failed in require at C:/tools/Strawberry/perl/site/lib/Devel/NYTProf.pm line 26.
Compilation failed in require.
BEGIN failed--compilation aborted.
 *********** [] , []
`

NYTprofiler works well in normal perl run. I think the issue is the way the perl plugin set the "NYTPROF" environment variable.

Ex: I printed the NYTPROF variable 

`
 NYTPROF ENV is stmts=0:calls=2:savesrc=0:slowops=1:sigexit=1:addpid=1:file=C:\Users\xxxx\AppData\Local\JetBrains\IntelliJIdea2020.2\profiling\perltest_Local__System__Perl_5_22_3_NYTProf_test_pl\nytprof.out:start=begin
`

In windows OS, "C:" is the drive name. ":" is used in the NYTProf/Core.pm as a delimiter to parse the variable data. So perl plugin should not pass "file" option with driver letter. it can only pass , like "./test_pl.out" or leave it to default.

**Comment by hurricup** [comment]
Thank you for your investigation! 
This looks like  real problem. We can't leave default path and can't use relative one. 
I'll check what can be done here.

**Comment by hurricup** [comment]
Seems `Any colon or equal characters in a value can be escaped by preceding them with a backslash.`

**Comment by hurricup** [comment]
You may try plugin from https://github.com/Camelcade/Perl5-IDEA/actions/runs/278660322 after tests will pass. 
This plugin requires IDEA 2020.3 EAP, i'll backport it to 2020.2 if everything will work fine.

**Comment by bakkiaraj** [comment]
Thanks for super fast fix. I think the windows PATHs also needs escape.

To verify your fix, I have added following code in C:/tools/Strawberry/perl/site/lib/Devel/NYTProf/Core.pm
`
....
$NYTPROF =~s/\\/\\\\/g; #convert single slash to double slash 
$NYTPROF =~s/:file=(\w):/:file=$1\\:/; #escape drive letter colon with slash 
print("\n NYTPROF ENV is $NYTPROF");

....

print "\n *** [$opt] , [$val]";
DB::set_option($opt, $val);
`

Here is the output,
`
 NYTPROF ENV is stmts=0:calls=2:savesrc=0:slowops=1:sigexit=1:addpid=1:file=C\:\\Users\\xxxx\\AppData\\Local\\JetBrains\\IntelliJIdea2020.2\\profiling\\test_Local__System__Perl_5_22_3_NYTProf_sha256padtest_pl\\nytprof.out:start=begin
 *** [stmts] , [0]
 *** [calls] , [2]
 *** [savesrc] , [0]
 *** [slowops] , [1]
 *** [addpid] , [1]
 *** [file] , [C:\Users\xxxx\AppData\Local\JetBrains\IntelliJIdea2020.2\profiling\test_Local__System__Perl_5_22_3_NYTProf_sha256padtest_pl\nytprof.out]
 *** [start] , [begin]

`
With this , Profiler executed fine and the results are shown in beautifully in the Idea IDE :)

**Comment by hurricup** [comment]
Actually according to nytprof docs you don't need to do anything It should just work with escaped colons https://metacpan.org/pod/Devel::NYTProf#NYTPROF-ENVIRONMENT-VARIABLE

**Comment by bakkiaraj** [comment]
When I dont do the windows path correction with one more additional  "\", Single slash is acting as a escape character.

See the log,

 NYTPROF ENV is stmts=0:calls=2:savesrc=0:slowops=1:sigexit=1:addpid=1:file=C\:\Users\xxxxxx\AppData\Local\JetBrains\IntelliJIdea2020.2\profiling\tst_Local__System__Perl_5_22_3_NYTProf_sha256padtest_pl\nytprof.out:start=begin
 *** [stmts] , [0]
 *** [calls] , [2]
 *** [savesrc] , [0]
 *** [slowops] , [1]
 *** [addpid] , [1]
 *** [file] , [C:UsersxxxxAppDataLocalJetBrainsIntelliJIdea2020.2profilingHelloCrypto_Local__System__Perl_5_22_3_NYTProf_sha256padtest_plnytprof.out]
NYTProf failed to open 'C:UsersxxxxAppDataLocalJetBrainsIntelliJIdea2020.2profilingHelloCrypto_Local__System__Perl_5_22_3_NYTProf_sha256padtest_plnytprof.out.15524' for writing, error 13: Permission denied at C:/tools/Strawberry/perl/site/lib/Devel/NYT
Prof.pm line 44.
Compilation failed in require.
BEGIN failed--compilation aborted.
 *** [start] , [begin]

This fails due to directory path is not set correct. Either to use unix path in "file" option , Or use windows path with "\\".

**Comment by hurricup** [comment]
Please, try this build https://github.com/Camelcade/Perl5-IDEA/actions/runs/280099494

**Comment by hurricup** [comment]
Can you confirm?
