### ISSUE TITLE
Handling of colons (typing assistance nightmare)

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2322]
It is impossible to type something like `$::var` - i.e. it shows the second colon but immediately removes it, possible workarounds are either to insert another character before second colon and then delete it. Problem occurs also with other sigils (`%` and '@`), including weird case when there is a space after them (including interpolated strings - though not for `%`).

Additional annoyance is that typing double colons (when referring to variable - `$boo::`) and then using backspace erases both of them - always, everywhere - in code and (interpolated) strings, so to enter just one you have to split them (or delete one), even worse - typing more than two is impossible at all.

Perl plugin 2020.2.4, IntelliJ IDEA 2020.2.3 (Ultimate Edition) Build #IU-202.7660.26, built on October 6, 2020

**Comment by hurricup** [comment]
you can turn that off in settings -> smartkeys But described issues need to be addressed, thank you..
