### ISSUE TITLE
Barewords with colons in `no strict` mode

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2323]
Perl allows barewords like `abc::def => 0` but those are interpreted as sub calls in specified namespace even when there is no `use strict` (or explicit `no strict`).

Perl plugin 2020.2.4, IntelliJ IDEA 2020.2.3 (Ultimate Edition) Build #IU-202.7660.26, built on October 6, 2020

**Comment by hurricup** [comment]
plugin always works in strict mode. there are few hacks for additional syntax, but if there any ambiguity - always strict.
