### ISSUE TITLE
Missing package (CPAN) where installing packages with cpan.

### ISSUE THREAD

**Issue by lvorobyov** [Camelcade/Perl5-IDEA#2325]
I'm trying to install cpan package thought IDE CLion. When I click on "install with cpan" button, popup "Missing package (CPAN)" appears.

![Снимок экрана_2020-11-20_16-43-00](https://user-images.githubusercontent.com/27832825/99806790-92c92a80-2b4f-11eb-8c25-2248e39d2443.png)

OS: Mojolicious XFCE latest version.
IDE: CLion 2020.2
Plugin version is 2020.2.4

**Comment by hurricup** [comment]
What OS and Perl/version manger is in use?

**Comment by lvorobyov** [comment]
The perl 5, version 32, subversion 0 (v5.32.0) built for x86_64-linux-thread-multi
I'm using Manjaro 20.2 XFCE

**Comment by hurricup** [comment]
Please, see https://github.com/Camelcade/Perl5-IDEA/issues/2141#issuecomment-614470333

**Comment by lvorobyov** [comment]
Thank you for the hint. I created symbolic link to cpan in /usr/bin/ directory and plugin seems to work fine.
