### ISSUE TITLE
Docker command: reset the ENTRYPOINT

### ISSUE THREAD

**Issue by targzeta** [Camelcade/Perl5-IDEA#2326]
Hi,
when the plugin is searching for the perl5 interpreter, I see it runs:
```bash
docker run --rm -i -a stdout -a stderr -a stdin -v /home/targzeta/.local/share/JetBrains/IntelliJIdea2020.3/perl5.plugin/perl:/intellijperl/home/targzeta/.local/share/JetBrains/IntelliJIdea2020.3/perl5.plugin/perl -v /home/targzeta/.cache/JetBrains/IntelliJIdea2020.3:/intellijperl/home/targzeta/.cache/JetBrains/IntelliJIdea2020.3 docker_image:latest sh /intellijperl/home/targzeta/.cache/JetBrains/IntelliJIdea2020.3/tmp/dockerWrapper328
```
but if the image has an entrypoint that it's, for example, a daemon, the previous command never ends. I suggest to reset the entrypoint with this command line option:
```bash
--entrypoint ""
```
Nevertheless, I think we have to add this option everywhere we need to run this type of images.

Best regards,
Emanuele

**Comment by hurricup** [comment]
Do you know that there is a per-project argument for a docker-based perl interpreter? You may use this for your purposes.

**Comment by targzeta** [comment]
Hi,
yes, I know. But actually I'm unable to select the perl interpreter from my docker image. The plugin is waiting forever:
![screenshot_20201123_222247](https://user-images.githubusercontent.com/2431105/100017907-e354b800-2ddb-11eb-82a0-1404c7d25170.jpg)

You can try by yourself with this simple Dockerfile:
```
FROM perl:5
ENTRYPOINT ["sh", "-c", "sleep 900"]
```

The plugin runs a docker container like this (`docker ps --no-trunc`):
```
cdbb0df95d3f8355f7a546a48143d1afc6f97cd4c4dfce7879b63a35dfdcce88   test:latest                  "sh -c 'sleep 900' sh /intellijperl/home/targzeta/.cache/JetBrains/IntelliJIdea2020.3/tmp/dockerWrapper225"   9 seconds ago        Up 7 seconds                                                             recursing_khayyam
```

Emanuele

**Comment by hurricup** [comment]
Please, try plugin from https://github.com/Camelcade/Perl5-IDEA/actions/runs/380724050 (artifacts should be available after testing)

Please, note that entry point reset for internal commands only, but not for command lines from run configurations, because this may affect user's workflow. To reset entrypoint in run configurations you should specify additional arguments for docker sdk.

**Comment by targzeta** [comment]
Hi,
with this artifact I can select the perl interpreter. But, when I add `--entrypoint=""` on "Docker parameters", it shows this "Docker command":
```
docker run --rm -i -a stdout -a stderr -a stdin --entrypoint=\"\" <project_and_helpers_volumes> <image_name> sh <shell_script_with_commands>
```
And, when I try to debug my code, I have this error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"\\\"\\\"\": executable file not found in $PATH": unknown.
```
It seems that it tries to quote the arguments. Changing the double quote character in a single quote character doesn't seem to help. What if you add a flaggable options?

Thank you in advance,
Emanuele

**Comment by hurricup** [comment]
There is some quotation problem, not quite sure what exactly. Use `--entrypoint=` as additional sdk argument.

**Comment by targzeta** [comment]
It works!

Thank you a lot!
Emanuele

**Comment by hurricup** [comment]
Thank you!

**Comment by hurricup** [comment]
Looks like this `""` is handled by bash, because when i'm running script:
```
use strict;
use warnings FATAL => 'all';
use v5.10;

say @ARGV;
```
with `perl ./test.pl --entrypoint=""`
I see
```
--entrypoint=
```
as result. Quotes are not passed to a script. This is something new I didn't know about shell behavior.

So when we starting process from java, we should use `--entrypoint=` to pass empty parameter. I can't handle this automatically, because someone may want to pass quotes.

**Comment by targzeta** [comment]
If you want to pass single or double quote as an argument in bash, you have to quote. Like this:
```
$> perl ./test.pl --entrypoint='""'
--entrypoint=""
```
I think it could be better to add a checkbox for resetting the entrypoint. But your solution works fine anyway.

Emanuele

**Comment by hurricup** [comment]
I'll think about it, thanks again!
