### ISSUE TITLE
In Webstorm the perl debugger disconnects before running any code

### ISSUE THREAD

**Issue by BernieSnoek** [Camelcade/Perl5-IDEA#2327]
# CLICK PREVIEW TAB ^^
1. This repository is for IDE part of perl plugin. Perl-side debugger issues should be posted to the [debugger tracker](https://github.com/hurricup/Perl5-IDEA-Debugger/issues).
2. Before reporting a feature request, please check out our [Wiki](https://github.com/hurricup/Perl5-IDEA/wiki)
3. Before reporting a bug, please, check [known issues](https://github.com/hurricup/Perl5-IDEA/wiki/Known-issues) and [syntax nuances](https://github.com/hurricup/Perl5-IDEA/wiki/Perl-syntax-nuances) sections.
4. Try to search in issues, may be someone already reported your one and you may clarify something or provide more information.
5. When reporting a bug, please, provide as more information as you can. Working example reproducing an error may really speed things up.
6. Make sure that problem still occurs with actual version of the IDE. (see [JetBrains site](https://www.jetbrains.com/))
7. Make sure that problem still occurs with actual version of the Perl plugin. (see [Plugins Repository](https://plugins.jetbrains.com/plugin/7796))
8. At least provide following information:
  * IDE name and version, including build, (e.g. `#IU-143.2370`, available in `Help: About` menu)
  * Perl5 plugin version (available in `File: Settings: Plugins` menu)
  * JRE version (e.g. `Oracle 1.8.0_91-b14`, see `java --version`)
  * Your OS name and version
9. Before posting an issue, please, remove this text. Thank you!

**Comment by hurricup** [comment]
please, remove template and fill necessary data

**Comment by BernieSnoek** [comment]
Hi Alexandr,
Thanks for your prompt reply. I have resubmitted with the information required and some logging and console output, hope this gives you a clue.

All the best
Bernie Snoek

**Comment by hurricup** [comment]
This IDE and plugin version are 4.5 years old. Please, use the most recent version.

**Comment by BernieSnoek** [comment]
Hi Alexandr,

There is console output, I did include it in the original report but here it is again.



Disconnected

/usr/bin/perl5.28 -d:Camelcadedb /Users/berniesnoek/Development/McLane/QuickAttachateToTTWin.pl



WARNING: This version of perl is included in macOS for compatibility with legacy software.

In future versions of macOS the perl runtime will not be available by

default, and may require you to install an additional package.





Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

When I run the command in terminal I get the following

 ~ /usr/bin/perl5.28 -d Camelcadedb /Users/berniesnoek/Development/McLane/QuickAttachateToTTWin.pl



WARNING: This version of perl is included in macOS for compatibility with legacy software.

In future versions of macOS the perl runtime will not be available by

default, and may require you to install an additional package.



Can't open perl script "Camelcadedb": No such file or directory



Access to the project could be difficult, but I get the same result if I try to debug a “Hello World” application.



Hope there are some clues here



Bernie

**Comment by hurricup** [comment]
Please, keep your answers consistent. You've created issue in the debugger repo, so comment there, not here. https://github.com/Camelcade/Devel-Camelcadedb/issues/52
Also, ran incorrect command line.
