### ISSUE TITLE
Add support for async subs as anonymous expressions

### ISSUE THREAD

**Issue by akarelas** [Camelcade/Perl5-IDEA#2333]
This appears well on the IDE:
```perl
async sub foo {
    # ...
}
```

But this does not:
```perl
{
    my $s = async sub {
        # ...
    };
}
```

![async](https://user-images.githubusercontent.com/423822/104992259-53bd3580-5a29-11eb-8c75-d9452ee2de20.png)0

IDE name and version: 2020.3.1 #WS-203.6682.155
Perl5 plugin version: 203.5784.10-EAP-SNAPSHOT
JRE version: The `java` binary doesn't exist on my system (?)
OS name and version: Ubuntu 20.04

**Comment by hurricup** [comment]
IDE supports `Future::AsyncAwait` according to it's documentation irr.
And it says nothing about anon subs with `async` modifiers. Is this some other module?

**Comment by akarelas** [comment]
It's from Future::AsyncAwait as well. Let me ask the author and I'll return with his answer.

**Comment by leonerd** [comment]
Hi - turns out perhaps I forgot to mention them in the docs. They're tested quite a bit in the unit tests, and in practice we use those all over the place. I'll add a mention to the docs.

**Comment by hurricup** [comment]
@leonerd thank you. Will update support then.
