### ISSUE TITLE
perlbrew executable file not showing

### ISSUE THREAD

**Issue by phastat** [Camelcade/Perl5-IDEA#2337]
System information:
OS: Ubuntu 20.04.2
I'm using the built in JRE with Intellij:
```
Build #IU-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-41-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1923M
Cores: 8
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea, de.netnexus.camelcaseplugin, dev.meanmail.plugin.nginx-intellij-plugin, org.jetbrains.plugins.go-template, com.intellij.kubernetes, com.perl5, com.dmarcotte.handlebars, org.jetbrains.kotlin, Pythonid, ru.meanmail.plugin.requirements, org.jetbrains.plugins.go
Current Desktop: ubuntu:GNOME
```

Perl5 Plugin version: 203.5784.10-EAP-SNAPSHOT

To reproduce the issue simply try to add an executable and it won't show. Adding it as a system perl works fine but not as a perlbrew executable, see screenshots below
![image](https://user-images.githubusercontent.com/78865248/107531653-0f860680-6b8b-11eb-90ba-babad4a9b299.png)

and example of it working as system perl:
![image](https://user-images.githubusercontent.com/78865248/107532164-989d3d80-6b8b-11eb-9be2-da844d607c8e.png)

**Comment by hurricup** [comment]
Is it properly named and have `x` permission?

**Comment by phastat** [comment]
It has the `x` permission and is named `perl` which I believe is correct?

**Comment by phastat** [comment]
Figured it out. Was using the wrong exe. Needed to pick the "perlbrew" binary. My bad.
