### ISSUE TITLE
Indentation of multiline chained map grep sort etc.

### ISSUE THREAD

**Issue by jonas-lindmark** [Camelcade/Perl5-IDEA#2338]
When using functional style chained array operations like in the examples below the current formatter implementation inserts extra indentation for every new line. This is not so easy to read and a bit distracting in my opinion.

This is what I would prefer:
```perl
my @prime_twins = map { [ $_ - 2, $_ ] }
    grep { is_prime($_) }
    map { $_ + 2 }
    grep { is_prime($_) }
    (3 .. 100);
```

And this is what is produced currently:
```perl
my @prime_twins = map { [ $_ - 2, $_ ] }
        grep { is_prime($_) }
            map { $_ + 2 }
                grep { is_prime($_) }
                    (3 .. 100);
```
As a comparison this is how Perl::Tidy will format the same code:
```perl
my @prime_twins = map { [ $_ - 2, $_ ] }
  grep { is_prime($_) }
  map  { $_ + 2 }
  grep { is_prime($_) } ( 3 .. 100 );
```

**Comment by jonas-lindmark** [comment]
I did have a go at this and think I got it working by adding a bit of logic to PerlIndentProcessor.java, can post a PR if this would be considered adding to the plugin :-)

**Comment by hurricup** [comment]
Yep, this may be a good feature. Still, technically formatter is right, because each next map/grep/sort is an argument for the previous one and should be indented. 
Still, it's really unfriendly.

**Comment by hurricup** [comment]
Ok, let's formalize it like this:
we need an option to align all the rightward list expressions (but not their arguments).
Meaning with option enabled we should have:
```
method1 {}
    method2 $var1, 
        $var2, 
    method3 {something}
    grep {...} 
    map {...}
    method4
         $var3, $var4,
    method5 @ARGV;
```
