### ISSUE TITLE
Perl modules on MacOS not detected by XS deparser

### ISSUE THREAD

**Issue by miken32** [Camelcade/Perl5-IDEA#2364]
PhpStorm 2021.1.1 Build #PS-211.7036.8, built on April 15, 2021
Perl plugin 2021.1
java 13.0.2 2020-01-14
macOS 11.2.3
Perl 5.28.3 installed via MacPorts

I never received [a prompt ](https://github.com/Camelcade/Perl5-IDEA/issues/1576#issuecomment-617873987)to run the xsubs deparser script – not sure if that's a separate issue or not. When I ran it manually, it listed very few things.

My binary modules are mostly `.bundle` files and look to be skipped over by the deparser script as a result. The regular expression [at the beginning of the script ](https://github.com/Camelcade/Perl5-IDEA/blob/master/plugin/scripts/xs_parser_simple.pl#L10)should be changed to include these files as well.

```
$ perl -V
Summary of my perl5 (revision 5 version 28 subversion 3) configuration:
...
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.16 -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk  -fstack-protector-strong'
...
  @INC:
    /opt/local/lib/perl5/site_perl/5.28/darwin-thread-multi-2level
    /opt/local/lib/perl5/site_perl/5.28
    /opt/local/lib/perl5/vendor_perl/5.28/darwin-thread-multi-2level
    /opt/local/lib/perl5/vendor_perl/5.28
    /opt/local/lib/perl5/5.28/darwin-thread-multi-2level
    /opt/local/lib/perl5/5.28

$ file /opt/local/lib/perl5/site_perl/5.26/darwin-thread-multi-2level/auto/Digest/SHA/SHA.bundle
/opt/local/lib/perl5/site_perl/5.26/darwin-thread-multi-2level/auto/Digest/SHA/SHA.bundle: Mach-O 64-bit bundle x86_64
```

Note, the built-in version of Perl (also 5.28) has similar build flags and also uses `.bundle` as an extension for binary modules. Once I updated the regex to `dll|so|bundle` and piped the output into the appropriate file, all the undefined sub errors went away.

**Comment by hurricup** [comment]
Thanks!
