### ISSUE TITLE
It doens't know the subs `_set`, `has_`, `trigger_`, `build_` and `clear_`. 

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2370]
It doens't know the subs `_set`, `has_` and `clear_`. See this attachment, it should be clearer.
![screenshot_20210511_161607](https://user-images.githubusercontent.com/2431105/117831326-bd7d7b80-b274-11eb-85d9-451ec5d4580a.jpg)

_Originally posted by @targzeta in https://github.com/Camelcade/Perl5-IDEA/issues/2352#issuecomment-838565716_

We need to test references and find usages

**Comment by hurricup** [comment]
`trigger` does not create a sub, it creates an implicit sub call

**Comment by hurricup** [comment]
`builder` and `lazy` do not produce additional subs, just invocations.

**Comment by hurricup** [comment]
@targzeta please, try build from https://github.com/Camelcade/Perl5-IDEA/actions/runs/850273590 after tests passed

**Comment by hurricup** [comment]
You probably need to invalidate caches though

**Comment by targzeta** [comment]
It worked :+1: 

Thank you very much @hurricup!

Emanuele
