### ISSUE TITLE
Formatting, variable definition, align equals sign

### ISSUE THREAD

**Issue by leobm** [Camelcade/Perl5-IDEA#2405]
Hi,

I don't know if this is possible, probably it is complicated to format it automatically. But that would be a feature I would really like to have.

For example, if I have several variables definitions.
e.g.
```
    my $var1 = 1;
    my $var100 = '';
    my $var1000 = undef;
```

then I would like to have the possibility to define the formatting so that the equal sign after the variable all are moved to the same column. So for example, like this:

```
    my $var1    = "";
    my $var100  = '';
    my $var1000 = undef;
```
is this theoretically possible?

Edit:
Oh, I also often use the #@type annotations.
Would be nice if they could be between the variable definitions and the formating still works.

many greetings 

Jan-Felix

**Comment by hurricup** [comment]
This is practically possible: 

![image](https://user-images.githubusercontent.com/2811330/124123904-79427680-da80-11eb-8c2b-c5997b2edc42.png)

Please, don't mix multiple requests in the single issue. Start another for types and provide an example of what do you mean.

**Comment by leobm** [comment]
cool, I didn't know that...thanks

**Comment by leobm** [comment]
I still have a problem with the formatting and the recognition of the function parameters.

For example, if I have the following function signature
```
sub Initialize {
 
    my $param_sNodeID = shift;
    #@type MediaCluster::Service::DatabaseConnections
    my $param_objDBConnections = shift;

....
```
The problem is the type annotation (or comment).
$param_sNodeID is still recognized as parameter, $param_objDBConnections 
but not anymore. Further disadvantage, in the Structure View (IntelliJ) the second parameter is not recognized either. 

![bild](https://user-images.githubusercontent.com/25712/124438931-164f2900-dd79-11eb-928f-f5c3251fac6e.PNG)


Yes, I know, I can also write the type in front of the variable in Perl:
`my MediaCluster::Service::DatabaseConnections $param_objDBConnections = shift;`
But I don't find that very readable.

is there anything I can do?

regards,

Jan-Felix

**Comment by hurricup** [comment]
Nope, but this looks like a valid point for improvement.
