### ISSUE TITLE
Error parsing valid code

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2409]
```
sub push_to_db {
    my ($self) = @_;

    while ( defined(my $username = <$self->{input}>) ) {
        chomp $username;
        say $username;
    }
}
```

**Comment by maximusfox** [comment]
It's not a parser, it's Perl.

This works fine:
```
sub push_to_db {
    my ($self) = @_;

    while ( defined(my $username = readline($self->{input})) ) {
        chomp $username;
        say $username;
    }
}
```
Problem in symbol ">". This symbol appears twice.
`while ( defined(my $username = <$self->{input}>) ) {`

**Comment by hurricup** [comment]
It's not valid. 
> If what's within the angle brackets is neither a filehandle nor a simple scalar variable containing a filehandle name, typeglob, or typeglob reference, it is interpreted as a filename pattern to be globbed, and either a list of filenames or the next filename in the list is returned, depending on context.
