### ISSUE TITLE
Can't choose Alpine base docker images for Perl Interpreter

### ISSUE THREAD

**Issue by brneor** [Camelcade/Perl5-IDEA#2415]
In `Settings > Languages & Frameworks > Perl 5 > Perl 5 Interpreter` trying to choose any alpine based image results in an empty "Choose a Perl5 Executable File" box:

![image](https://user-images.githubusercontent.com/5962898/127703526-84cb3536-c237-4ff2-8cb6-4b0b6f736758.png)

I do not have the same issue when choosing eg. Fedora or Ubuntu based images. Does the plugin need a specific command to run inside the container? If so, which one?

Running Perl5 Plugin version 2021.2 on

```
WebStorm 2021.2
Build #WS-212.4746.80, built on July 23, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2016M
Cores: 12
Non-Bundled Plugins: com.github.patou.gitmoji (1.8.0), zielu.gittoolbox (212.6.6), ua.in.dej.myEmmet (1.2.5), com.perl5 (2021.2), com.perl5.lang.mojo (2021.2)
```

**Comment by hurricup** [comment]
IDE logs could be helpful for you and for me :) Please, zip and attach your logs folder. Or send it to my email hurricup at gmail

**Comment by hurricup** [comment]
Is this your report? https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-3453

**Comment by brneor** [comment]
> 
> 
> Is this your report? https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-3453

Yep, looks like my report! (I didn't knew I sent it)

Looks like the issue is caused by `classify` option to `ls` command provided by BusyBox, right? I'm going to try a workaraound. Ty very much! 😃

**Comment by brneor** [comment]
Installing `coreutils` did the trick for now.
