### ISSUE TITLE
Reformat code as action on save doesn't work

### ISSUE THREAD

**Issue by gpassero** [Camelcade/Perl5-IDEA#2429]
## Issue

I've enabled the option to reformat code on save and I noticed that doesn't seem to work for me. 

I'm sharing below some screen shots of how I've enabled that setting and how a sample code looks after I save it (with "Save Document" action) and how it looks after I reformat it with a manual trigger of the "Reformat Code" action. 

Enabling auto code reformat at Settings > Tools> Actions on Save
![action on save - reformat code is on](https://user-images.githubusercontent.com/4478523/137744821-65801fae-761e-43c3-83fd-a63aaef65763.png)

Code after triggering "Save Document"
![after save and before manual reformat](https://user-images.githubusercontent.com/4478523/137744860-c714b2d4-2317-4477-8e08-f32b3b29b5c8.png)

Code after manually trigger "Reformat Code"
![after manual reformat](https://user-images.githubusercontent.com/4478523/137744872-8c4e512a-3fec-48a7-b883-320a1c6d3b46.png)

As you can see, the code looks different, but shouldn't it look the same considering reformat automatically on save is enabled?

## Environment

**IDE name and version**
Build #IU-212.5457.46, built on October 12, 2021

**Perl5 plugin version**
2021.2 - Sep 25, 2021

**JRE version**
openjdk 11.0.12 2021-07-20 LTS

**OS**
macOS Big Sur Version 11.6

**Comment by hurricup** [comment]
Does it work with other languages? It seems that this does not require any efforts from the plugin, ide should invoke existing reformatter on save.
