### ISSUE TITLE
If I exclude `local/` then installed modules and their exported symbols are not found.

### ISSUE THREAD

**Issue by akarelas** [Camelcade/Perl5-IDEA#2436]
**IDE: WebStorm #WS-213.5744.224
Perl v5.34.0**

I can choose to exclude or not exclude the `local/` directory that Carton creates, which contains all the CPAN dependencies of my project.

If I don't exclude it, then when I do a full search for a string, those CPAN modules are also searched and lines are returned from them.

If I exclude it, I get markings that the module I `use` could not be found, and neither can their exported symbols.

Both options are bad.

Isn't there a way to exclude `local/` from search, but not get markings if the CPAN modules are present in any of the directories which I marked as being "Perl5 library root"? Maybe by playing with `_Deparsed_XSubs.pm`?

Thank you.

**Comment by hurricup** [comment]
This is interesting case. This is not probably possible out of the box. But you can define a scope which excludes local/ directory and restrict your search with it.

**Comment by hurricup** [comment]
Could you please provide me with reproduction steps. how to set up a sample project?

**Comment by hurricup** [comment]
This should work in 2023.1
