### ISSUE TITLE
Plugin doesn't recognize importing with `qw`

### ISSUE THREAD

**Issue by dims12** [Camelcade/Perl5-IDEA#2437]
Perl plugin doesn't recognize importing with `qw`, for example

```
use My::Package qw(
   my_function
);

```
then `my_function` below won't be known.

Actual for plugin 2021.2 within IntelliJ IDEA.

**Comment by hurricup** [comment]
How export is done in My::Package?

**Comment by hurricup** [comment]
Please, feel free to get back when have more details. Some real life example would be nice. Things depends on how export being done.
