### ISSUE TITLE
After updating  to version 2021.3 the IDE is no longer connecting to Perl debugger

### ISSUE THREAD

**Issue by deresov** [Camelcade/Perl5-IDEA#2438]
I updated IDE and Perl plugin to the latest version (2021.3). After that, the IDE will no longer connect to Perl debugger, it just repeats "Waiting for process to start..." until terminated.
This seems to be similar to issue #2237

>C:/Strawberry/perl/bin/perl.exe -d:Camelcadedb D:/work/ptest/test.pl
>Listening for the IDE connection at 0.0.0.0:64442...
Waiting for process to start...
Waiting for process to start...
Waiting for process to start...
Waiting for process to start...
Waiting for process to start...
Waiting for process to start...
Terminating on signal SIGINT(2)
>
>Process finished with exit code 2
>Disconnected

The Perl process is running and is listening on the right port:

>netstat -a -b
> ...
>  TCP    0.0.0.0:64442          LAPTOP-XXXXXXX:0      LISTENING
 [perl.exe]
...

Environment:

- Windows 10 (Version 10.0.19044 Build 19044)
- IntelliJ IDEA 2021.3 (Ultimate Edition) Build #IU-213.5744.223, built on November 27, 2021
- Perl Plugin version 2021.3
- JRE version: 11.0.13+7-b1751.19 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- Perl Interpreter: Strawberry Perl "This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread"
- Devel::Camelcadedb          v2021.2  2021.200  HURRICUP/Devel-Camelcadedb-v2021.2.tar.gz

I doesn't seem to matter if I run the script directly or using run configuration. It also doesn't matter if breakpoints are set or not.
I am able to duplicate the problem on another machine with similar configuration.

**Comment by hurricup** [comment]
Is there a chance that you have some antivirus/firewall and and gave permission to connect to the old IDE version? 
Because this release is mostly maintenance and not much changed since the last verision.

**Comment by deresov** [comment]
This machine is running default Windows Defender firewall and antivirus only. No additional third party AV.

I checked firewall rules:

IDEA
“C:\users\ME\appdata\local\jetbrains\toolbox\apps\idea-u\ch-0\213.5744.223\bin\idea64.exe” (verified that this is the one I am running)
Is allowed through on both public and private networks.

Perl Interpreter
“C:\strawberry\perl\bin\perl.exe”
Is also allowed on both public and private networks.

There were rules for older versions of IDEA but all of them were allowed.

I also tried installing the plugin into PyCharm to see if this issue was specific to IDEA, but the results were the same.

**Comment by hurricup** [comment]
Not sure what can I do here. Most likely it some security(???) measure on your side.
Works like a charm for me:
![image](https://user-images.githubusercontent.com/2811330/147411525-c42bae51-d50a-4692-8d63-5cfc1fc9fbaf.png)

**Comment by bobgeorge1st** [comment]
I have exaxctly the same problem. In the IDEA an also in the command line:
![image](https://user-images.githubusercontent.com/97881652/149746906-10255001-2169-489b-83ee-280259320be9.png)

Environment:
Windows 11 Home 21H2
IntelliJ IDEA 2021.3.1
Perl Plugin version 2021.3
perl 5, version 24, subversion 1 (v5.24.1) built for MSWin32-x86-multi-thread-64int

I have only Windows Firewall an AV, I also tried it with deactivated fireall, but no zhere was no improvement

**Comment by hurricup** [comment]
@bobgeorge1st sorry, your terminal screenshot is not enough. What ide does at this moment? What run configuration is used?

**Comment by bobgeorge1st** [comment]
Ok, sorry. I started a simple "Hello World!"-script on the Windows command line:
![image](https://user-images.githubusercontent.com/97881652/149774273-dc536ea7-6a75-449d-83e4-01c9614bfc9a.png)
The environment variables are set as follows:
PERL5_DEBUG_HOST=0.0.0.0
PERL5_DEBUG_PORT=51629
PERL5_DEBUG_ROLE=client

**Comment by hurricup** [comment]
@bobgeorge1st and what is going on on IDE side?

**Comment by hurricup** [comment]
btw for local cases you should not do this. Idea should be able to run scripts by itself.

**Comment by hurricup** [comment]
This is interesting.
Can you pull the repo and run from sources?
I can see in the code where are we stuck, but can't say why. 
Also, you may try to open 'Debug log settings' action and put in there `#com.perl5.lang.perl.debugger.run.run.debugger.PerlDebugProfileState`, then reproduce and see `DEBUG` messages in the log.

This is logic that handles this: https://github.com/Camelcade/Perl5-IDEA/blob/master/plugin/debugger/src/com/perl5/lang/perl/debugger/run/run/debugger/PerlDebugProfileState.java#L57

**Comment by bobgeorge1st** [comment]
Hm, I don't know how to run it from source, but I edited the "Debug log settings". Here is the output:

2022-01-18 10:20:29,948 [  35558]  DEBUG - debugger.PerlDebugProfileState - system: C:/Strawberry/perl/bin/perl.exe -IC:/Users/XXX/IdeaProjects/perl/lib -d:Camelcadedb C:/Users/XXX/IdeaProjects/perl/test/test.pl
 
2022-01-18 10:20:29,956 [  35566]  DEBUG - debugger.PerlDebugProfileState - stdout: [2J[m[HListening for the IDE connection at 0.0.0.0:53206...
]0;C:\Strawberry\perl\bin\perl.exe[?25h 
2022-01-18 10:20:30,575 [  36185]  DEBUG - debugger.PerlDebugProfileState - stdout: [?25l[8;21;228t[HListening for the IDE connection at 0.0.0.0:53206...[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[2;1H[?25h 
2022-01-18 10:20:37,603 [  43213]  DEBUG - debugger.PerlDebugProfileState - stdout: Terminating on signal SIGINT(2)
 
2022-01-18 10:20:37,742 [  43352]  DEBUG - debugger.PerlDebugProfileState - system: 
Process finished with exit code 2

**Comment by hurricup** [comment]
Oh, seems tty is there.... interesting.

**Comment by bobgeorge1st** [comment]
I have no idea.

**Comment by hurricup** [comment]
Ok, seems the reason is https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/
It pollutes process output with some ANSI stuff when process executed interactively (with tty).

**Comment by hurricup** [comment]
Try to:

1. Choose Help -> Find Action
2. Type `Registry`
3. Find option `terminal.use.conpty.on.windows` and disable it. 

Se if it helps

**Comment by bobgeorge1st** [comment]
It didn't help so much. Now the output looks like this:

2022-01-18 12:22:15,300 [  80858]  DEBUG - debugger.PerlDebugProfileState - system: C:/Strawberry/perl/bin/perl.exe -IC:/Users/XXX/IdeaProjects/perl/lib -d:Camelcadedb C:/Users/XXX/IdeaProjects/perl/test/test.pl
 
2022-01-18 12:22:15,300 [  80858]  DEBUG - debugger.PerlDebugProfileState - stdout: [0m[0KListening for the IDE connection at 0.0.0.0:60287...[0K[?25l
[0K[?25h 
2022-01-18 12:22:40,709 [ 106267]  DEBUG - debugger.PerlDebugProfileState - stdout: [?25lTerminating on signal SIGINT(2)[0K[1G[?25h 
2022-01-18 12:22:40,755 [ 106313]  DEBUG - debugger.PerlDebugProfileState - stdout: [?25l
[0K[?25h 
2022-01-18 12:22:40,755 [ 106313]  DEBUG - debugger.PerlDebugProfileState - system: 
Process finished with exit code 2

**Comment by hurricup** [comment]
Just to be sure: does everything works fine in 2021.2?

**Comment by bobgeorge1st** [comment]
No, it's the same problem

**Comment by hurricup** [comment]
Did it work before?

**Comment by bobgeorge1st** [comment]
It worked on a windows 8.1-machine with version 2019.3

**Comment by hurricup** [comment]
@deresov what about you?

**Comment by deresov** [comment]
For me it started after updating IDEA to 2021.3. It worked fine on 2021.2 and earlier.

I have since tried to roll back to 2021.2 and it helps, but doesn't fix the problem completely - I have to hit "Rerun..." button a few times before debugger finally connects. 

Disabling "terminal.use.conpty.on.windows" setting made no difference.

**Comment by hurricup** [comment]
Ok, re-checked on other computer.
Different state of windows:
```
Edition	Windows 10 Pro
Version	21H2
Installed on	‎6/‎18/‎2020
OS build	19044.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

and 

```
Edition	Windows 10 Pro
Version	21H2
Installed on	‎18.‎06.‎2020
OS build	19044.1469
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

Both works fine with both option values. 
Perl is strawberry perl installed with berrybrew. and executed with berrybrew.
Trying direct usage of strawberry perl.

**Comment by stevieb9** [comment]
Author of `berrybrew` here. I've subscribed to this issue and will try to help get it sorted if I can. I'll update dnmfarrell/berrybrew#28 as needed.

**Comment by hurricup** [comment]
@stevieb9 in this case berrybrew is kinda making things better, but guess this the case when two bugs together producing acceptable result. 

Ideally MS should not pollute process output with unnecessary ANSI codes and berrybrew should handle PTY properly (the easiest way in my opinion is to allow perl to do this, without proxying things)

**Comment by hurricup** [comment]
@bobgeorge1st @deresov please, check plugin from artifacts from https://github.com/Camelcade/Perl5-IDEA/actions/runs/1714751395 (when it's done). Should work just fine.

**Comment by deresov** [comment]
Installed plugin from artifacts - debugger connects perfectly. Thanks so much for fixing this!

I noticed two things while testing updated plugin:

"Connected" message sporadically does not show up in console on Windows although debugger connects.

The plugin does not like system perl on macOS either. It works fine with perlbrew installed perl.
Tested on macOS 11.6.2
  system perl (/usr/bin/perl) 5.30.2 with Devel::Camelcadedb v2021.2 - debugger does not connect.
  perlbrew perl (installed in $HOME) 5.34.0 with Devel::Camelcadedb v2021.2 - debugger connects fine.

**Comment by hurricup** [comment]
Regarding `Connected` message: new windows pty library adds ANSI control characters to the process output. Including clear screen before the first text from the process. So if `Connected` appears after this - you see it, if `Connected` comes first - clear screen removes it. 
I don't have a mac to test the system debugger, but will try to figure out something.

**Comment by bobgeorge1st** [comment]
> https://github.com/Camelcade/Perl5-IDEA/actions/runs/1714751395 (

Sorry for delay. Which file should I download to test it?

**Comment by hurricup** [comment]
@bobgeorge1st you may just update plugin from the JB repository, it was released with all fixes applied

**Comment by bobgeorge1st** [comment]
Yeah! Now it works. Thank you very much!
