### ISSUE TITLE
`$|` is interpolated within Regexp

### ISSUE THREAD

**Issue by aldem** [Camelcade/Perl5-IDEA#2439]
Probably related to #1435 - `$|` is interpolated within regexp:

![image](https://user-images.githubusercontent.com/754722/147372787-5274d224-2917-4cd4-a8aa-ae003b0e2482.png)

Plugin v2021.3

**Comment by hurricup** [comment]
Investigation results:
Our lexer has few flows with this:
1. `$|` should not be parsed as variable when interpolated, only `${|}` form
2. `@(`, `@)`, `@|` should be rendered literally when interpolated

Test sample:
```
$ perl -E 'say "$(\n $)\n @(\n @{(}\n @)\n @{)}\n $|\n @|\n @{|}"'
1000 4 24 27 30 46 116 126 131 997 1000 1001
 1000 4 24 27 30 46 116 126 131 997 1000 1001
 @(
 
 @)
 
 0
 @|
 
```

**Comment by hurricup** [comment]
Cover `/[$]/` with test. current lexing is right, not sure if already covered.

**Comment by hurricup** [comment]
Compilation dump: 
```
Compiling REx "$| @| $( $) 54880 @( @)  "
Final program:
   1: BRANCH (3)
   2:   SEOL (28)
   3: BRANCH (FAIL)
   4:   TRIE-EXACT[ ] (28)
        < @> (28)
        < > (9)
   9:     SEOL (10)
  10:     OPEN1 (12)
  12:       EXACT < > (14)
  14:       SEOL (15)
  15:     CLOSE1 (17)
  17:     EXACT < 54880 @> (20)
  20:     OPEN2 (22)
  22:       EXACT < @> (24)
  24:     CLOSE2 (26)
  26:     EXACT <  > (28)
  28: END (0)
minlen 0 
```
