### ISSUE TITLE
Hackathons in 2022

### ISSUE THREAD

**Issue by djzort** [Camelcade/Perl5-IDEA#2442]
I am uncertain what the best contact is for Perl5-IDEA so I just thought i would create an issue. 

We in the perl marketing committee would like to get this project involved in an IDE Hackathon in 2022 (see https://news.perlfoundation.org/post/hackothon-events-planning-2022)

Please comment on the above post and/or jump in to the marketing channel on The Perl Foundations Slack instance (perlfoundation dot slack dot com)

**Comment by hurricup** [comment]
@djzort thank you for the invitation. I commented in the topic, but i'm unable to sign in to the slack workspace (no account for my email)

**Comment by djzort** [comment]
I have just sent an invite from perlfoundation slack to your gmail listed here on github
