### ISSUE TITLE
Camelcade Intellij plugin isn't available in marketplace

### ISSUE THREAD

**Issue by astange1** [Camelcade/Perl5-IDEA#2450]
Hello,   I was just looking to upgrade to a newer plugin for the latest Intellij/Pycharm releases and noticed that the Camelcade plugin isn't available in the plugin Marketplace.     Might there be another location where the plugin can be obtained?

Thank you for all the contributions here!

**Comment by hurricup** [comment]
https://plugins.jetbrains.com/plugin/7796-perl

**Comment by astange1** [comment]
Thank you.    I was searching for Camelcade, and the Plugin Marketplace
came back with no references.

Alan

**Comment by hurricup** [comment]
I should probably add a keyword if possible. Thanks.
