### ISSUE TITLE
Perl with embedded multiline SQL syntax highlighting issues

### ISSUE THREAD

**Issue by markndelaney** [Camelcade/Perl5-IDEA#2480]
Hi,
With standard perl5 plugin within Idea I find the Identification and highlighting of embedded multiline SQL support is patchy.  Please see attached file for examples.

IDE: IDEA IntelliJ IDEA 2021.3.3 (Ultimate Edition), Build #IU-213.7172.25, built on March 15, 2022
Perl plugin:  Alexandar Evstigneev 2021.3.1
MacOS Monterey 12.3

![Perl with embedded SQL](https://user-images.githubusercontent.com/12050952/160141288-923521eb-2d9e-4b4c-8aa0-664d01ecc75a.png)

# These perl examples correctly do SQL syntax highlighting

my $ip_cpe = cmdbQueryOneValue("SELECT start_ip FROM slot_ip WHERE slot_id=$slot_id");

foreach my $bar (cmdbQuery(<<"SQL"
    SELECT start_ip FROM slot_ip
SQL
)) {
}

foreach my $bar (cmdbQuery(<<"SQL")) {
    SELECT start_ip FROM slot_ip
SQL
}

if (cmdbQuery(<<"SQL")) {
    SELECT start_ip FROM slot_ip
SQL
}

# These perl examples do not do SQL syntax highlighting

my $ip_cpe2 = cmdbQueryOneValue(<<"SQL");
	SELECT start_ip FROM slot_ip WHERE slot_id=$slot_id
SQL

my $ip_cpe3 = cmdbQueryOneValue(<<"SQL:MariaDB");
	SELECT start_ip FROM slot_ip WHERE slot_id=$slot_id
SQL:MariaDB

my $foo = <<"SQL";
	SELECT start_ip FROM slot_ip WHERE slot_id=$slot_id
SQL

my $baz = <<"SQL"
	SELECT start_ip FROM slot_ip WHERE slot_id=$slot_id
SQL
;

# language=SQL:MariaDB
my $foo2 = <<"SQL";
	SELECT start_ip FROM slot_ip WHERE slot_id=$slot_id
SQL
# language=Perl

**Comment by hurricup** [comment]
By default injection is disabled for texts with interpolation. In perl settings there is a checkbox to enable it. But this may produce false-positive errors from SQL code insight.

**Comment by markndelaney** [comment]
'Automatically inject other languages in here-docs by marker text' was already checked prior to raising issue.

Setting the 'Allow injections in QQ here-docs with interpolated entities' checkbox solved the issue even though I'm **not** using the 'qq {  }' syntax and therefore I wouldn't have expected this checkbox to solve this.

Thank you for your quick response / help.

**Comment by hurricup** [comment]
Well, qq means things supporting interpolation. Not only `qq/../` literally
