### ISSUE TITLE
qq incorrectly re-wraps newlines - breaking code logic

### ISSUE THREAD

**Issue by todd-richmond** [Camelcade/Perl5-IDEA#2481]
In current latest plugin, qq// is reformatted to incorrectly modify newlines which can break code logic. Here is an example of some code to create gnuplot config that wraps between the $self terms if line length is set to 80 which is then invalid config

The qw// list configuration option does not make any difference even when set to "don't wrap"

```
sub foo() {
    print GP qq~
	set term png size $length,$height large font "$self->{fontname}" $self->{gnuplot_font_size} background "#ffffff"
	set linetype 1 linecolor rgb "#ff0000"
	~;
}
```
becomes
```
sub foo() {
    print GP qq~
	set term png size $length,$height large font "$$self{fontname}" 
	$$self{gnuplot_font_size} background "#ffffff"
	set linetype 1 linecolor rgb "#ff0000"
	~;
}

**Comment by hurricup** [comment]
I can not reproduce the issue with default formatting settings. 
Please, provide a screenshot of your perl code style settings: wrapping and perl5-specific tabs.

**Comment by todd-richmond** [comment]
I just realized I was using 2021.3 instead of 2022.1. I just upgraded and it pulled down the latest plugin so I'm trying to repro the problem

**Comment by todd-richmond** [comment]
still happens with the latest plugin. I did forgot to add a "sub xxx" wrapper in my example so my lines were indented 4 chars. Replacing $self->{fontname} with xxxxxxxxxxxxxxxx causes the same wrap bug as does removing the " chars so this seems to just be a problem with qq incorrectly as if were qw

**Comment by hurricup** [comment]
First strange thing is that your code style missing settings responsible for conversion of `$a->` to `$$a`. Should look like
```
  <Perl5CodeStyleSettings>
    <option name="OPTIONAL_DEREFERENCE_HASHREF_ELEMENT" value="1" />
    <option name="OPTIONAL_DEREFERENCE_SIMPLE" value="2" />
  </Perl5CodeStyleSettings>
```
And the second strange thing is that I can't reproduce it, works as intended. 
Do you have any additional plugins enabled?

**Comment by todd-richmond** [comment]
looks like the options block got rewritten when I upgraded to latest plugin. All the options on the UI seem the same so defaults might have changed
```
    <Perl5CodeStyleSettings>
      <option name="OPTIONAL_QUOTES" value="2" />
      <option name="OPTIONAL_QUOTES_HASH_INDEX" value="2" />
      <option name="OPTIONAL_QUOTES_HEREDOC_OPENER" value="2" />
      <option name="OPTIONAL_DEREFERENCE" value="2" />
      <option name="OPTIONAL_DEREFERENCE_HASHREF_ELEMENT" value="1" />
      <option name="OPTIONAL_DEREFERENCE_SIMPLE" value="2" />
      <option name="OPTIONAL_PARENTHESES" value="1" />
      <option name="MAIN_FORMAT" value="2" />
      <option name="SPACES_WITHIN_ANON_HASH" value="false" />
      <option name="SPACES_WITHIN_ANON_ARRAY" value="false" />
      <option name="METHOD_CALL_CHAIN_SIGN_NEXT_LINE" value="false" />
      <option name="ATTRIBUTES_WRAP" value="1" />
      <option name="QW_LIST_WRAP" value="1" />
      <option name="ELSE_ON_NEW_LINE" value="false" />
      <option name="VARIABLE_DECLARATION_WRAP" value="1" />
    </Perl5CodeStyleSettings>

**Comment by hurricup** [comment]
Reproduced. Thank  you

**Comment by todd-richmond** [comment]
great - glad it repros. hopefully #2482 is related or a dup
