### ISSUE TITLE
Linebreaks added inside quoted strings

### ISSUE THREAD

**Issue by todd-richmond** [Camelcade/Perl5-IDEA#2482]
This might be related to issue #2481, but happens in simple inline quoted strings and broke many files. The quotes are not necessary in the function call but legal and occur in too many places to track down.

```
sub foo() {
    $self->{database_datasource} = $self->{config}->get("$self->{datasource}.datasource");
}
```
becomes
```
sub foo() {
    $$self{database_datasource} = $$self{config}->get("
	$$self{datasource}.datasource");
}

**Comment by hurricup** [comment]
Same thing here
Before: 
![image](https://user-images.githubusercontent.com/2811330/163866926-993283b1-e765-401e-8656-26fda4173ae1.png)

After
![image](https://user-images.githubusercontent.com/2811330/163866998-f52ac8df-5476-4106-8e71-79d1e1a811bd.png)

Also editor screenshot would be nice, to know where wrapping limit is.

**Comment by todd-richmond** [comment]
config in #2481. Editing the sample to be in a sub foo here too so that indents are correct

**Comment by hurricup** [comment]
Yes, this is the same problem as #2481
