### ISSUE TITLE
Object::Pad support

### ISSUE THREAD

**Issue by cmburn** [Camelcade/Perl5-IDEA#2483]
Hi! 
[Object::Pad](https://metacpan.org/pod/Object::Pad) is an OOP library being written by one of the core Perl developers, Paul Evans (aka LeoNerd). It forms the base of Corinna, the object system being developed to be merged into base Perl. It's quite useful, and a bit cleaner than Moose. My Java is a bit rusty, but I can still write it if you point out how you want it done!

**Comment by hurricup** [comment]
This is a large task to do. Can't give an estimation in today world situation :(

**Comment by hurricup** [comment]
As far as I know native perl OOP is on the way, so this probably won't be implemented.

**Comment by rwp0** [comment]
> As far as I know native perl OOP is on the way, so this probably won't be implemented. 

`feature-class` (Corinna) has almost the same language as Object-Pad, and also implemented by the same author
