### ISSUE TITLE
New File: defaulting to Script instead of Package

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2493]
It hit me many times

everytime I do `File` -> `New` -> `Perl5 File` I accidentally create a module with `.PM` extension instead of a script.

![Perl script](https://i.imgur.com/QIZbltt.png)

I think scripts should be the default because they are created/used more often than modules for Perl code.

There were `.pl` before `.pm` existed historically as well.

Thanks.

**Comment by hurricup** [comment]
Well, this is questionable. 
E.g web application will have a single starter script and all the code going to be in pm controllers/templates. Not in pl scripts.
Also, here is alphabetical sorting, Package and script. not extensions. 
However, I can understand your concern and feels like IDE should remember last choice or smth. But this feels like an IDE feature not a plugin.

**Comment by rwp0** [comment]
Can we configure it without changing the defaults?

An option for this would be very useful.

Also, if I name my script `.pl` it still creates it as a module (suffix could be read as well).

**Comment by hurricup** [comment]
configure what? Atm this menu is pretty static and dumb.

**Comment by rwp0** [comment]
Configure the selected item or the order of items on the menu.

I see, but might be worthy to enhance it a bit for that reason.

**Comment by rwp0** [comment]
Haha saw you mixing those on YouTube as well 😋

**Comment by hurricup** [comment]
true :)
