### ISSUE TITLE
Warning on using IO::Handle methods

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2495]
[printf](https://github.com/Perl/perl5/blob/blead/dist/IO/lib/IO/Handle.pm#L421) method is defined in [IO::Handle](https://perldoc.perl.org/IO::Handle#METHODS) module

![Screenshot](https://i.imgur.com/5THNsBD.png)

I don't know if it's possible to add definition for filehandle OO methods, but that would prevent warnings from showing up.

Thanks.

**Comment by hurricup** [comment]
Have you deparsed XSubs?

**Comment by rwp0** [comment]
Probably yes, I have `_Deparsed_XSubs.pm` in place.

Just run `Tools -> Perl5 -> Re-Generate XSubs Declarations` if that's what you mean.

**Comment by hurricup** [comment]
Is `IO::Handle::printf` there?
Try to specify type of `$file` explicitly with annotation and see if it helps.

**Comment by hurricup** [comment]
Can we close this one?
