### ISSUE TITLE
RFE: support for interpreters managed by the [asdf](https://asdf-vm.com) version manager

### ISSUE THREAD

**Issue by scop** [Camelcade/Perl5-IDEA#2499]
Would be nice to have support for intepreters managed by [asdf](https://asdf-vm.com) version manager, in particular [its Perl plugin](https://github.com/ouest/asdf-perl), like there is for plenv and perlbrew managed ones.

I'm primarily interested in just having the IDE automatically suggest interpreters installed in the asdf install location when one starts to choose one in Languages & Frameworks > Perl5, no need for anything besides that as far as I'm concerned for now. asdf + its Perl plugin managed interpreters are installed in `~/.asdf/installs/perl` by default.

Further enhancements could include automatically choosing the correct one based on asdf's [`.tool-versions` file](https://asdf-vm.com/guide/getting-started.html#_6-set-a-version).

**Comment by hurricup** [comment]
- [x] add and use asdf interpreter
- [ ] terminal customizer
- [ ] UI to install perl (may be shared with `plenv`, both using `perl-install` under the hood)
- [ ] docker images for tests
- [ ] integration tests
- [ ] configure CI with asdf

**Comment by hurricup** [comment]
Feel free to try artifacts from this build: https://github.com/Camelcade/Perl5-IDEA/actions/runs/4284499126

**Comment by hurricup** [comment]
Please, be aware of ouest/asdf-perl#20 issue with threads number
