### ISSUE TITLE
No documentation for most Perl functions

### ISSUE THREAD

**Issue by christianitis** [Camelcade/Perl5-IDEA#2502]
Using IntelliJ Ultimate 2022.1.3, on bundled JRE (OpenJDK 11.0.15). Host OS is OpenSUSE Tumbleweed. Plugin version 2022.1.1.

"No documentation found." for almost all standard (stock) functions. Documentation for standard packages and pragmas work fine though.
Using the same setup at work (except running on Windows 10), documentation displays fine.
Not sure if this is related, but almost no documentation seems to show for imported modules/packages and their functions either (99% of the time)

**Comment by hurricup** [comment]
What is your Perl version?

**Comment by christianitis** [comment]
> What is your Perl version?
5.34.1 for x86_64-linux-thread-multi.
Also tried with 5.34.0 for x86_64-linux-thread-multi, still no documents.

**Comment by hurricup** [comment]
I have no access to such host OS, so can't investigate further here. Still it works for ubuntu and perlbrew installed perl
![image](https://user-images.githubusercontent.com/2811330/204120765-ace1966e-3703-4567-bec3-b8275a6288db.png)

Does `perldoc -f my` works from the console? 
Do you have a `pod` directory in one of the package roots? Like this:
![image](https://user-images.githubusercontent.com/2811330/204120828-24e852d0-460a-4fbf-9340-0324d244d2d8.png)

**Comment by hurricup** [comment]
Guess I reproduced that. In my case it works, for example for keywords. But not working for packages/subs. Investigating. Presumably broken in IDE.

**Comment by hurricup** [comment]
Looks like
![image](https://user-images.githubusercontent.com/2811330/204136189-ffa5c27c-0fd5-48d9-9654-af5e4c0ca48f.png)
or
![image](https://user-images.githubusercontent.com/2811330/204136200-a996e165-8164-48ff-a209-9e953e9feeca.png)

**Comment by christianitis** [comment]
> I have no access to such host OS, so can't investigate further here. Still it works for ubuntu and perlbrew installed perl ![image](https://user-images.githubusercontent.com/2811330/204120765-ace1966e-3703-4567-bec3-b8275a6288db.png)
> 
> Does `perldoc -f my` works from the console? Do you have a `pod` directory in one of the package roots? Like this: ![image](https://user-images.githubusercontent.com/2811330/204120828-24e852d0-460a-4fbf-9340-0324d244d2d8.png)

`perldoc -f my` returns "ListUtil.c: loadable library and perl binaries are mismatched (got first handshake key 0xeb00080, needed 0xeb80080)". So it must be a problem on my end.

**Comment by hurricup** [comment]
There also were a problem on the IDE side which is now fixed, so thank you again :)
