### ISSUE TITLE
Support Syntax::Keyword::Match syntax

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2513]
## Keywords

- [match](https://metacpan.org/pod/Syntax::Keyword::Match#match)
- [case](https://metacpan.org/pod/Syntax::Keyword::Match#case)
- [default](https://metacpan.org/pod/Syntax::Keyword::Match#default)

`match` currently reddens out the editor:

![image](https://user-images.githubusercontent.com/68062695/195574818-0708200e-5902-4ab5-bb2b-97b58af308a6.png)

Making `eq` an `Unexpected token`.

Note that the `OP` (`==`, `eq`, `=~`, and `isa` is a bareword, and not a string).

This will most likely be the core syntax of Perl as well in the future.

Thanks

---

Build #IC-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Plugin version: 2022.2.2
Debian 11

**Comment by hurricup** [comment]
sorry, but I can't support every syntax extension written for perl. Perl has it's own switch functionality, suggest to use it. 
Some exceptions may be made for suer-old or super-popular extensions, but this is not the case as far as I can see.

**Comment by rwp0** [comment]
Okay, but I think the built-in switch functionality (the `switch` feature) is deprecated and is going to be removed, and probably replaced by the syntax of this very module.

**Comment by hurricup** [comment]
We will get back to it then.
