### ISSUE TITLE
type annotation should work with primitive types

### ISSUE THREAD

**Issue by anton-kapelyushok** [Camelcade/Perl5-IDEA#2554]
I am not sure if I understand current intent of `#@type` annotations, but it seems like the following code should work:

````perl
#@type HashRef[Int]
my $var = {foo => 1};
````

But Idea complaints with "Unable to find namespace definition"  on `Int`

**Comment by hurricup** [comment]
At the moment `#@type` hints the IDE object's class. (what reference is blessed with)

See: https://github.com/Camelcade/Perl5-IDEA/wiki/Annotations#type (should be updated, a bit obsolete)
See: https://github.com/Camelcade/Perl5-IDEA/issues/254 (parsing was implemented, but other logic was not).

**Comment by anton-kapelyushok** [comment]
Thank you for your answer! Could not find it in the wiki)

Another issue I encountered (I will report here to avoid creating new issue)
While using signatures feature Idea tries to format the following code like this:

```
use feature ('signatures');
sub my_sub(
#@type MyType
    $poupa
) {}
```

instead of 

```
use feature ('signatures');
sub my_sub(
    #@type MyType
    $poupa
) {}
```
