### ISSUE TITLE
Perl plugin modifies behavior of comments in C files

### ISSUE THREAD

**Issue by rillig** [Camelcade/Perl5-IDEA#2563]
In a C project in CLion 2022.3.1, open a C (not Perl) file.
Paste the following comment:
~~~c
/*
 * Some comment unrelated to the URL.
 *
 * https://example.org/
 */
~~~
Press Ctrl, hover over the URL in the comment.

***What is the expected result?***
The URL is highlighted, when I click, the URL opens in the browser.

***What happens instead?***
The whole comment is highlighted:
![](image.png)

***What OS and IDE versions are used?***
~~~text
CLion 2022.3.1
Build #CL-223.8214.51, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0

Non-Bundled Plugins:
    com.perl5 (2022.3.1)
~~~

**Comment by hurricup** [comment]
- Happens in Java and IDEA as well. 
- Link works fine, but highlighting is wrong.
- Can't say at once why, platform changed a lot in this part some time ago.

**Comment by hurricup** [comment]
With plugin it ends like this (with full element range):
![image](https://user-images.githubusercontent.com/2811330/214068476-dc9e5550-f2ae-470b-9d98-5098335a76c6.png)

Without plugin like this (with proper range):
![image](https://user-images.githubusercontent.com/2811330/214069297-d30d3028-a7e0-41c3-a644-0c227f5a8eaf.png)
