### ISSUE TITLE
Perl::Tidy in external libraries not found

### ISSUE THREAD

**Issue by scop** [Camelcade/Perl5-IDEA#2582]
Similarly as #2569 for run/test configs, looks like the configured external libraries dirs are not searched for Perl::Tidy either.

Setup details are the same as in #2569.

Tools -> Perl5 -> "Reformat ... with Perl::Tidy" gives this, even though Perl::Tidy is installed in the configured external libraries dir:

![Screenshot from 2023-02-24 21-23-23](https://user-images.githubusercontent.com/109152/221272538-d5a09d7c-8671-4bf5-8fae-178e90908aa3.png)

**Comment by hurricup** [comment]
Strange, this now should be covered with tests. Will check.

**Comment by hurricup** [comment]
what version of the plugin are you using?

**Comment by scop** [comment]
2022.3.2 (with GoLand 2022.3.2).

**Comment by hurricup** [comment]
then this is the same bug. Bugfix was not yet released. If you want to get fixed version asap, you should download plugin from github actions and install it from the disk. But i'm currently releasing 3.3, so just wait  a bit.

**Comment by scop** [comment]
Ack, fix for this and #2569 verified with 2022.3.3. Thanks!
