### ISSUE TITLE
Implement terminal customizer

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2584]
Necessity to switch in terminal is really annoying

**Comment by rwp0** [comment]
Do you mean switching the Perl version?

**Comment by hurricup** [comment]
yep. it should work automatically. Switch to project selected interpreter

**Comment by rwp0** [comment]
Exactly I found myself doing `perlbrew use blead' on each terminal tab in the project. Looking forward to having this set to the project's selected interpreter. Thanks for the consideration 👍

**Comment by hurricup** [comment]
Plugin built in https://github.com/Camelcade/Perl5-IDEA/actions/runs/4276113351 should be able to automatically configure terminal for the `perlbrew` and `plenv`. 

IMPORTANT: some adjustments may be necessary (bash example):
- it may be necessary to move initialization from `.bashrc` to `.profile` 
- it is necessary to change terminal command from `/bin/bash` to `/bin/bash -l` so profile was sourced.

Not sure if it may work correctly in interactive mode and source `.bashrc` properly.
