### ISSUE TITLE
IntelliJ IDEA CE EAP Support

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2590]
![image](https://user-images.githubusercontent.com/68062695/221644891-e5bc44f3-fe26-4127-97c9-72fc876590f5.png)

![image](https://user-images.githubusercontent.com/68062695/221644608-75bf8b8a-6633-482d-b07f-21c6ff8e7497.png)

Can we have EAP support for the plugin?

**Comment by hurricup** [comment]
see https://twitter.com/CamelcadeIDE/status/1593454890432581633?t=ikGwMVId8llbMZbeHRcGTA&s=19

**Comment by rwp0** [comment]
Great, thanks!

**Comment by hurricup** [comment]
Was done in  fc6482d0868111abc2c4306bd29b34d477920902 actually
