### ISSUE TITLE
STDERR from prove has double line feed in output window

### ISSUE THREAD

**Issue by tomk3003** [Camelcade/Perl5-IDEA#2637]
When running tests that produce output on STDERR the lines have always an additional linefeed.
This is not happening on the commnd line. 

PyCharm 2022.3.3 (Professional Edition)
Build #PY-223.8836.43, built on March 10, 2023
Runtime version: 17.0.6+1-b653.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-35-generic
Non-Bundled Plugins:
    com.perl5 (2022.3.3)
    com.perl5.lang.embedded (2022.3.3)
    com.perl5.lang.tt2 (2022.3.3)
    com.perl5.lang.mojo (2022.3.3)

**Comment by hurricup** [comment]
Feels, like this is IDE problem, not plugins: https://youtrack.jetbrains.com/issue/IDEA-316156/Stderr-output-from-tests-contains-extra-newlines
