### ISSUE TITLE
Respect Perl::Critic configuriation about the necessity of the imports of strict and warnings

### ISSUE THREAD

**Issue by damenc** [Camelcade/Perl5-IDEA#2681]
The plugin always reminds the developer to make use of the pragmas [strict](https://perldoc.perl.org/strict) and [warnings](https://perldoc.perl.org/warnings) which is of course a totally fine feature:

![image](https://user-images.githubusercontent.com/50652738/235610914-15b9dd44-7827-46c9-bf59-81bda03b6127.png)

I always do use them but the pragmas are set by importing other modules. For example [Moose](https://metacpan.org/pod/Moose) does this for me. In order not fail about the supposedly missing pragma imports when executing static code analysis using [Perl::Critic](https://metacpan.org/pod/Perl::Critic) the configuration holds alternative Modules fulfilling the needs:

![image](https://user-images.githubusercontent.com/50652738/235611545-bdd9ea2f-c7c3-43ff-99d2-f3198f48d843.png)

Of course I can get rid of the reminders by disabling them but this is not really target-oriented. It would be perfect if the [Perl::Critic](https://metacpan.org/pod/Perl::Critic) configuration could be respected at this point.

**Comment by hurricup** [comment]
Actually plugin should understand that `use Moose;` or `use Moo;` and some other packages implies strict and warnings. 
What is your particular case?

**Comment by hurricup** [comment]
Actually, I should probably replace current approach with hardcoding this with user-configurable list, would be a nice feature.

**Comment by damenc** [comment]
@hurricup Thank you very very much. That's **exactly** what we need, so we can configure our base project module as provider for warnings and strict pragma :-)
