### ISSUE TITLE
Code style: cuddled else

### ISSUE THREAD

**Issue by targzeta** [Camelcade/Perl5-IDEA#2682]
On reformatting code, the plugin rewrite these lines:
```perl
if (1) {
  print 'always';
} else {
  print 'never';
}
```
as:
```perl
if (1) {
  print 'always';
}
else {
  print 'never';
}
```
I remember there was an option to change this code style, but I can't find it anymore!

Best regards,
Emanuele

P.S. PyCharm 2023.1.1 (Professional Edition) Build #PY-231.8770.66, built on April 27, 2023
Perl plugin 2023.1.1

**Comment by targzeta** [comment]
Hi Alexandr,
thank you for your reply.

I tried a little bit of everything but nothing worked, as you can see on the previous window :(
![screenshot_20230512_182925](https://github.com/Camelcade/Perl5-IDEA/assets/2431105/1828d1eb-689e-4bde-bf9d-8d573e657263)

Emanuele

**Comment by hurricup** [comment]
preview may not work, because this option works only one way. It may insert new line if missing. 
Should probably be adjusted to `as is`/`same line`/`different lines`. Or it should remove newline if unchecked. I'll investigate. 
For now inserting newline should work.

**Comment by targzeta** [comment]
Alexandr,
but with this option unchecked, the command "Reformat Code (Ctrl+Alt+L)"  moves my "else" branch in a new line.
The code:
![screenshot_20230512_234830](https://github.com/Camelcade/Perl5-IDEA/assets/2431105/b34f6c4b-e030-48c5-9c40-2bfa728f61b4)

The config:
![screenshot_20230512_234355](https://github.com/Camelcade/Perl5-IDEA/assets/2431105/7c96ee6a-60ca-47d2-8318-1c813eddbb99)

The result of "Reformat Code" command:
![screenshot_20230512_234842](https://github.com/Camelcade/Perl5-IDEA/assets/2431105/42a70223-08c7-41ba-97a5-05ab3256b1d8)

I'm sure that my code base it was format with the Tools "Actions on Save -> Reformat code". So I think that this is a recently bug.

Now I have disabled the "Actions on Save -> Reformat code" because I'm unable writing code with my preferred code style.

Best regards,
Emanuele

**Comment by hurricup** [comment]
I will check this. Something seems wrong.

**Comment by hurricup** [comment]
Ok. The problem is - misleading text on the option. You are looking into spacing tab and this checkbox is about a space before the keyword. Newline option is on the `wrapping braces and alignments` tab. Option has the same name for some reason.

**Comment by hurricup** [comment]
Here we go

![image](https://github.com/Camelcade/Perl5-IDEA/assets/2811330/dc0eabd6-726c-4ca0-97d3-0b2cedb7e7e4)

**Comment by targzeta** [comment]
Thank you Alexandr!

Emanuele
