### ISSUE TITLE
The perl project does not appear in Recent Projects list

### ISSUE THREAD

**Issue by Ashark** [Camelcade/Perl5-IDEA#2754]
Hello, and thank you for this plugin.

The question is not about the work of plugin itself, but about the little thing - it is not displayed in Recent Projects of IntelliJ Idea. However, when I start intellij idea, it is opened with it as a last opened project.

I would like the project to also appear in Recent Projects list, because I have a launcher that can quickly launch a needed project.

 
IDE name and version:
```
IntelliJ IDEA 2023.1.4 (Community Edition) Build #IC-231.9225.16, built on July 13, 2023
Runtime version: 17.0.8.1+1 amd64
VM: OpenJDK 64-Bit Server VM by N/A
```
Perl5 plugin: version: 2023.1.2
JRE version:
```
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1, mixed mode)
```
Your OS name and version: Arch Linux

**Comment by hurricup** [comment]
This sounds like an IDE problem, not plugins. I would suggest to try in most recent version and if problem is still there, report to the https://youtrack.jetbrains.com/

**Comment by Ashark** [comment]
Thanks for suggestion. I have checked with the recent eap version and it fixed there.

IntelliJ IDEA 2023.2.2 (Community Edition)
Build #IC-232.9921.47, built on September 13, 2023
