### ISSUE TITLE
Add line numbers to the Threads & Variables panel

### ISSUE THREAD

**Issue by Ashark** [Camelcade/Perl5-IDEA#2780]
Currently (Perl plugin 233.9102.97-EAP-SNAPSHOT), when debugging, in "Threads & Variables" panel, you can see stack lines. But they do not have line numbers at which the line is currently staying.
However, the debugger does apparently know that numbers, because it jumps there when I click.
It would be nice to see line numbers (like it is expected for any other language, for example for python in PyCharm).

<img src=https://github.com/Camelcade/Devel-Camelcadedb/assets/22634975/5b7c0c27-b022-41f3-aa0c-3d8d12a9dd47 width=50% />

<img src=https://github.com/Camelcade/Devel-Camelcadedb/assets/22634975/11501d7f-1a75-481b-94cd-c833f2bc7ed3 width=50% />

**Comment by Ashark** [comment]
Ух ты! Спасибо за такой быстрый фикс! Буду следить когда выйдет следующая версия.

**Comment by Ashark** [comment]
I am not sure how correct it would be for perl, but could it be possible to also slightly improve the format?
As can be seen in screenshot for python debugger, the format is `function, file:line`. Can the perl debugger use the same? I.e., separate function name from package/file name? For example, the above frame could be written as:
 `_readConfigurationOptions, Application.pm:1234`.

I have noticed that the format may differ per language. For example, [here](https://youtrack.jetbrains.com/issue/IDEA-308138/) you can see it for php, and [here](https://betterprogramming.pub/intellij-idea-debugging-like-a-pro-d1169545a0a7) for java.

**Comment by hurricup** [comment]
The problem is that it is not possible to show sub name and file path together so they both were visible. May be should show file name if sub is available. WIll think about it.

**Comment by hurricup** [comment]
Ended up with something like this: 
![image](https://github.com/user-attachments/assets/8a01d9ad-23a8-44c5-a508-66f92be3fcac)

**Comment by Ashark** [comment]
Thanks! 
I am not using the plugin currently, but hope it will be useful in the future.
