### ISSUE TITLE
Use "perl5-IDEA" as a plugin archive name for releases

### ISSUE THREAD

**Issue by Ashark** [Camelcade/Perl5-IDEA#2789]
Hello.
Just a minor nitpick. Can you please give a meaningful name to the release archive in the JetBrains marketplace? Because currently, it is called just "plugin-233.9102.97-EAP-SNAPHOT.zip". When downloading manually, in the Downloads folder it is not obvious that it is a perl plugin. The other plugin developers name their archive with the name of plugin, you can see that for installed plugins "~/.local/share/JetBrains/<idename_version>/", for example "markdown-editor".
Probably, it is not possible to rename previous releases, but for new releases the "normal" archive name "Perl5-IDEA" can be used.

**Comment by hurricup** [comment]
The problem seems that jar is called same as a module it was built from. Usually plugins have a single module project and project name is used. Here we have a multi-module structure and plugin is build from `:perl5:plugin` module. I'll take a look, thanks.
