### ISSUE TITLE
Remote Perl Interpreter Support 🐪

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2808]
Though we can install the plugin on an SSH-based remoting IDE with success, we can't make use of it since it doesn't detect the remote Perl Interpreter, and setting the local Perl Interpreter also has no effect (eg. to color up the editor, enable Structure tool window etc).

So given these findings, can we say that remote JetBrains IDE installation is not supported at all by this plugin?

For contrast, I'd no problem setting up a remote Python interpreter with PyCharm (are we not in that level yet?).

**Comment by hurricup** [comment]
Duplicates #1823
