### ISSUE TITLE
Unable to configure in 241.4832 version

### ISSUE THREAD

**Issue by Ashark** [Camelcade/Perl5-IDEA#2823]
Hello.
The plugin is broken for version 2024.1.

  * IDE name and version: IntelliJ IDEA 2024.1 EAP (Ultimate Edition) , Build #IU-241.8102.112, built on January 16, 2024
  * Perl5 plugin version: 241.4832
  * JRE version: bundled inside the intellij-idea-ue-eap 2023.3.241.8102.112-1 package
  * Your OS name and version: Arch Linux

In all my perl run/debug configurations, the red cross is shown.

![invalid configuration](https://github.com/Camelcade/Perl5-IDEA/assets/22634975/ab644afe-7554-4581-a1cd-b3b4ec556d4c)

In **Settings | Languages & Frameworks | Perl 5** in **Project | Perl5 | Perl5 Interpreter** I see that there are no interpreters available.

![no perl5 interpreters](https://github.com/Camelcade/Perl5-IDEA/assets/22634975/3d1f388a-8657-4e54-8736-920fa91659a1)

Now I press gear button, Local, Add System Perl and select the path to `/usr/bin/perl`.

![Add perl system interpreter](https://github.com/Camelcade/Perl5-IDEA/assets/22634975/e6a06037-5abd-43ed-95c7-95da40773f4a)

After I press "Ok" button in file selection dialog, the interpreter is not added to list. Instead the interface is semi-hanged.

If I close the settings window, then (without restarting IDE) go to these settings (Perl5) again, the page is not rendered correctly.

---
 If I rollback to the previous version of IntelliJ and the plugin - it works as expected.

**Comment by hurricup** [comment]
Plugin does not work in most recent 241 versions yet. Last showstopped was fixed yesterday (presumably) i'll try to address this as soon as I can. In worth case - on the weekend. Sorry.

**Comment by hurricup** [comment]
Please, try the recent EAP version, it should work.

**Comment by hurricup** [comment]
Let me know if there are still problems.

**Comment by Ashark** [comment]
Yeah, it installed and works. Thank you!

I additionally wanted to say you a HUGE THANKS for your plugin. With it, I could port a [legacy kde project on perl](https://invent.kde.org/sdk/kdesrc-build) to the [python implementation](https://invent.kde.org/sdk/kde-builder). That was a huge project that took me approximately half of the year. But without your amazing plugin that would be even harder.

Your plugin allowed to use the convenient JetBrains editor and allowed to debug the perl. Thank you very much!
