### ISSUE TITLE
Ghost inspections

### ISSUE THREAD

**Issue by morehockeystats** [Camelcade/Perl5-IDEA#2860]
![ghost-inspections](https://github.com/Camelcade/Perl5-IDEA/assets/40477794/fcdbdeb9-da77-4c47-b0c1-462213183951)
The plugin continues to see failed inspections even after they are gone.

Screenshot attached. You can see there are no violations in lines 397 and 398, for example.

Option to "Suppress" inspection has disappeared in the current version:
IntelliJ IDEA 2024.1.2 (Ultimate Edition)
Build #IU-241.17011.79, built on May 22, 2024

Plugin:
Version: 2024.1

Java:
JRE: Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Theme: Xcode Dark Theme 1.2.4

OS: Ubuntu 22.04.4

**Comment by hurricup** [comment]
This is a known IDE issue: https://youtrack.jetbrains.com/issue/IJPL-28967

**Comment by hurricup** [comment]
does reopening file/project helps? if yes, that it is definitely it

**Comment by morehockeystats** [comment]
reopening the file doesn't fix it, reopening the project does. Yeah, that's it. Sorry.
