### ISSUE TITLE
IDEA 2024.2 is out, breaking Perl support

### ISSUE THREAD

**Issue by Zastai** [Camelcade/Perl5-IDEA#2870]
IDE: #IU-242.20224.300 (on Windows 11, with the bundled JetBrains JRE: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9))
Plugin: 2024.1

The plugin only report support up to 241.*, so will not load in this version.

Would it be possible to adjust the plugin to report support for the entire major version (i.e. up to but not including 250.*), so that this issue only occurs on the 2024.x -> 2025.x upgrade?
Or does JetBrains treat 2024.2 as a major version compared to 2024.1, including API breaks?

**Comment by hurricup** [comment]
I'm sorry for inconvenience. Trying to build the plugin for 24.2, but still wip.

**Comment by akarelas** [comment]
Anyone knows if I'm allowed to install WebStorm 2024.1 again, to get the Perl plugin working, or if the `.idea` folder has been modified too much by the new version and it's a risk to do that?

**Comment by hurricup** [comment]
most likely they don't. Usually it is safe to just remove your `.idea` folder and it is going to be re-created by the IDE. You may loose some settings though. You may back up your `.idea` dir and give it a try. 
No user files should be modified.

**Comment by akarelas** [comment]
Thanks. All I needed to do was backup .idea and otherwise keep it intact before downgrading to WebStorm 2024.1.

**Comment by hurricup** [comment]
2024.2 is now avaialble, sorry for the delay.

**Comment by akarelas** [comment]
@hurricup I've got WebStorm 2024.1 and I'm not seeing the Perl plugin as having available updates. Is it because I have WS 2024.1? Will I see the plugin update as soon as I update my WS?

**Comment by Zastai** [comment]
Thanks, @hurricup !

@akarelas I would expect so.

**Comment by hurricup** [comment]
@akarelas yes, because it is compatible with 2024.2.x
