### ISSUE TITLE
`await` keyword is not recognized

### ISSUE THREAD

**Issue by thekip** [Camelcade/Perl5-IDEA#2873]
I have to work with a legacy perl project which is using async/await. I checked the issues in this repo and it seems IDE should support this syntax. 

However, IDE gives me warning and not correctly parse expressions when `await` keyword is used. It seems `async` keyword works just fine. 

<img width="783" alt="image" src="https://github.com/user-attachments/assets/87951338-4328-4127-a72b-d59cbb1aa18e">
 
In more complicated cases it completely messes the syntax and make some symbols unaccessable: 

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/65d8443e-f174-4465-9ffc-a25ee0c7a647">

Because it thinks that `await` is a "fancy" method of `RT::API::Google::Places` not even `RT::API::Google::Places->findplacefromtext_p(...)` 

* Webstorm Build #WS-241.18034.50, built on June 19, 2024
* Perl5 plugin version 2024.1

I'm not sure is it how it supposes to be, or i should use some specific syntax to make it work?

**Comment by hurricup** [comment]
I will look into this after releasing 24.2. irr it should work same way as async, but was some time ago

**Comment by hurricup** [comment]
So. In the support for the `Future::AsyncAwait` was implemented in the #2144 and only `async` is treated as a keyword, because the context of it is more or less clear - sub definition. `await` can technically be in different places and if we will treat it as a keyword this may cause to false-positive lexing in some projects. 

I'll re-check the syntax and see if I could improve your cases handling.

**Comment by hurricup** [comment]
Ok, seems it is an unary operator and may be I could add it to the lexer
```
use v5.14;
use Future::AsyncAwait;
use warnings FATAL => 'all';
use strict;

sub myecho{
    return shift;
}

async sub asyncecho{
    return shift;
}

async sub mysub{
    say myecho 42 + 42;
    say myecho(42) + 42;
#    say await asyncecho(42) + 42; # Expected a blessed object reference to await at ... unary operator
    say await(asyncecho(42)) + 42;
    say await asyncecho(42), 24;
    return ((await asyncecho(42)) + 42);
}

my $var = mysub();
say $var;
say $var->get();
say $var + 42;
```

**Comment by hurricup** [comment]
This is more like it

![image](https://github.com/user-attachments/assets/f37c86ac-d45a-4ddd-881f-35e63f9a1df9)

**Comment by hurricup** [comment]
You may try the plugin from this build, should be much better now. 2024.2 only
https://github.com/Camelcade/Perl5-IDEA/actions/runs/10441479770/artifacts/1824754313
