### ISSUE TITLE
Set website in GitHub repository

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2888]
I propose setting
https://plugins.jetbrains.com/plugin/7796-perl
as the website for this GitHub repository.

Because it's easy to access the plugin page and also helps linking the source to the binary (GitHub to Marketplace).

To be shown under About (on the right) along with topics:
![image](https://github.com/user-attachments/assets/473e5c22-9ec9-4cd1-a79a-5ec9fa94f733)

![image](https://github.com/user-attachments/assets/6b54a2b2-3309-4ce9-8a4b-5d4aa76d93d1)

This field is currently empty, but can benefit from the linking 🙂

**Comment by hurricup** [comment]
Done, thank you!!! The usability of this option is just the worse. Browsed all the settings pages to find it :(
