### ISSUE TITLE
Concatenating to `$$` yields "semicolon expected" error

### ISSUE THREAD

**Issue by scop** [Camelcade/Perl5-IDEA#2912]
* IDE name and version, including build: GoLand, Build #GO-242.22855.106, built on September 22, 2024
  * Perl5 plugin version: 2024.2.2
  * JRE version: Runtime version: 21.0.3+13-b509.15 amd64 (JCEF 122.1.9), VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  * Your OS name and version: Ubuntu 24.04.1

Concatenating a string to `$$` (current process id) yields a false "semicolon expected" error on the opening quote of the string to be concatenated:

``` perl
my $foo = $$."foo";
           # ^here
```

See also attached screenshot.

![Screenshot from 2024-09-23 13-12-58](https://github.com/user-attachments/assets/c0121088-abe5-4f83-815d-977c8562482a)

**Comment by hurricup** [comment]
Ye, seems plugin treats it as `${$.}`

**Comment by hurricup** [comment]
Similar to #1893
