### ISSUE TITLE
!die "message" is NOT unreachable code

### ISSUE THREAD

**Issue by michael-meron** [Camelcade/Perl5-IDEA#2919]
_PhpStorm 2024.2.3 Build #PS-242.23339.16, built on September 25, 2024
macOS 15.0.1
Non-Bundled Plugins:
  com.perl5 (2024.2.2)_

The IDE flags each occurrence of `!die` as 'unreachable code', such as in, for example ...

`@dirnames = grep { -d or !die "Not a directory: '$_'\n" } @dirnames;`

This is wrong. The code, as well as the code following it, is well reachable.
Please fix. :)

**Comment by hurricup** [comment]
Plugin builds incorrect control flow for `-d or !die "Not a directory: '$_'\n"`
![image](https://github.com/user-attachments/assets/d12fbad3-eb9a-4fa4-b626-6c092bfe88b8)

**Comment by hurricup** [comment]
Oh. It is actually correct. Highlighting is kinda misleading. 
The problem here is that negation is never reached as you can see on the graph above, because control will die, so negation is redundant here.
