### ISSUE TITLE
Mysterious Multiple definitions warnings

### ISSUE THREAD

**Issue by morehockeystats** [Camelcade/Perl5-IDEA#2936]
I get Multiple namespace definitions / Multiple sub definitions warning, but I can't understand where the duplicates happen. I cleaned the blib directories, although the IDE was set to ignore it from the start. How can I figure out where the duplicates are being found?

IDEA Build #IU-242.23726.103, built on October 23, 2024
Plugin 2024.2.3
Ubuntu 22.04.5
Perl 5.40.0, locally compiled, installed in /usr/local/bin
JRE openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

**Comment by hurricup** [comment]
there should be a quickfix to navigate or just try to navigate to declaration. And there should be multiple variants.
