### ISSUE TITLE
The parser does not understand the delimiter curly bracket in a regular expression.

### ISSUE THREAD

**Issue by prtscr-master** [Camelcade/Perl5-IDEA#2948]
The following match is not parsed correctly: 

`my $p = $f =~ s{\A$gitPath[/]}{}r; `

It gives an error on the slash (/). If I escape it, it parses correctly, i.e., 

`my $p = $f =~ s{\A$gitPath[\/]}{}r; `

Please advise.

**Comment by hurricup** [comment]
I see. This is a funny and tricky case.
The plugin considers `$gitPath[` as a start of array element and attempts to parse an index. Inside it sees the start of regular expression `/` and this is where things break.
I'll check if I can fix it, but for now you may escape backslash or remove the grouping brackets, they are unnecessary in this particular example.

**Comment by hurricup** [comment]
And this is a valid syntax for perl:
```
use strict;
use warnings FATAL => 'all';
use v5.10;

my @test = (1,2,3);
$_ = "1";
say /1/;
say $test[/1/];
```

**Comment by hurricup** [comment]
And seems there is a logic to avoid this, but it is incomplete for some reason. Introduced in https://github.com/Camelcade/Perl5-IDEA/commit/a92edc9830cbb808c7f000d294f3d2e3717e9a3a
