### ISSUE TITLE
Isolate moo/moose attributes from functions in structure view

### ISSUE THREAD

**Issue by elcamlost** [Camelcade/Perl5-IDEA#770]
I think, qr/moo(se)?/ attributes is not exactly the functions - they combine object property, accessor  functions and maybe some other fucntions (like triggers or builders). So it'll be more appropriate to give them its own icon at structure view panel
![icons structure view](https://cloud.githubusercontent.com/assets/5188593/12387057/ef821620-bdda-11e5-8fe3-aeb83b223152.png)

**Comment by hurricup** [comment]
I'm not sure that attributes declared with qr// are handled in any way at the moment.

**Comment by elcamlost** [comment]
Oh, sorry, I misguided you. It was just more perlish and compact way to tell "moo or moose" ))

**Comment by hurricup** [comment]
Ok, reviewing user feedback atm. Basically, all properties are just subs, generated by has statements.
Now all (if everything works right) such subs are supported. And unclear what to filter here. All of them? accessors? readers? I have not enough exerience to decide here. Suggestions?

**Comment by elcamlost** [comment]
Our project has a lot of perl moo-based classes with a lot of accessors. So I want to filter all Moo attributes by their names (part after has, not reader) and go to attribute definition. It can contain default or trigger function as anonymous subs and so on.

Also each attribute can generate a lot of other functions dynamically (reader, writer, builder, predicate, clearer, and endless handlers). And all this functions (not attribute name) probably must be available for method name completion.

So I suggest separate attribute list and give opportunity to filter dynamic functions from function list

**Comment by hurricup** [comment]
How about togglable grouping, like: 

![This](http://dl4.joxi.net/drive/2017/07/14/0004/3351/294167/67/2ff4478882.png)

This is cratch, attr name and location missing yet

**Comment by elcamlost** [comment]
Amazing!


14.07.17 22:15, Alexandr Evstigneev пишет:

**Comment by hurricup** [comment]
You may build plugin from https://github.com/Camelcade/Perl5-IDEA/tree/2017.1 and try new feature

**Comment by elcamlost** [comment]
Thanks, I try. Build was successfull, now i investigate features.

There were some warnings during the build

```

 > Task :generatePerl5Parser
BNF_RULE:last_expr: unexpected cardinality OPTIONAL of expr, treating as 
ATOM
BNF_RULE:next_expr: unexpected cardinality OPTIONAL of expr, treating as 
ATOM
BNF_RULE:goto_expr: unexpected cardinality OPTIONAL of expr, treating as 
ATOM
BNF_RULE:redo_expr: unexpected cardinality OPTIONAL of expr, treating as 
ATOM
BNF_RULE:deref_expr: 'expr ( <op> expr) +' expected for N-ary operator, 
treating as POSTFIX
```

Not sure they are meaning something, just for your knowledge


15.07.17 20:49, Alexandr Evstigneev пишет:
