### ISSUE TITLE
Template Toolkit support

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#796]
http://template-toolkit.org/docs/manual/index.html

**Comment by earandap** [comment]
When you plan release this feature?

**Comment by hurricup** [comment]
Current build is going to be about debugger. Assigning to the next one. Going to be in the end of June

**Comment by hurricup** [comment]
You may try RC version http://evstigneev.com/IDEA-Perl5-2.006.zip

**Comment by earandap** [comment]
Great work! I've been testing it all day. I'll send some issues I encountered.

**Comment by hurricup** [comment]
Added completion and navigation for files and blocks. http://evstigneev.com/IDEA-Perl5-2.007.zip
Waiting for your feedback only.

**Comment by earandap** [comment]
After update to 2.0007 i got this error http://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-215

**Comment by hurricup** [comment]
Dam. Try http://evstigneev.com/IDEA-Perl5-2.008.zip

**Comment by earandap** [comment]
I am working on a project with Perl legacy code, there is a lot of code like this: 

```
[%+ IF page_params.page_type == "member" +%]
    <script type="text/javascript" src="[% js_path %]/member/script.js"></script>
    [% PROCESS "member/resale/members_js.tt" %]
[% END %]
```
`[%+ IF page_params.page_type == "member" +%]` is showing unexpected token, due '+' character at the begin and end

http://template-toolkit.org/docs/manual/Config.html#section_PRE_CHOMP_POST_CHOMP

**Comment by hurricup** [comment]
oh. missed them. Implemented only minus.

**Comment by earandap** [comment]
This is not working
`[% #this is a comment  %]`

It is working
```
[% #this is a comment  
%]
```

**Comment by hurricup** [comment]
I thought it should work till the end of the line, not close marker

**Comment by earandap** [comment]
If the comment is like this
`[%# this is a comment %]` 
the all line will be a comment, notice that `[%# `, but if is not next `[% # ` the line can be finished with CLOSE_TAG

**Comment by hurricup** [comment]
Please try http://evstigneev.com/IDEA-Perl5-2.009.zip
Fixed problem with chomp modifiers and line comment

**Comment by hurricup** [comment]
Would be nice if you could run code analysis on tt files to find all the errors. Also, if you have skype, would be nice if you could contact me: hurricup

**Comment by hurricup** [comment]
How is the last build going?

**Comment by earandap** [comment]
It is better by far. Great work!.

**Comment by hurricup** [comment]
Could you run code analysis on your codebase to find out all errors?

**Comment by bbarker** [comment]
Looking forward to this, will try to get a few days of perl coding soon to
make the switch.

**Comment by earandap** [comment]
How can I run code analysis? I am using WebStorm with this plugin

**Comment by hurricup** [comment]
On the folder with templates, right mouse click
![than](http://joxi.net/n2Y8bylFj86Qbm.png)
Create inspection profile and disable all inspections, except `General->Syntax error` 
And run it.

**Comment by earandap** [comment]
Done. [Code Analis](https://drive.google.com/open?id=0B1uh1YyWMIJdZWM3QTljTGc3ZzQ)

**Comment by hurricup** [comment]
Nono, it useless without the code. You should check what been found and make me examples.

**Comment by earandap** [comment]
I got it.  Do you want the examples as new issues?

**Comment by earandap** [comment]
It is possible define  different colors for TT language?

**Comment by hurricup** [comment]
yep, create one issue for all problems.
Atm it uses colors from perl settings.
