### ISSUE TITLE
Child indent is incorrect in anonymous hash (without plus) passed as subroutine argument

### ISSUE THREAD

**Issue by miralita** [Camelcade/Perl5-IDEA#913]
Valid formatting:

```
my $var = {
    k1 => 'v1',
    k2 => 'v2',
};

test1( +{
        k1 => 'v1',
        k2 => 'v2',
    } );
```

Broken formatting:

```
test1( {
        k1     => 'v1',
            k2 => 'v2',
    } );
```

I know it is very difficult to distinguish between this case and code block. May be it is better to declare plus as required in code styles :)

**Comment by hurricup** [comment]
This can't be done with current parser. It does not take prototypes into account and can't always distinct code block from hash :(
I'm using tmp variables in such situations. And i'm not sure how plus before will affect the program :)

**Comment by hurricup** [comment]
May be it's not a bad idea to consider this block as anon hash all the time. But need to think about drawbacks

**Comment by miralita** [comment]
Plus and "do" are legal distinguishing signs for perl compiler :) But I slightly curious that it has the same effect on Java parser

**Comment by hurricup** [comment]
Hm. Didn't know about plus. And I thought that perl doesn't need hints, it's just checks prototype and treats opening brace as hash or block beginning.

Well, it's not a java parser. It's perl parser written in java (generated from bnf with manual extensions) and i've tried to make it mimics perl's parser in all possible ways. But IDEA's architecture does not allow me to use the same approach as in perl, where lexer and parser works together.

**Comment by miralita** [comment]
> May be it's not a bad idea to consider this block as anon hash all the time

Please don't forget about below cases which are code blocks:
```
{
	my $static;
	sub test {
		# init pseudo-static variable
	}
}

{
	local $global_var;
	sub test {
		# ...
	}
}
```

The problem also reproduces when subroutine is called without curly braces:
```
test1 {
		k1     => 'v1',
			k2 => 'v2',
	}
```

**Comment by miralita** [comment]
>  And I thought that perl doesn't need hints, it's just checks prototype
I can't present any working example, but I met cases in past when perl treat my hashes as code blocks. It is very rare case but doesn't impossible. I will write if I recall :)

**Comment by hurricup** [comment]
Nono, distinction problem exists only in two cases:
1 Bare hash, like:
```
sub somesub{
  {  # we can't say if it's block or hash and i have no idea how to do it.
     key => 42
  };
}
```

2 Parameter for subs with (&) proto, when we omit sub on first code block argument and has no second argument without comma:
```
sub somesub(&);

# here perl checks prototype of somesub, finds & there and knows that 
# block is actually sub{ say 'here we go!'; }. And i can't do that
somesub { say 'here we go!'; }; 
```
I've suggested that we can try to parse second case as hash all the time. 
Atm it looks like:
```
call_arguments ::=
    anon_hash comma list_expr
    | block [[comma] list_expr]
    | list_expr
```
So if no comma afterwords - it's a block :)

**Comment by miralita** [comment]
Oh, yes, I just was going to write the same thing after RTFM :)
